### ISSUE TITLE
Add a Create Account page

### ISSUE THREAD

**Issue by eclipsewebmaster** [openhwgroup/openhwgroup.org#101]
Add "Create Account" to the top portion of the website that links to a page on the openhwgroup website.

The contents of that page should be along these lines:

To join and participate in the Working Groups, industry collaborations that drive the roadmap and development of new open source hardware and related software platforms, the OpenHW Group leverages the GitHub development platform, and the development processes provided by the Eclipse Foundation.

* Step 1: Create a (link)GitHub account(/link) and take note of your GitHub ID
* Step 2: Create an (link)Eclipse Foundation account(/link) and associate it to your GitHUb ID
* Step 3: Browse our (link = https://github.com/openhwgroup) repositories on GitHub) and contribute!
* Step 4: Become an openHW Group (link)Member(/link)

Contributions to GitHub (via Pull Requests) may not pass the Eclipse Foundation's development and Intellectual Property processes if your GitHub account is not linked to your Eclipse Foundation account.

**Comment by chrisguindon** [comment]
I created draft of this new Create account page:
https://deploy-preview-103--eclipsefdn-openhwgroup.netlify.com/register/

**Comment by chrisguindon** [comment]
Done!
