### ISSUE TITLE
Create a Projects page

### ISSUE THREAD

**Issue by eclipsewebmaster** [openhwgroup/openhwgroup.org#102]
Create a Projects page where the list of openHW Group projects (Task Groups) are listed. This would mimic the list of projects on the openHW Group Organization:
https://github.com/openhwgroup

From this page, provide links to the Create Account page (suggested in issue 101) and the Membership pages.

**Comment by autumnfound** [comment]
Please see https://deploy-preview-105--eclipsefdn-openhwgroup.netlify.com/projects for updates

**Comment by eclipsewebmaster** [comment]
Just a minor nit with your last commit. See comment.

**Comment by autumnfound** [comment]
> Just a minor nit with your last commit. See comment.

@eclipsewebmaster done!

**Comment by chrisguindon** [comment]
Thank you @autumnfound
