### ISSUE TITLE
CORE-V Chassis image

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#106]
please add the image below into the body of the CORE-V Chassis news post of Dec 10th.  If possible include "CORE-V Chassis" as a title under the image.

![CORE-V Chassis](https://user-images.githubusercontent.com/2498391/71195303-a5f6ba80-225b-11ea-98ef-73985e81ed2c.png)

**Comment by autumnfound** [comment]
This is live https://www.openhwgroup.org/news/2019/12/10/openhw-group-announces-core-v-chassis-soc-project-and-issues-industry-call-for-participation/
