### ISSUE TITLE
INZONE.AI new member logo

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#107]
Please add the INZONE.AI as a new member to the home page and members page with a link to http://www.inzone.ai/

![inzoneai](https://user-images.githubusercontent.com/2498391/71313013-f5c2b680-2400-11ea-8956-6ee7553f66fa.png)

**Comment by autumnfound** [comment]
This is live. https://www.openhwgroup.org/#members-partners
