### ISSUE TITLE
new Membership Application Form

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#108]
Please update the text as shown below on page https://www.openhwgroup.org/membership/contact/
The existing Bylaws, Membership Agreement and Email us links should be maintained with a link added for the attached Membership Application PDF.
[OpenHW Group - Membership Application Form.pdf](https://github.com/openhwgroup/openhwgroup.org/files/3992936/OpenHW.Group.-.Membership.Application.Form.pdf)

Updated text below...

To become a member, follow these steps:

1 - Read the Bylaws, then complete the Membership Application form and sign the Membership Agreement.
2 - Email us PDF copies of the completed Membership Application form and the signed Membership Agreement.

**Comment by autumnfound** [comment]
Changes to text + PDF are live
