### ISSUE TITLE
Add CORE-V-DOCS to the Projects Page

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/openhwgroup.org#111]
Add the CORE-V-DOCS project to the Projects page (https://www.openhwgroup.org/projects/).  The Projects page already includes the CORE-V-VERIF and RISC_VM projects.

The by-line can be "Design, Verification and Platform documentation for the CORE-V family of RISC-V cores."

VIEW THE REPOSITORY should link to https://github.com/openhwgroup/core-v-docs.

**Comment by autumnfound** [comment]
This is live https://www.openhwgroup.org/projects/
