### ISSUE TITLE
New Member University of Utah

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#113]
Please add the U of Utah as a new member to the home page and members page with a link to
https://sites.google.com/site/pegaillardon/research/openfpga

![UlogoHv1-1200px](https://user-images.githubusercontent.com/2498391/72185822-b6fd9c00-33c1-11ea-9319-bdb0cca6fb9c.png)

**Comment by autumnfound** [comment]
This is live!

**Comment by rickoco** [comment]
Please update the web link to https://www.ece.utah.edu/

**Comment by chrisguindon** [comment]
Thanks @autumnfound
