### ISSUE TITLE
New member University of Ottawa

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#115]
Please add the U of Ottawa as a new member to the home page and members page with a link to
http://carg.site.uottawa.ca/index.html

[uottawa_hor_wg9_cmyk.eps.zip](https://github.com/openhwgroup/openhwgroup.org/files/4051637/uottawa_hor_wg9_cmyk.eps.zip)

**Comment by autumnfound** [comment]
This is live!
