### ISSUE TITLE
name change inzone.Ai to verifAi.ai

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#120]
please change the name of Inzone.AI to VerifAi, replace the existing logo with the attached logo and point to verifai.ai

![2-Print-ready logo-01](https://user-images.githubusercontent.com/2498391/72915447-9679fe00-3d40-11ea-87f7-55dab5aeb074.png)

**Comment by autumnfound** [comment]
Is there an update to the link as well, or should it point ar the inzone link?

**Comment by rickoco** [comment]
see above text - verifai.ai is the new url

**Comment by autumnfound** [comment]
This is live
