### ISSUE TITLE
member urls

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#123]
It looks like the url links in the member / partner directory do not point to the actual member sites as they do on home page where the member logos are located...
https://www.openhwgroup.org/membership/members/

**Comment by chrisguindon** [comment]
@rickoco Is it correct for us to assume that all OpenHWGroup members are Eclipse Foundation members?

**Comment by chrisguindon** [comment]
I am asking, since our standard procedure is to link to members page such as https://www.eclipse.org/membership/showMember.php?member_id=1380

**Comment by chrisguindon** [comment]
I spoke to Paul W. about this and the "Supporter members" is the membership level for Eclipse Members.

@autumnfound Can you fix the member urls?

**Comment by chrisguindon** [comment]
If possible, let's fix the logic in the base theme:

1. if we have id, use that to link to eclipse.org.
2. use website_url if set,
3. no link

**Comment by autumnfound** [comment]
This is live
