### ISSUE TITLE
new member PolyMtl

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#133]
Please add Polytechnique Montreal as a new member to the home page and members page with a link to https://www.polymtl.ca/en
![polytechnique_genie_impact_droite_eng_cmyk](https://user-images.githubusercontent.com/2498391/74563392-b6b16d00-4f3a-11ea-87c0-f88a712f9dbb.jpg)

**Comment by autumnfound** [comment]
This is live
