### ISSUE TITLE
pls restore #members-partners link

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#140]
This link used to jump to the members-partners section of the home page, but seems to have been removed with the most recent new member additions.   There are external sites that link to this url, so can it pls be restored?

https://www.openhwgroup.org/#members-partners

**Comment by autumnfound** [comment]
That still works for me, could you test again?

**Comment by rickoco** [comment]
weird - works for me now as well.  sorry for the bother...
