### ISSUE TITLE
news release

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#141]
Could you please post the attached news item on our site today?
Also, pls shorten the number of news items shown on the home page to be more/less in line with the events sections.
[OHW004 OpenHW Group announces rapid membership growth.docx](https://github.com/openhwgroup/openhwgroup.org/files/4244823/OHW004.OpenHW.Group.announces.rapid.membership.growth.docx)

**Comment by autumnfound** [comment]
This is live
