### ISSUE TITLE
Homepage members section is becoming crowded

### ISSUE THREAD

**Issue by autumnfound** [openhwgroup/openhwgroup.org#150]
With the number of members on the page, the main members section on the homepage is becoming very crowded. I'd like to suggest that we trim down the number of standard members shown on page load, while maintaining all of the sponsors. The members shown would be randomized and ordered, with a call to action to see all members (so people know there are many more members to see).

Below I've included a sample without ordering, showing 6 random members. I would spend a little more time fixing the alphabetical order if we go ahead with the feature. @rickoco what do you think?

![Example](https://user-images.githubusercontent.com/23018241/76118862-2c4dad80-5fbc-11ea-9686-32d4f03e5ac6.png)

**Comment by rickoco** [comment]
Looks good @autumnfound  - where would the "See All Members" link go to?  A new page with all logos?  The member directory is not particularly useful IMHO.

Also, do the same thing with the Partners section - so we only have 1 row of partner logos just like the members logos.

**Comment by autumnfound** [comment]
The idea would be to direct people to the member directory currently. We can update this to redirect users to the proper tab for the given group, so members to the members view of the directory, and the partners button to the partners view. Would that work?

**Comment by autumnfound** [comment]
Example with alphabetical sorting + partners:
![image](https://user-images.githubusercontent.com/23018241/76120644-eabf0180-5fbf-11ea-84ed-80f6717deaaa.png)

**Comment by rickoco** [comment]
Actually - for now, let's leave the members / partners sections on the home page as is.  There's benefit to showing this many logos.  Clearly, as we add more members, we'll need to change this - but leave as is for the next few months at least.
