### ISSUE TITLE
new partner Digilent

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#151]
please add Digilent as a new partner and link to https://store.digilentinc.com/

![digilent-logo_ni-3000](https://user-images.githubusercontent.com/2498391/76263346-05e67700-6235-11ea-81bf-1cc614dfd0c0.png)

Also, pls always keep Norton Rose, PWC and RBC alone on the bottom row of the Partner section.

**Comment by autumnfound** [comment]
I've added digilent to the partners section
