### ISSUE TITLE
Create an About us and Working Groups page

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/openhwgroup.org#160]
- Create an About us page (https://www.openhwgroup.org/about/)
  - Replace About Us link in main menu with a link to this new page
  - Content: https://docs.google.com/document/d/1ZiRJN6InhxX2uEAI4vDhFCOXaH4tnsnodQq-Y7mZye0/edit

- Create a Working Groups page (https://www.openhwgroup.org/working-groups/)
  - Replace CORE-V Family link with a link to the new Working Groups page
  - Content: https://docs.google.com/document/d/1gCDjCIsCDLnpgkvP3OQOG6FkOE_5ufoUIbTcXmpmMvE/edit

### Requirements

- We will probably want to create a data file to manage these list of people.
- We won't have any profile picture but we expect to have them in the future.
- Rick would like us to use a linkedin widget or one of our icons instead of a text link for Linkedin links.

**Comment by chrisguindon** [comment]
@rickoco Please let us know if we are missing anything for this request!

**Comment by chrisguindon** [comment]
Deadline: May 7, 2020

**Comment by rickoco** [comment]
> @rickoco Please let us know if we are missing anything for this request!

looks good so far @chrisguindon - thanks for this...

**Comment by autumnfound** [comment]
Since there is now a separate page, should we remove the About Us section on the home page?

**Comment by chrisguindon** [comment]
> Since there is now a separate page, should we remove the About Us section on the home page?

No, we plan on keeping that section for now.

**Comment by autumnfound** [comment]
@rickoco please see the following link for a preview of my current draft https://deploy-preview-161--eclipsefdn-openhwgroup.netlify.app 

The one section I wasn't fully sure about was the chair members for each of the working groups. Right now I have it set up tentatively in a way we could transition into a row of headshots + quick facts about the member. If you like the general idea, I would invest more time centering the content to make it symmetrical.

**Comment by chrisguindon** [comment]
Quick feedback feedback:

- I don't like the LINKEDIN button. It should be spelled "LinkedIn". Is there a javascript or an icon we could use to make this look nicer?

- Update the casing of titles: For example "Working group chairs" should be "Working Group Chairs".

**Comment by autumnfound** [comment]
The casing on the buttons was a design decision for the site. Rick has already requested the removal of the forced casing and is up for PR now.

**Comment by rickoco** [comment]
> Quick feedback feedback:
> 
> * I don't like the LINKEDIN button. It should be spelled "LinkedIn". Is there a javascript or an icon we could use to make this look nicer?
> * Update the casing of titles: For example "Working group chairs" should be "Working Group Chairs".

I agree with @chrisguindon - not a big fan of the LinkedIn button style.  Looks like we're missing the LinkedIn links for the TWG and MWG chairs.  Also, we don't need "Working Group Chairs" or "Task Group Chairs" titles ahead of the Chairs info.

**Comment by autumnfound** [comment]
Working groups page has been updated in preview: https://deploy-preview-161--eclipsefdn-openhwgroup.netlify.app/working-groups/

**Comment by chrisguindon** [comment]
I would switch the working groups and about us link.

I think it would be best to include **About us** as the first link.

Can we also stop using all caps in the button links?

**Comment by chrisguindon** [comment]
It looks like we are done here!

Thank all!
