### ISSUE TITLE
OpenHW TWG Mailing lists

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#163]
Please add the following sentence and link at the end of the Technical Working Group section of the [Working Groups page](https://www.openhwgroup.org/working-groups/) right after the Co-Chair name info.

You can join the [OpenHW TWG Mailing List here.](https://accounts.eclipse.org/mailing-list/openhw.twg)

**Comment by autumnfound** [comment]
This is live.
