### ISSUE TITLE
OpenHW CORE-V Cores mailing list

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#164]
Please add the following sentence and link at the end of the Cores Task Group section of the [Working Groups page](https://www.openhwgroup.org/working-groups/) right after the Co-Chair name info.

You can join the [OpenHW CORE-V Cores Mailing List here.](https://accounts.eclipse.org/mailing-list/openhw.core-v.cores)

**Comment by autumnfound** [comment]
This is live.
