### ISSUE TITLE
OpenHW CORE-V SW mailing list

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#166]
Please add the following sentence and link at the end of the SW Task Group section of the [Working Groups page](https://www.openhwgroup.org/working-groups/) right after the Co-Chair name info.

You can join the [OpenHW CORE-V SW TG Mailing List here.](https://accounts.eclipse.org/mailing-list/openhw.core-v.sw)

**Comment by autumnfound** [comment]
This is live.
