### ISSUE TITLE
Sponsors & Partners section issue

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#17]
In a chrome browser on a mac (safari is fine), the Sponsors and Partners section is not displayed at all.

**Comment by ericpoirier** [comment]
Hi Rick, I'm also using Chrome on mac and I see that section properly. I also asked my colleague to verify on Linux and it works as well.

Can you hard refresh (Shirt + R) that page and see if it changes anything?

**Comment by rickoco** [comment]
tried flush and hard re-fresh, no dice...

**Comment by ericpoirier** [comment]
Can you send a screenshot of what you are seeing?

**Comment by rickoco** [comment]
<img width="1440" alt="Screen Shot 2019-06-04 at 11 15 41 AM" src="https://user-images.githubusercontent.com/2498391/58891251-2b4cc000-86ba-11e9-9f7e-0891c5134e74.png">

see attached - the sponsor / partner section is just a thin white line...

**Comment by ericpoirier** [comment]
Ah you know what, I bet its because you have an Ad blocker in your browser and that section's name contains the word "sponsors" in it.

If you do have an Ad blocker, can you turn it off to see if that section appears. If so, I will rename that section to something else.

**Comment by rickoco** [comment]
You nailed it.  Rename 'Sponsors' to 'Members' and that should do it.

**Comment by ericpoirier** [comment]
Hi Rick,

I renamed the classes for that section and and also installed an Ad blocker in my browser to test and it seems to be working fine on my end. Can you confirm that it is working as well for you?

Thanks.

**Comment by rickoco** [comment]
Confirmed - working fine...  Issue Closed
