### ISSUE TITLE
new member AB Open

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#171]
Please add new member AB Open and link to abopen.com
[datum_logoV2.eps.zip](https://github.com/openhwgroup/openhwgroup.org/files/4635754/datum_logoV2.eps.zip)

**Comment by autumnfound** [comment]
You have attached the Datum logo from the previous issue. Did you have a specific image you wanted us to use for AB Open?

**Comment by rickoco** [comment]
sorry - here is the correct AB Open logo...
[AB Open - Logo.svg.zip](https://github.com/openhwgroup/openhwgroup.org/files/4653963/AB.Open.-.Logo.svg.zip)
