### ISSUE TITLE
OpenUK new partner

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#176]
please add OpenUK as a new partner and link to https://openuk.uk/
![OpenUK logo](https://user-images.githubusercontent.com/2498391/83689542-3122fd00-a5bd-11ea-98c4-0534d014bb1f.png)

**Comment by rickoco** [comment]
OpenUK belongs in the Partner section not in the Member section...

**Comment by chrisguindon** [comment]
@rickoco How about this: https://deploy-preview-178--eclipsefdn-openhwgroup.netlify.app

**Comment by rickoco** [comment]
> @rickoco How about this: https://deploy-preview-178--eclipsefdn-openhwgroup.netlify.app

sorry OpenUK should be within the partners technology section.  Norton Rose, PWC & RBC should be alone in the bottom row of the partners section as they are non-technology partners.  Also, Digilent should be moved into alphabetical order in the partners tech section.

**Comment by rickoco** [comment]
> How about this?
> https://deploy-preview-178--eclipsefdn-openhwgroup.netlify.app/
> 
> I needed to shrink some of the images to make this work.

Yes @chrisguindon - this is good.
