### ISSUE TITLE
Calendar for openhwgroup.org

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#188]
Please integrate the calendar for meetings@openhwgroup.org on the openhwgroup.org website with a link from the Eclipse project page.

(I’ll send you the password privately if needed.)

The calendar look and feel should be similar to the Eclipse IOT calendar at 
https://calendar.google.com/calendar/embed?src=meetings%40openhwgroup.org&ctz=America%2FToronto

Similar to Eclipse IoT, people should be able to download the Ical calendar to their local client if they wish.

** The calendar details for meetings@openhwgroup.org are at:
The  Calendar ID
meetings@openhwgroup.org

Public URL
https://calendar.google.com/calendar/embed?src=meetings%40openhwgroup.org&ctz=America%2FToronto

Embed Code
<iframe src="https://calendar.google.com/calendar/embed?src=meetings%40openhwgroup.org&ctz=America%2FToronto" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

Public Address in ICAL format
https://calendar.google.com/calendar/ical/meetings%40openhwgroup.org/public/basic.ics

**How we will use the calendar
To add an item:
-	TG chairs or others setting up calls or face-face events would include meetings@openhwgroup.org on their invite list.
-	It is configured to auto-accept meeting invites.
-	Calendar items will contain all the zoom details 

To change/delete meetings
-	(I have tested meeting changes/deletions and it works appropriately)
-	We would request all WG chairs to double check the calendar after adding or changing an item. 

** Placement:
-	  The calendar should be available at openhwgroup.org (Under https://www.openhwgroup.org/working-groups/)
-	A link from the eclipse project page should lead to the calendar at the openhwgroup.org  https://projects.eclipse.org/projects/openhw/developer

**Comment by autumnfound** [comment]
Where on the page should this be included, and should there be any associated content/instructions regarding the content of the calendar?

**Comment by DBees** [comment]
Please add a section called OpenHW Working Group Calls above the green footer at the bottom of the page.

The header should be the same font/size as Marketing Working Group.

The text is as below, with the links pointing to the calendar details. 

In case of any questions please call Duncan Bees at 604 418 8997

Thanks

Duncan

 

OpenHW Working Group Calls

 

 

All the OpenHW Group Working Calls are managed through a single shared Google calendar.

You can find a web version of this shared calendar here. 

It is available here in ICal format, which is compatible with most desktop calendar clients.

**Comment by DBees** [comment]
Actually the OpenHW is repetitive: You can just use this simplified text:

 

 

Working Group Calls

 

 

All the Working Group Calls are managed through a single shared Google calendar.

You can find a web version of this shared calendar here. 

It is available here in ICal format, which is compatible with most desktop calendar clients.

 

 

From: Duncan Bees <duncanbees@gmail.com> 
Sent: June 29, 2020 12:30 PM
To: 'openhwgroup/openhwgroup.org' <reply@reply.github.com>; 'openhwgroup/openhwgroup.org' <openhwgroup.org@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [openhwgroup/openhwgroup.org] Calendar for openhwgroup.org (#188)

 

Please add a section called OpenHW Working Group Calls above the green footer at the bottom of the page.

The header should be the same font/size as Marketing Working Group.

The text is as below, with the links pointing to the calendar details. 

In case of any questions please call Duncan Bees at 604 418 8997

Thanks

Duncan

 

OpenHW Working Group Calls

 

 

All the OpenHW Group Working Calls are managed through a single shared Google calendar.

You can find a web version of this shared calendar here. 

It is available here in ICal format, which is compatible with most desktop calendar clients.

**Comment by rickoco** [comment]
@chrisguindon @autumnfound - guys, any status here?

**Comment by DBees** [comment]
The calendar looks good.
Comments: 
1) it is hard to notice that "ICal format" in the sentence, "The shared calendar is also available in ICal format, which is compatible with most desktop calendar clients." is actually a link, as the text colour is very similar to the rest of the text. Can you make it in the same red colour as other links on that page? 

2) Also, there is one other link on the page in a different colour to the others, "You can join the OpenHW CORE-V HW TG Mailing List here." Please also make it in the same red colour.

3) Please provide  a link from the Eclipse project pages to the working group page.
The link should be provided  on both these pages:
https://projects.eclipse.org/projects/openhw.corev/developer
https://projects.eclipse.org/projects/openhw/developer

The text of the link should say "OpenHW Group Working Groups and Calendar". 
Also, remove the sentence in both places saying "The project has not provided information for this page."

Thank you
Duncan
