### ISSUE TITLE
Post news article: OpenHW TV Episode 1 now available on-demand

### ISSUE THREAD

**Issue by shanda-eclipse** [openhwgroup/openhwgroup.org#190]
We would like the following news item hosted on the OpenHW site. We can use the newsroom to add it to the newsfeed, but the click-through link needs to be a page on OpenHW. Here is the content:

**Date:** Monday, June 29, 2020 
**Title:** OpenHW TV Episode 1 now available on-demand
**Body:** 
We live-streamed a world class first episode of OpenHW TV on 18th June and even exceeded our registration numbers, as guest presenters from Metrics and Imperas highlighted the open source CORE-V processor IP design verification plan. Our live Q&A session at the end with panellists from OpenHW Group including the Co-Chairs of our Verification Task Group was extremely popular and provoked some great discussion.

If you missed it, you can access the entire recording here: https://www.youtube.com/watch?v=GNElOjxo0GQ

Be sure to register for the next episode on 16th July @ 11am EST / 8am PST / 4pm BST which will look at the OpenHW Group CORE-V family of RISC-V processor cores, highlighting the CVE4 and CVA6.

![image](https://user-images.githubusercontent.com/61751191/86010503-80582400-b9e9-11ea-995d-5004835bb728.png)

**Comment by chrisguindon** [comment]
@autumnfound this is a request that came in from newsroom.eclipse.org 

OpenHWGroup prefers to host their news item on the website. We need to create this newspage on their website and post back a link on this issue once we are done.

@shanda-eclipse will update the news item on newsroom.eclipse.org with the link that we will provide.

**Comment by chrisguindon** [comment]
@shanda-eclipse https://openhwgroup.org/news/2020/06/29/openhw-tv-episode-1-now-available-on-demand/

**Comment by rickoco** [comment]
Thx @shanda-eclipse, @chrisguindon and @autumnfound for getting this up quickly.  The YouTube url should be attached the to the gallery image to be more intuitive IMHO and there is no reg link for episode 02 mentioned in the bottom of the text.  I'll have Andrea from Publitek provide the episode 02 reg link.

**Comment by chrisguindon** [comment]
@rickoco How about we embed the video on the page? //cc @autumnfound

**Comment by rickoco** [comment]
> @rickoco How about we embed the video on the page? //cc @autumnfound

yes pls @chrisguindon and @autumnfound
