### ISSUE TITLE
OpenHW TV page

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#192]
Pls create a separate OpenHW TV page with thumbnails and intro for each episode of OpenHW TV (from the news post) so the content is more readily accessible over time (not getting buried in a news roll).  So, this is a new page on the site (with an OpenHW TV link is the top menu) that aggregates the various OpenHW TV episodes into seasons much like the navigation you'd see in Netflix for example.

**Comment by chrisguindon** [comment]
Thanks for the bug report!

@rickoco I know you are looking for a Netlfix look and feel but I am wondering if we should do something similar to what we did for the Resources page for iot.eclipse.org: https://iot.eclipse.org/resources/

@ChristieWittEclipse Can you help with this issue? I am thinking we need to create a mockup before my team implements this.

**Comment by rickoco** [comment]
@chrisguindon - yes the IoT resources page would suite perfectly.  In fact the actual IoT video page is great https://iot.eclipse.org/community/resources/videos/  The only change I'd suggest is to show more text as the intro to each episode (as included in the news room post) to give viewers more detail on the episode so they can decide if they actually want to watch it.

**Comment by ChristieWittEclipse** [comment]
@chrisguindon I will make a mockup and add it here for approval before your team implements this.

**Comment by rickoco** [comment]
> @chrisguindon I will make a mockup and add it here for approval before your team implements this.

Hi @ChristieWittEclipse - do you know when you can have a mockup ready?

**Comment by ChristieWittEclipse** [comment]
@rickoco I will upload the mockup before the end of the day today.

**Comment by rickoco** [comment]
> @rickoco I will upload the mockup before the end of the day today.

Thx @ChristieWittEclipse

**Comment by ChristieWittEclipse** [comment]
@rickoco I've attached the mockup. Let me know what you think!
[Open-HW-Videos.pdf](https://github.com/openhwgroup/openhwgroup.org/files/4881001/Open-HW-Videos.pdf)

**Comment by rickoco** [comment]
> @rickoco I've attached the mockup. Let me know what you think!
> 
> ![Open-HW-Videos](https://user-images.githubusercontent.com/58480647/86636639-87ab9e80-bfa2-11ea-89e8-4aed8994ac55.jpg)

Looks great!  We'll dual host the videos on youtube as well as youku in China, so we'll also want a youku link option (not another thumbnail though).  Also, Title should be OpenHW TV instead of 'videos' and once we get into Season 2 we'll want to be able to collapse Season 1 in some fashion.

Overall, looks great!

**Comment by ChristieWittEclipse** [comment]
@rickoco Thanks for reviewing, I've implemented your feedback in the below mockup. I would suggest that when you start publishing Season 2, we add a button below those videos that says "View Season 1 Videos", which would link to an archive page. If season 1 is collapsable, the page will get very long and hard for users to navigate on mobile.
![OpenHW-Videos-v2](https://user-images.githubusercontent.com/58480647/86841472-f99ee900-c071-11ea-8704-1dbf91decab7.png)

**Comment by rickoco** [comment]
Thx @ChristieWittEclipse looks great.  Ready to go @chrisguindon

**Comment by chrisguindon** [comment]
Links of the work so far by @autumnfound 

- New Video: https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/resources/videos/
- Events: https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/events/

Assuming that all is well, my question is now: Where should we link to this new page? Should we create a new top-level menu item for videos?

**Comment by rickoco** [comment]
> Links for the work done so far by @autumnfound:
> 
> * New Video: https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/resources/videos/
> * Events: https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/events/
> 
> Assuming that all is well, my question is now: Where should we link to this new page? Should we create a new top-level menu item for videos?

Hi @chrisguindon and @autumnfound - both previews look good and ready to go.  Let's create a top level menu item called  'OpenHW TV' and no need to have 'Videos' as a title at the top of the page or in the url for that matter.  Publish away...

**Comment by chrisguindon** [comment]
@chrisguindon and @autumnfound - both previews look good and ready to go. Let's create a top level menu item called 'OpenHW TV' and no need to have 'Videos' as a title at the top of the page or in the url for that matter. Publish away...

@rickoco I made some changes to address your feedback:
https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/

My changes:

- Added a OpenHW TV top level menu item
- removed h1 title on https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/resources/videos/
- Renamed the page to OpenHW TV but the url is still  resources/videos/

Should we rename the URL from  /resources/videos/ to /openhwtv ?

**Comment by rickoco** [comment]
> @rickoco I made some changes to address your feedback:
> https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/
> 
> My changes:
> 
> * Added a OpenHW TV top level menu item
> * removed h1 title on https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/resources/videos/
> * Renamed the page to OpenHW TV but the url is still  resources/videos/
> 
> Should we rename the URL from /resources/videos/ to /openhwtv ?
> 
> If not, let me know and I will make this live!

Thx @chrisguindon - yes pls, rename the url to openhwtv

We have episode 02 ready and also have the Youku posts ready to embed.

**Comment by chrisguindon** [comment]
> Thx @chrisguindon - yes pls, rename the url to openhwtv

Done!

> We have episode 02 ready and also have the Youku posts ready to embed. See issue #200

+1 We will deal with that on issue #200. I would like to get this one on production first.

**Comment by chrisguindon** [comment]
The new url:
https://deploy-preview-199--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/
