### ISSUE TITLE
OpenHW TV Youku links

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#200]
please embed Youku streaming to the new OpenHW TV page in addition to the YouTube embedded viewer.  Episode 01 has now been posted to Youku 
https://player.youku.com/embed/XNDc0OTI4MzI2NA==?client_id=4d6c5c68498ff602

Embedded Youku player details can be found in the attached doc...
[YOUKU Front-end development.docx](https://github.com/openhwgroup/openhwgroup.org/files/4935013/YOUKU.Front-end.development.docx)

**Comment by shangyunhai** [comment]
@rickoco Episode 02 has been posted to Youku
https://player.youku.com/embed/XNDc1OTQ4MTA3Ng==?client_id=4d6c5c68498ff602

**Comment by autumnfound** [comment]
For the Youku link, I'd recommend that we stick with what was in the design in terms of look and feel. Have the youtube video embedded with a link to the Youku video as an alternative. This decreases duplication and clutter on the page and will make it a little more responsive. I can add the link to the page at least, I just didn't include it previously as there was no known link

**Comment by rickoco** [comment]
> For the Youku link, I'd recommend that we stick with what was in the design in terms of look and feel. Have the youtube video embedded with a link to the Youku video as an alternative. This decreases duplication and clutter on the page and will make it a little more responsive. I can add the link to the page at least, I just didn't include it previously as there was no known link

Yes, @autumnfound that is fine.  Pls go ahead with the episode 01 youku link.  We'll have the episode 02 youtube link to you shortly to go with the 02 youku link above posted here by @shangyunhai
