### ISSUE TITLE
New video upload to OpenHW TV page

### ISSUE THREAD

**Issue by AndreaFionda** [openhwgroup/openhwgroup.org#202]
Please can we upload the next episode of OpenHW TV to this page: (https://www.openhwgroup.org/resources/openhwtv/)

This should be posted as:

OpenHW TV S1 E02
The CORE-V family of RISC-V cores
July 16th 2020

The file format is MP4 which I can't upload but it is posted to the YT channel here: [https://www.youtube.com/watch?v=GNElOjxo0GQ&t=2711s ] (Please let me know how to get the file uploaded here if that's what's needed.)

Body:
Episode 2 of OpenHW TV gives an in-depth overview and progress to date of the CVE4 (previously RI5CY) and CVA6 (previously Ariane) cores with panelists from the OpenHW Group Cores Task Group answering questions in an interesting Q&A session at the end.

Also, could we rename episode 1 to say this:

OpenHW TV S1 E01
Open source IP verification
June 18th 2020

**Comment by autumnfound** [comment]
I can upload the second video, but there is no space in the mockup for a title, so I'd have to consult with our design folks about that if Rick gives the +1 for inclusion.

**Comment by autumnfound** [comment]
@rickoco See above

**Comment by AndreaFionda** [comment]
OK thanks @autumnfound - please do go ahead and upload the second video in the meantime. Thanks
