### ISSUE TITLE
Add OpenHW TV episode titles

### ISSUE THREAD

**Issue by autumnfound** [openhwgroup/openhwgroup.org#204]
It was requested in #202 to add an episode title for the following OpenHW TV episodes:

OpenHW TV S1 E02
The CORE-V family of RISC-V cores

OpenHW TV S1 E01
Open source IP verification

Currently, there is no dedicated space for this in the mockup, so we would have to add it in as content or make a layout change. This issue is to track the decision on placement of this and whether we want to add episode titles to the page.

@rickoco as this was from a community member, I wanted to check in with you before we work on implementation. I could create a quick mockup with the HTML at a later time so that we can see the different possible positions for these titles.

**Comment by rickoco** [comment]
Thx Martin @autumnfound - yes Andrea is from Publitek our Marketing / PR firm.  I've sent her a member invite to the repo.

2nd line in the title to show episode content is desireable.
