### ISSUE TITLE
OpenHW Group Hubspot integration

### ISSUE THREAD

**Issue by AndreaFionda** [openhwgroup/openhwgroup.org#205]
We would like to replace the existing MailChimp form across the OpenHW Group site where the "Join our mailing list" button occurs: 
Replace [https://mailchi.mp/77bbac3766fb/openhwgroup] with this Hubspot form: [https://share.hsforms.com/1XdNvwOBNRTONOVdZjwVleg4o9yd]

Thanks

Andrea

**Comment by chrisguindon** [comment]
@AndreaFionda To confirm, you simply need us to relate the link in the header and footer of the site?

**Comment by AndreaFionda** [comment]
Yes please! Thank you 👍
