### ISSUE TITLE
Add episode #03 of OpenHW TV to https://www.openhwgroup.org/resources/openhwtv/

### ISSUE THREAD

**Issue by AndreaFionda** [openhwgroup/openhwgroup.org#209]
Please can we add the following episode of OpenHW TV https://youtu.be/tZJ8-umar4k to the website page: (https://www.openhwgroup.org/resources/openhwtv/)

With the following text:

Episode 03 features our HW and SW Task Groups, as well as guest member Ashling. The Chairs of the groups talk about the work of the SW and HW Task Groups to date, including an outlook to future roadmaps. We also look in detail at the open source GNU toolchain for the CORE-V family of RISC-V cores provided by Embecosm, and Ashling presents an in-depth overview and live demonstration of the RiscFree Eclipse based IDE debug interface to the Genesys2 FPGA board. It's an opportunity to see the complete CORE-V MCU FPGA development environment and hear the questions from the live Q&A session at the end with our panelists.

**Comment by autumnfound** [comment]
Should we wait for the yooku links, or are we posting as is and updating with the additional video link later?

**Comment by AndreaFionda** [comment]
Thanks @autumnfound - can we post as is and add the link later as I've had a couple of requests for the on-demand already
