### ISSUE TITLE
New Global Foundries logo

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#214]
Please replace the current Global Foundries logo on the site with this one attached (leave url the same).

![GFonly-ORANGE-letters](https://user-images.githubusercontent.com/2498391/92187034-a30e1b00-ee26-11ea-976c-42bd77d6438e.png)

**Comment by annejacko** [comment]
Along with adding the Global Foundries logo, please add a log for Embecosm and QuickLogic. URLs are http://www.embecosm.com/
http://www.quicklogic.com/
http://globalfoundries.com/
![embecosm-logo](https://user-images.githubusercontent.com/29178654/92195749-8b349800-ee22-11ea-8d65-25feb6a73719.png)
![QL-Logo](https://user-images.githubusercontent.com/29178654/92195759-8ff94c00-ee22-11ea-8ea8-5ed01b68f1f4.png)
