### ISSUE TITLE
Add the Youku link of episode #03 of OpenHW TV to website

### ISSUE THREAD

**Issue by shangyunhai** [openhwgroup/openhwgroup.org#216]
Please can  we add the Youku link of episode of #03  to website, it's a late link.

Many thanks.

**Comment by shangyunhai** [comment]
The link of video is: https://player.youku.com/embed/XNDg0NjY0MTM1Ng==?client_id=4d6c5c68498ff602

**Comment by rickoco** [comment]
Any progress here?
