### ISSUE TITLE
Please add Codeplay Software's logo on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#222]
Hello,
Please add the attached Codeplay Software's logo to OpenHW Group's website https://www.openhwgroup.org/
[[Accepted] 2017 - Color Logo.zip](https://github.com/openhwgroup/openhwgroup.org/files/5301268/Accepted.2017.-.Color.Logo.zip)

Thank you,
Zahra

**Comment by autumnfound** [comment]
@rickoco @ZahraFazli  at what level should I add Codeplay to the site, sponsor or partner?

**Comment by autumnfound** [comment]
Zahra sent me a question for clarification on this:

> Hi Martin, not sure how to respond to the bug, but Codeplay Software is a Silver member

apologies, I misspoke as its partners and members. We stopped using sponsors a while back and it's just sticking like gum under a desk in my brain, whoops! I'll add as a member then, thanks Zahra!
