### ISSUE TITLE
Please add OpenHW TV Episode 4 to the OpenHW Group website

### ISSUE THREAD

**Issue by AndreaFionda** [openhwgroup/openhwgroup.org#223]
Please can you add the next episode to [https://www.openhwgroup.org/resources/openhwtv/] as follows:

OpenHW TV S01E04
CORE-V MCU SoC in GF 22FDX
Sept 24, 2020

[https://www.youtube.com/watch?v=GOEvs7YFTzE]

Episode 4 discusses the OpenHW Group philosophy of learn, adopt, produce: learning about what is available in open-source ecoysystems, adopting and gaining experience on using these building blocks and deploying commercial grade open-source elements in production releases of designs. The episode includes updates from the OpenHW Group HW Task Group discussing the CORE-V MCU SoC project and features speakers from QuickLogic giving an overview of the ETH Zurich "Arnold" test chip and the path to production for the CORE-V MCU SoC, as well as Global Foundries talking about the features and benefits of 22FDX. You will also hear from the ARC Investment VC fund with insights into why there is early investment in open-source activity and as always, the popular Q&A at the end with the panel.

Please also add the Youku link:

View on Youku.com [https://v.youku.com/v_show/id_XNDg4NzE0Mjc4OA==.html?spm=a2h1n.8251843.playList.5!4~5~A&f=52505486&o=1]

As we add more episodes to this page, is there any way we can improve the layout so the thumbnails are smaller and go across the page?

Thanks

Andrea

**Comment by autumnfound** [comment]
In what way do you mean by go across the page? We can make tweaks for sure, but we should be careful with it given how long the descriptions are. With lengthy descriptions, narrowing the columns so we can show more thumbnails will make the long descriptions even longer on the page.

**Comment by AndreaFionda** [comment]
Yes OK, let's leave it for now then and just post the latest episode. I will have a think about the descriptions and how we might do it. Thank you.
