### ISSUE TITLE
Add Alean-Tec's logo on OpenHW Group website 

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#228]
Alean-Tec is a Member. Please add attached their 
[aLean-Tec_logo-tagline.zip](https://github.com/openhwgroup/openhwgroup.org/files/5348236/aLean-Tec_logo-tagline.zip)
logo on the OpenHW Group website

URL

**Comment by flora8984461** [comment]
Hello, @ZahraFazli 

just hope to make sure if the site is https://www.alien-tec.com/ ?

**Comment by ZahraFazli** [comment]
Hello Yi, 
I do not believe thats the website. My search doesn't tell me that they have an active profile. Their LinkedIn doesn't suggest an active website either.

**Comment by flora8984461** [comment]
> Hello Yi,
> I do not believe thats the website. My search doesn't tell me that they have an active profile. Their LinkedIn doesn't suggest an active website either.

Thanks. for now I will not put any url. Sorry I searched wrong link

**Comment by flora8984461** [comment]
Please check the preview: https://deploy-preview-229--eclipsefdn-openhwgroup.netlify.app

Thanks!

**Comment by ZahraFazli** [comment]
Looks good. Just wanna confirm if we want to in alphabetical order

**Comment by flora8984461** [comment]
> Looks good. Just wanna confirm if we want to in alphabetical order

@ZahraFazli  Just updated as alpha order. Thanks for reminding!

**Comment by rickoco** [comment]
Please add the URL https://alean-tec.com/
