### ISSUE TITLE
Please add Aldec Inc's logo on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#230]
Please add attached Aldec's logo on the OpenHW Group website. Aldec is a Silver Member.
Thanks,
Zahra
![Corporate_Logo_Aldec_Crescent](https://user-images.githubusercontent.com/50374570/95893943-6521e200-0d56-11eb-848f-98811b473580.png)

Website URL: https://www.aldec.com/en

**Comment by rickoco** [comment]
@chrisguindon @autumnfound - just checking in as this request is now a week old and the member is asking why they’re are not shown on our site yet.  Pls help...

**Comment by chrisguindon** [comment]
Thanks for the ping @rickoco! 

@flora8984461 Can you take a look at this today?

**Comment by flora8984461** [comment]
The logo is updated on the preview and I have created PR. Please take a preview here: https://deploy-preview-233--eclipsefdn-openhwgroup.netlify.app/

Thanks!
