### ISSUE TITLE
Please add CircuitSutra Technologies' logo on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#232]
Please add CircuitSutra Technologies' logo on the OpenHW Group website under Members.

URL: https://www.circuitsutra.com/
[logo.zip](https://github.com/openhwgroup/openhwgroup.org/files/5410466/logo.zip)

**Comment by flora8984461** [comment]
The logo is updated on the preview and I have created PR. Please take a preview here: https://deploy-preview-233--eclipsefdn-openhwgroup.netlify.app/

Thanks!
