### ISSUE TITLE
Update Working Group page

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#234]
https://www.openhwgroup.org/working-groups/

please add Tim Saxe of QuickLogic Corporation as the Vice-Chair of the HW Task Group  (currently says Open)
![image](https://user-images.githubusercontent.com/8946246/96801310-24f8da00-13bc-11eb-97f2-4a00deb89f38.png)

Here is his linked in profile
https://www.linkedin.com/in/tim-saxe-aa281a4/

**Comment by flora8984461** [comment]
Hello, 
the change has been updated.  Please preview here: https://deploy-preview-235--eclipsefdn-openhwgroup.netlify.app/working-groups/

Thanks!
Yi

**Comment by DBees** [comment]
Looks great, Yi, thank you very much!
Duncan
