### ISSUE TITLE
Please add OpenHW TV episode 5 on-demand to the OpenHW Group website

### ISSUE THREAD

**Issue by AndreaFionda** [openhwgroup/openhwgroup.org#237]
Please can you add the following episode of OpenHW TV to this page on OpenHW TV:

[https://www.openhwgroup.org/resources/openhwtv/]

OpenHW TV S01 E05
October 29 2020

Link to the file for upload is here: [https://www.youtube.com/watch?v=B5CPAztbj5g]

Back in June, the first episode of OpenHW TV looked at the CORE-V Verification Test Bench and our open-source RISC-V processor IP design verification plan. Just 4 months on and OpenHW Group is approaching the Functional RTL Freeze milestone for the CVE4. This episode looks at what the Functional RTL Freeze milestone means and how learnings from our early verification efforts have shaped our test bench progress, highlighting bugs and coverage gaps to help us deliver commercial grade, industrial quality verification work. Presenters include the Verification Task Group leadership team as well as key members of the OpenHW Group ecosystem who have collaborated to build our industry quality, coverage driven CORE-V Verification Test Bench.

View on Youku [https://player.youku.com/embed/XNDkzODg0MzI1Mg==]

**Comment by rickoco** [comment]
@AndreaFionda - don’t we want the YouTube link instead of the Wistia site?

**Comment by AndreaFionda** [comment]
> @AndreaFionda - don’t we want the YouTube link instead of the Wistia site?

Yes - thanks for pointing out!

**Comment by flora8984461** [comment]
Hi @AndreaFionda ,
Please check the preview: https://deploy-preview-238--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/
I think the youtube link should be this: 
https://v.youku.com/v_show/id_XNDkzODg0MzI1Mg==.html?spm=a2hbt.13141534.1_2.d_1_6&f=52505486

Thanks!

**Comment by AndreaFionda** [comment]
> Hi @AndreaFionda ,
> Please check the preview: https://deploy-preview-238--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/
> I think the youtube link should be this:
> https://v.youku.com/v_show/id_XNDkzODg0MzI1Mg==.html?spm=a2hbt.13141534.1_2.d_1_6&f=52505486
> 
> Thanks!

Hi @flora8984461 - thanks for this, the preview looks good. Yes, that is the correct Youku link (not YouTube)
