### ISSUE TITLE
Add PlatformIO Labs as a member on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#239]
Hello, 
Please add PlatformIO Labs's logo on the OpenHW Group website under Members
[platformio-labs-logo-horizontal.png.zip](https://github.com/openhwgroup/openhwgroup.org/files/5516866/platformio-labs-logo-horizontal.png.zip)

URL: https://piolabs.com/

**Comment by rickoco** [comment]
@chrisguindon @autumnfound - Chris, Martin any progress here?  We’ve had issues open for a few days now...
