### ISSUE TITLE
Change co-chair name on Marketing Working Group

### ISSUE THREAD

**Issue by kevin-mcdermott** [openhwgroup/openhwgroup.org#240]
The one of the marketing working group co-chairs has changed, can you please remove Hansheng (Hans) Tan and also change the LinkedIn reference text and link

This is the page on OpenHW website
https://www.openhwgroup.org/working-groups/

Remove 
Hansheng (Hans) Tan
Co-chair
Futurewei Technologies, Inc.

And replace with 
Kevin McDermott
Co-chair
Imperas Software Ltd.

LinkedIn
Follow Kevin McDermott on LinkedIn
https://www.linkedin.com/in/kevin-mcdermott-7b3139/

**Comment by autumnfound** [comment]
@rickoco can we get a +/- 1 on this change before we action it? Thanks!

**Comment by rickoco** [comment]
👍
