### ISSUE TITLE
Please add this news story to OpenHW Group website

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#246]
Hi, I've replaced Andrea at Publitek. Please can you make this update to the website..

On this webpage:
https://www.openhwgroup.org/resources/openhwtv/

OpenHW TV S01 E06
Deep Dive into Formal Verification for the CORE-V CVE4
Nov 20, 2020

OpenHWTV-S1E6

Our last webinar episode of 2020 is now available to watch on-demand. Last month we looked at our progress on the RTL functional freeze milestone for the CVE4 and how we arrived there with the high quality verification work from our members. We had a lot of questions around the Formal Verification work carried out to get us this far, so we have dedicated this episode to a deep-dive into the Formal Verification work and to hear from our partners on what it actually means. As always, the panel session will be live for a Q&A with all our speakers.

View on YouTube: https://youtu.be/UfZ3jbH6eM0
View on youku.com: https://player.youku.com/embed/XNDk3Mjk4MzIyMA==
 
<img width="1278" alt="OpenHWTV-S1E6" src="https://user-images.githubusercontent.com/74318457/99811026-7d96d080-2b3c-11eb-8d68-0aebc7e3a452.png">

**Comment by chrisguindon** [comment]
This was done via #247

**Comment by chrisguindon** [comment]
@NaylDSouza please note that you can submit news stories via https://newsroom.eclipse.org/node/add/news

Please le me know if you have any questions!
