### ISSUE TITLE
Please post this news story on the OpenHW 

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/openhwgroup.org#247]
On this webpage:
https://www.openhwgroup.org/resources/openhwtv/

OpenHW TV S01 E06
Deep Dive into Formal Verification for the CORE-V CVE4
Nov 20, 2020

OpenHWTV-S1E6

Our last webinar episode of 2020 is now available to watch on-demand. Last month we looked at our progress on the RTL functional freeze milestone for the CVE4 and how we arrived there with the high-quality verification work from our members. We had a lot of questions about the Formal Verification work carried out to get us this far, so we have dedicated this episode to a deep-dive into the Formal Verification work and to hear from our partners on what it actually means. As always, the panel session will be live for a Q&A with all our speakers.

View on YouTube: https://youtu.be/UfZ3jbH6eM0
View on youku.com: https://player.youku.com/embed/XNDk3Mjk4MzIyMA==

@flora8984461 Once this page is live, please submit a news item so that we can promote this on the openhwgroup homepage: http://newsroom.eclipse.org/node/add/news

**Comment by flora8984461** [comment]
@chrisguindon The youtube is private, can it be accessible? https://www.youtube.com/watch?v=UfZ3jbH6eM0&feature=youtu.be

**Comment by chrisguindon** [comment]
@flora8984461 Thanks - I will send a note about this.

**Comment by shangyunhai** [comment]
The new link of Youku: https://v.youku.com/v_show/id_XNDk3Mjk4MzIyMA==.html?spm=a2h1n.8251843.playList.5!6~5~A&f=52505486&o=1

**Comment by rickoco** [comment]
@chrisguindon - this should not be closed yet and the post for E06 is not up on the OpenHW TV page https://www.openhwgroup.org/resources/openhwtv/

**Comment by chrisguindon** [comment]
Issues are automated closed when we merge a PR.

I explained the delay in regards to deploument in my email this morning.

**Comment by chrisguindon** [comment]
The video is on the website: https://www.openhwgroup.org/resources/openhwtv/
