### ISSUE TITLE
Host production website with Netlify

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/openhwgroup.org#249]
As many of you might already know, we are currently leveraging Github pages in order to host the openhwgroup.org and osdforums.org website:
https://github.com/openhwgroup/openhwgroup.org/blob/master/.travis.yml

## Problem

I have been noticing delays/errors when deploying updates to the oenhwgroup.org website. Builds are timing out even worst, not starting which is delaying updates from making their way on to prod.

To address this. I am manually triggering rebuilds in order to publish changes to the website.

I believe this issue is related to the Backlog of Linux builds for Open source projects on travis-ci.org which seems to be increasing:

<img width="900" alt="Screen Shot 2020-10-23 at 8 06 34 AM" src="https://user-images.githubusercontent.com/893942/97001701-d015aa80-1506-11eb-894f-833fb1ca1b63.png">

## Solution

I am proposing that we migrate hosting providers from Github pages to Netlify. 

We have been using Netlify for its PR preview feature for more than a year now and it's proven to more reliable than travis-ci. It also makes sense for us to use the same automation server for production and staging.

In order to make the switch, we will need to point the openhwgroup.org/osdforum.org domain to Netlify servers instead of Github. We will also need to make some tweaks to our configs:

- We would need to remove the "disallow_robots_txt" script: https://github.com/openhwgroup/openhwgroup.org/blob/master/package.json#L20
- Remove the deploy/env section from https://github.com/openhwgroup/openhwgroup.org/blob/master/.travis.yml

This change should also improve security for the site since this will allow us to remove the encrypted access token from our travis-ci file: https://github.com/openhwgroup/openhwgroup.org/blob/master/.travis.yml

Please let me know if you have any concerns about this proposal. I am currently scheduling this work to be done on December 2 at 1 pm EST in order to address the build time issue.

Please note that the migration will require about 30 minutes of downtime in order for Netlify to generate a valid SSL cert.

//cc @rickoco @DBees

**Comment by rickoco** [comment]
no problem here @chrisguindon

**Comment by chrisguindon** [comment]
Migration is now complete!
