### ISSUE TITLE
Post news article:

### ISSUE THREAD

**Issue by jph152** [openhwgroup/openhwgroup.org#250]
A request from Nayl D'Souza, who handles marketing for OpenHW, who would like this article to be hosted on the OpenHW website. https://www.openhwgroup.org/news/

I will add it to the website's news feed afterwards.

Thanks!

//headline//
CORE-V CVE4 RTL Freeze Milestone Achieved 

//sub-headline//
Major industry 'first' for an open-source ecosystem

//main body copy//
The OpenHW CV32E40P RISC-V core is the first open-source core for high-volume chips verified with the state-of-the-art process required for high-integrity, commercial SoCs.  

The RTL Freeze milestone was achieved with OpenHW ecosystem contributors working collaboratively using CORE-V-VERIF, an OpenHW Group project to develop, deploy, and execute pre-silicon functional verification of the OpenHW Group's CORE-V family of RISC-V cores. The CVE4, which is part of the CORE-V open-source IP family, matches the quality of IP offered by established commercial providers and is verified with state-of-the-art, auditable flows.

CORE-V-VERIF provides a silicon-proven, industrial-grade functional verification platform to the RISC-V community. CORE-V-VERIF leverage verification components developed by the RISC-V community and will be continuously maintained and enhanced to integrate the latest best-practices and technology for the verification of future CORE-V cores.

CORE-V-VERIF includes verification strategy and planning documents, and SystemVerilog/UVM code implementing an end-to-end simulation environment. Additionally, the platform supports an advanced SVA formal verification environment, which leverages the RISC-V ISA specification in SAIL and provides optimal integration with simulation. The platform supports the use of structural, functional, and mutation coverage metrics and CORE-V-VERIF leverages both open-source and commercial IPs and EDA technology.

The CORE-V-VERIF project is hosted in the OpenHW Group GitHub repositories and is available to the community under the Solderpad 2.0 license.

Thanks to all of those community members involved in this landmark project.

HEADER IMAGE:
<img width="904" alt="OpenHW-CORE-V" src="https://user-images.githubusercontent.com/69642121/101777643-ca792180-3ac0-11eb-81a6-a5b8d43fa5cd.png">

**Comment by rickoco** [comment]
Yes @jph152 - pls post the article.  Also in the 2nd last sentence, pls link to our GitHub repo for this project as follows...

The [CORE-V-VERIF project is hosted in the OpenHW Group GitHub repositories](https://github.com/openhwgroup/core-v-verif) and is available to the community under the Solderpad 2.0 license.

**Comment by flora8984461** [comment]
Hello @jph152 ,

I'm not sure should we use this header image, it would be like this: 🤔

![image](https://user-images.githubusercontent.com/39588094/101832223-0e8e1580-3b05-11eb-8f33-244a339f9b0f.png)

Thanks!

**Comment by chrisguindon** [comment]
@jph152 I agree with Yi. We would need to change the styles of the header or changes to these images so that our users can read the white text...

@meKokabi can you help us here?

**Comment by chrisguindon** [comment]
@jph152 is it an option for us to publish the article without this header? We could add it later once it's ready...?

**Comment by rickoco** [comment]
feel free to embed the image (reduced in size) in line with the text.

**Comment by rickoco** [comment]
Or you can simply embed the attached CORE-V logo
![CORE-V-portrait](https://user-images.githubusercontent.com/2498391/101835349-a5f56780-3b09-11eb-83c4-77198f2f351d.png)

**Comment by jph152** [comment]
> @jph152 is it an option for us to publish the article without this header? We could add it later once it's ready...?

Yes, please go ahead and publish! The image could go in between the headline and body text.

**Comment by flora8984461** [comment]
Hi @chrisguindon @rickoco @jph152 

How about this preview?
https://deploy-preview-251--eclipsefdn-openhwgroup.netlify.app/news/2020/12/10/core-v-cve4-rtl-freeze-milestone-achieved/

Thanks!

**Comment by meKokabi** [comment]
@chrisguindon Absolutely! I would be happy to help!

**Comment by meKokabi** [comment]
<img width="830" alt="Screen Shot 2020-12-10 at 5 38 01 PM" src="https://user-images.githubusercontent.com/75500459/101838389-801e9180-3b0e-11eb-9711-d0c00d081ed9.png">
@chrisguindon You may want to use this as BkG image

**Comment by jph152** [comment]
@flora8984461 Looks good, but I think a smaller version of the image would be best

**Comment by flora8984461** [comment]
@meKokabi @jph152 
I used the updated header image as bg and used smaller original image as embeded in the article for you to have a comparison which one you want to use. And I will remove the other one.

https://deploy-preview-251--eclipsefdn-openhwgroup.netlify.app/news/2020/12/10/core-v-cve4-rtl-freeze-milestone-achieved/

Thanks!

**Comment by jph152** [comment]
@flora8984461 I think we should use the header image (provided by @meKokabi) if there are no objections

**Comment by chrisguindon** [comment]
> I used the updated header image as bg and used smaller original image as embeded in the article for you to have a comparison which one you want to use. And I will remove the other one.
> 
> https://deploy-preview-251--eclipsefdn-openhwgroup.netlify.app/news/2020/12/10/core-v-cve4-rtl-freeze-milestone-achieved/

@rickoco Are you good with removing the image from the text and keeping the header that @meKokabi created?

**Comment by flora8984461** [comment]
@jph152 If you are good with the current version: https://deploy-preview-251--eclipsefdn-openhwgroup.netlify.app/news/2020/12/10/core-v-cve4-rtl-freeze-milestone-achieved/ , we can go live with this once we have +1 from you.

Thanks!

**Comment by jph152** [comment]
Yes, let's go live with this @flora8984461
