### ISSUE TITLE
Add Intrinsix Corp as Member on the OpenHW Group

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#258]
Please add Intrinsix Corp as OpenHW Group Member on the website https://www.openhwgroup.org/
[intrinsix-logo-2016-eps.zip](https://github.com/openhwgroup/openhwgroup.org/files/5850292/intrinsix-logo-2016-eps.zip)

**Comment by flora8984461** [comment]
Hi @ZahraFazli , I assume the website is https://www.intrinsix.com/ ?

Thanks!

**Comment by ZahraFazli** [comment]
Yes, confirmed. Thanks
