### ISSUE TITLE
Update Link to the Member Committer and Contributor Agreement 

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#260]
Hello, 
The link to the Eclipse Foundation Member Committer and Contributor Agreement needs to be updated to point to the AISBL MCCA and align with the eclipse.org "Become A Member" Page. 
Below is the link to the updated MCCA
https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf
Thanks,
Zahra

**Comment by flora8984461** [comment]
Hi @ZahraFazli , where is the link to MCCA on OpenHW site?

**Comment by ZahraFazli** [comment]
https://www.openhwgroup.org/membership/

**Comment by flora8984461** [comment]
@ZahraFazli Thanks! the site is updated, please check https://www.openhwgroup.org/membership/contact/

**Comment by ZahraFazli** [comment]
LGTM, Thank you!
