### ISSUE TITLE
Add CSEM SA as Member

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#261]
Hello, 
Please add CSEM SA's logo on the OpenHW Group website as Member https://www.openhwgroup.org/
[csem-logo-cmyk.zip](https://github.com/openhwgroup/openhwgroup.org/files/5888163/csem-logo-cmyk.zip)

**Comment by flora8984461** [comment]
Hi @ZahraFazli  Can I confirm with you the company url is https://www.csem.ch/Home? Thanks!

**Comment by ZahraFazli** [comment]
Hi, yes, I can confirm. thanks
