### ISSUE TITLE
Please add content to OpenHW website

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#262]
We would like the following news item hosted on the OpenHW site. As usual, this needs to be on a page on OpenHW website. https://www.openhwgroup.org/resources/openhwtv/
Note there will be a youku.com link to follow but let's please not wait for this before publishing.
I will send that as an update later. Thanks.
Here is the content:

**Date** 
Thursday, 28 January, 2021

**Title:** 
OpenHW TV Episode 1 of Season 2 now available to view

**Body:**
2021. New year, new episode of OpenHW TV. In the first episode of Season Two, we feature an interview between embedded.com editor-in-chief Nitin Dahad and OpenHW Group President and CEO Rick O'Connor. They discuss the latest milestones of the OpenHW Group, the roadmap for the organization, as well as the key issues that are driving the growth of open-source processor design and development. Plus there's a brief bonus round-up of season one showing the interesting range of guidance and discussion that was presented last year.
You can access the entire recording here: https://youtu.be/LZ8N3uLD4wY

<img width="853" alt="OpenHWTV-S2E1-visual" src="https://user-images.githubusercontent.com/74318457/106202506-f3a95a80-61b1-11eb-90fd-6eb64ef643cd.png">

**Comment by flora8984461** [comment]
@NaylDSouza Hi, Please check the preview: https://deploy-preview-264--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

Thanks!

**Comment by NaylDSouza** [comment]
@flora8984461 Thanks Flora. 
Looks good, like how you've archived Season One.
Let's please change "OpenHW TV Episode 1 of Season 2 now available to view" sub-headline to "embedded.com CEO interview and Season One round-up"

**Comment by flora8984461** [comment]
@NaylDSouza Thanks you like it. It's actually other's work who build the shortcode automatically does the archives. 

So the updated preview now is: https://deploy-preview-264--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by NaylDSouza** [comment]
Great just two more small changes Flora.

2021.New year, new episode of OpenHW TV.  (there should be a space needed between "2021." and "New year")

So this needs to be:

2021. New year, new episode of OpenHW TV.

Also in the body copy:

Plus there’s a brief bonus round-up of season one showing the interesting range of guidance and discussion that was presented last year.

Should be:

Plus there’s a brief bonus round-up of Season One showing the interesting range of guidance and discussion that was presented last year.

**Comment by flora8984461** [comment]
@NaylDSouza Thanks for the catch. I just updated the preview: https://deploy-preview-264--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by chrisguindon** [comment]
@flora8984461 @autumnfound,

please see https://github.com/openhwgroup/openhwgroup.org/pull/264#issuecomment-769977476

**Comment by autumnfound** [comment]
Please see https://github.com/openhwgroup/openhwgroup.org/pull/267#issuecomment-769983717. There is an issue when viewing the site, and we're not sure if this is intentional. We've tagged @NaylDSouza for clarification, but figured it may take some time for feedback as it was posted late Friday

**Comment by chrisguindon** [comment]
Done!
