### ISSUE TITLE
Add Technion as Member on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#268]
Please add Technion as Member on the OpenHW Group as Member https://www.openhwgroup.org/
![TechnionIIT English 3-lines](https://user-images.githubusercontent.com/50374570/106634568-e42d6700-654d-11eb-9cfd-a3bc1df911d7.png)

**Comment by flora8984461** [comment]
Hi @ZahraFazli Just hope to confirm is https://www.technion.ac.il/en/technion-israel-institute-of-technology/ the correct link?
