### ISSUE TITLE
Add CEA List as Member on OpenHW Group

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#272]
Please add CEA List as Member on the OpenHW Group website  https://www.openhwgroup.org/
[search.zip](https://github.com/openhwgroup/openhwgroup.org/files/5945755/search.zip)

**Comment by flora8984461** [comment]
Hi @ZahraFazli The search.zip you uploaded contains only a html page with a lot of logos. Can you provide one that is expected? Thanks! 

The screenshot shows what is in the search zip:

![image](https://user-images.githubusercontent.com/39588094/107390395-a8524e80-6ac5-11eb-9aca-db6cf6608b8e.png)

**Comment by ZahraFazli** [comment]
Hello Yi, 
I have added the correct one.
thanks,
Zahra
![download](https://user-images.githubusercontent.com/50374570/107423152-04c76500-6aea-11eb-955b-a9a6f1d45964.png)

**Comment by flora8984461** [comment]
> Hello Yi,
> I have added the correct one.
> thanks,
> Zahra
> ![download](https://user-images.githubusercontent.com/50374570/107423152-04c76500-6aea-11eb-955b-a9a6f1d45964.png)

Thanks. Just hope to confirm the website, is it: http://www-list.cea.fr/en/?

**Comment by ZahraFazli** [comment]
The website is correct. 
Thanks
