### ISSUE TITLE
OpenHW TV S2 E02: What do you gain from the OpenHW ecosystem?

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#273]
//Please add this news story asap//

![OHW_TV_S2E2_BANNER__WITH_REG](https://user-images.githubusercontent.com/74318457/107292857-6d6aff00-6a62-11eb-9546-0f32bddd01df.png

//Please link the picture above the text to this registration link://
https://us02web.zoom.us/webinar/register/3916125564509/WN_B3csDDiRSgejGAvgqJyc6g

The fast-growing, open-source OpenHW ecosystem will be explored in our next episode of OpenHW TV. OpenHW Group is at the heart of a mainstream shift to open-source processors, bringing many benefits to silicon manufacturers and technology partners. In this episode OpenHW IP adopters will highlight key drivers for their engagement in the OpenHW community.

Rick O'Connor (President and CEO) and Duncan Bees (Director, Technical Programs) from OpenHW Group are joined by:
- Sebastian Ahmed, Senior Director of R&D, Silicon Labs
- Rob Oshana, VP Software Engineering for R&D, NXP
- Tim Saxe, CTO, QuickLogic
- Bertand Tavenier, VP Software, Thales
- John Martin, Senior Design Engineer, EM Microelectronic

After a series of 5 minute presentations, there is a live Q&A roundtable session as usual.

[Register here](https://us02web.zoom.us/webinar/register/1016125564767/WN_B3csDDiRSgejGAvgqJyc6g)

**Comment by flora8984461** [comment]
Hi @NaylDSouza The preview for the page would be: https://deploy-preview-274--eclipsefdn-openhwgroup.netlify.app/news/2021/02/09/openhw-tv-s2-e02-what-do-you-gain-from-the-openhw-ecosystem/

And once we got +1 from you, we will merge to live and add the same news to the newsroom.

Thanks!

**Comment by NaylDSouza** [comment]
Please go ahead. All good from me.

**Comment by flora8984461** [comment]
@NaylDSouza 
Please check the two new news here:
https://www.openhwgroup.org/news/

thanks!

**Comment by NaylDSouza** [comment]
Sorry, urgent mistakes in the news stories @flora8984461 and @chrisguindon - please can you help.
I need to replace the banner on the webinar page with this:

![OHW_TV_S2E2_BANNER__WITHOUT_REG](https://user-images.githubusercontent.com/74318457/107404874-9c36b300-6afe-11eb-9759-658dca0ab546.png)

And I've spelt Bertrand Tavernier wrong. There is a typo in Bertrand.

Thanks
Nayl

**Comment by flora8984461** [comment]
Hi @NaylDSouza 
Please check the new preview:  https://deploy-preview-276--eclipsefdn-openhwgroup.netlify.app/news/2021/02/09/openhw-tv-s2-e02-what-do-you-gain-from-the-openhw-ecosystem/

We will merge it once got +1 from you. Thanks!

**Comment by NaylDSouza** [comment]
Hi @flora8984461 - that's great - you're a star. Thank you. Please proceed with merging and going live with the changes.

**Comment by flora8984461** [comment]
Hi @NaylDSouza , my team just helped me merge it. Please check the updated page https://www.openhwgroup.org/news/2021/02/09/openhw-tv-s2-e02-what-do-you-gain-from-the-openhw-ecosystem/

**Comment by NaylDSouza** [comment]
OK @flora8984461 – Permission to shoot me. We made a double typo with Bertrand's name. His surname was spelt wrong too. It is Tavernier (not Tavenier). I've told Bertrand that this will be changed within 24 - 48 hrs.

**Comment by flora8984461** [comment]
Hi @NaylDSouza  Is not the current site is already `Bertrand Tavernier`? Btw, I just noticed I also need to update https://newsroom.eclipse.org/news/announcements/openhw-tv-s2-e02-what-do-you-gain-openhw-ecosystem.

**Comment by NaylDSouza** [comment]
@flora8984461 Glad you're paying attention. Yes, you caught the typos already. Thank you.
