### ISSUE TITLE
Episode Two of OpenHW TV (Season 2) available to watch

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#279]
//News story for home page of OpenHWGroup.org website//

**Episode Two of OpenHW TV (Season 2) available to watch**
The fast-growing, open source OpenHW ecosystem is the focus of this episode of OpenHW TV. OpenHW IP adopters highlight the key drivers for their engagement in the OpenHW community. The episode also contains an extended Q&A session addressing questions such as what the sweet spot is for RISC-V cores such as CORE-V, and which RISC-V ISA extensions are most important. Watch the video of the webinar broadcast on 18 February now.

//Please link to https://youtu.be/rBMOfFKgxso//

**Comment by flora8984461** [comment]
This is live on https://www.openhwgroup.org/news/

I'm going to close this bug, please feel free to reopen it if more changes needed. Thanks!
