### ISSUE TITLE
Please add episode to https://www.openhwgroup.org/resources/openhwtv/

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#280]
Please add episode to https://www.openhwgroup.org/resources/openhwtv/

**OpenHW TV S02 E02**
What do you gain from the OpenHW ecosystem?
Feb 18, 2021

The fast-growing, open source OpenHW ecosystem is the focus of this episode of OpenHW TV. OpenHW IP adopters highlight the key drivers for their engagement in the OpenHW community. The episode also contains an extended Q&A session addressing questions such as what the sweet spot is for RISC-V cores such as CORE-V, and which RISC-V ISA extensions are most important. Watch the video of the webinar broadcast on 18 February now.

//Please embed video to link to https://youtu.be/rBMOfFKgxso//

**Comment by flora8984461** [comment]
Hi @NaylDSouza 
Please check the preview: https://deploy-preview-281--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

Do you want to provide Youku link? 

Thanks!

**Comment by NaylDSouza** [comment]
@flora8984461  I've requested this but haven't received it yet. Please go live and we'll do that addition later. Thanks.
