### ISSUE TITLE
please update CEA logo on member site

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#282]
**Describe the bug**
CEA logo is the wrong one, please update. Thanks!

[logo-CEA-version-couleurs.zip](https://github.com/openhwgroup/openhwgroup.org/files/6026021/logo-CEA-version-couleurs.zip)

**Comment by flora8984461** [comment]
Hi @DBees Please check the preview: https://deploy-preview-284--eclipsefdn-openhwgroup.netlify.app/

Thanks!

**Comment by DBees** [comment]
Thanks Yi looks good!
