### ISSUE TITLE
Add YosysHQ to the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#283]
Please add YosysHQ as member on OpenHW Group website
![YOS_horiz](https://user-images.githubusercontent.com/50374570/108900849-21829300-75e8-11eb-9b0f-e27c32b14b99.png)

**Comment by ZahraFazli** [comment]
Website: https://www.yosyshq.com/

**Comment by flora8984461** [comment]
Hi @ZahraFazli  Please check the preview: https://deploy-preview-284--eclipsefdn-openhwgroup.netlify.app/

Thanks!
