### ISSUE TITLE
OpenHW Group at the virtual embedded world, March 1 – 5 2021 (Germany)

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#285]
//Please add news story to OpenHW website//

OpenHW Group is participating at the virtual embedded world, March 1 – 5 2021 (Germany)

Wednesday Mar 3, 18:40 CET - 18:50 CET
CORE-V: Industrial Grade, Open Source RISC-V Cores
Exhibitor's Forum 1
Speaker: Rick O'Connor, OpenHW Group

Thursday Mar 4, 2021, 11:00 - 11:30 CET  
RISC-V with OpenHW Roundtable ⁠
Roundtable with OpenHW Group

Friday Mar 5, 2021, 11:30 - 12:00 CET 
Session on System-on-Chip: Core Integration & Tools
Leveraging RISC-V Technology for Industry Use
Speakers: Robert Oshana, Vice President, NXP
& Rick O'Connor, OpenHW Group.

Friday Mar 5, 2021, 12:30 - 12:45 CET 
Session on System-on-Chip: Core Integration & Tools
Discussion/Q&A
Farhad Mafie with Rob Oshana & Rick O'Connor

Friday Mar 5, 2021, 14:20 - 14:40 CET 
Exhibitor Forum 2
CORE-V: Industrial Grade, Open-Source RISC-V Cores

The CORE-V family is an OpenHW Group project to develop, deploy, execute pre-silicon functional verification and SoC based evaluation kits of the CORE-V family of open-source RISC-V cores. Written in SystemVerilog, the CORE-V open-source IP matches the quality of IP offered by established commercial providers and is verified with state-of-the-art, auditable flows. With Rick O'Connor, OpenHW Group.

Registration for Embedded World:
https://www.messe-ticket.de/Nuernberg/embeddedworld2021/

For more information, visit the event website
https://www.embedded-world.de/en/programme

**Comment by flora8984461** [comment]
Hi @NaylDSouza 
I made a preview: https://deploy-preview-288--eclipsefdn-openhwgroup.netlify.app/news/2021/02/26/openhw-group-is-participating-at-the-virtual-embedded-world-march-1-5-2021-germany/

I wonder if you would like some styling or just this is good? 

Thanks!

**Comment by NaylDSouza** [comment]
Hi @flora8984461 - please can we add the dates in bold and the same font size as the other body text, rather than very big and green.

Also, please can you add a new event entry at the top of that list of events - you'll see this happens on Wednesday.

Many thanks, Nayl

**Comment by flora8984461** [comment]
@NaylDSouza Thanks for your feedback!

I just updated the style and content, please check the preview: https://deploy-preview-288--eclipsefdn-openhwgroup.netlify.app/news/2021/02/26/openhw-group-is-participating-at-the-virtual-embedded-world-march-1-5-2021-germany/

Thanks!

**Comment by NaylDSouza** [comment]
Sorry @flora8984461 Flora please can you change the time of that first event to:
**17:40 - 17:50 CET** 

(changing the time and removing a CET reference after the first time)

Then all good and please post. No need to wait for my go ahead.

**Comment by flora8984461** [comment]
@NaylDSouza  Sounds good, I also added a `2021` to keep consistency with others.

**Comment by flora8984461** [comment]
Hi @NaylDSouza The new is live, please check: https://www.openhwgroup.org/news/2021/02/26/openhw-group-is-participating-at-the-virtual-embedded-world-march-1-5-2021-germany/

Thanks!

**Comment by NaylDSouza** [comment]
Thanks @flora8984461 
Can this also show on https://www.openhwgroup.org/news/

**Comment by flora8984461** [comment]
Sure! 

Btw, https://newsroom.eclipse.org/news form is available to everyone in our community, you can always promote any news by submitting it. 

I have created one for you, https://newsroom.eclipse.org/news/announcements/openhw-group-participating-virtual-embedded-world-march-1-%E2%80%93-5-2021-germany You can view and edit it if you log in. 

Thanks!

**Comment by NaylDSouza** [comment]
Ah Flo, it may be showing on Eclipse news site but not the OpenHW home page. Please can it show there too? Thanks.

https://www.openhwgroup.org/news/
![Screenshot 2021-03-02 at 15 29 27](https://user-images.githubusercontent.com/74318457/109671765-476de180-7b6c-11eb-9133-41a130c2d29b.png)

**Comment by flora8984461** [comment]
@NaylDSouza Hi, it is showing https://www.openhwgroup.org/news/ . The data is retrieved from https://newsroom.eclipse.org/news . Once after creation, it might take a few minutes to sync the data.

Thanks!

**Comment by NaylDSouza** [comment]
Thanks @flora8984461 Now showing! That's great.

On the events section of the home page, please can we also make one small addition:

OpenHW Day 
(during RISC-V Week 2021)
Thursday April 1, 2021 
https://open-src-soc.org/

**Comment by chrisguindon** [comment]
@NaylDSouza,

As mentioned on the Eclipse Newsroom website, please email news@eclipse.org to request edits.
