### ISSUE TITLE
OpenHW Day

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#286]
//Please add to the events listing on home page of OpenHW Group//

**OpenHW Day** 
Thursday April 1, 2021
https://open-src-soc.org/

**Comment by flora8984461** [comment]
Hi @NaylDSouza @chrisguindon 
to create an event, I will submit in the newsroom, https://newsroom.eclipse.org/node/add/events

I am not sure about some of the fields, what are the event type and attendance type? 
![image](https://user-images.githubusercontent.com/39588094/109356673-08c7e680-784f-11eb-93a8-ba34db7f988f.png)

And what is the time zone? Is there any text body you want to add? (optional)
![image](https://user-images.githubusercontent.com/39588094/109356747-21d09780-784f-11eb-92c8-02d929be57d1.png)

Do I need to add location info?
![image](https://user-images.githubusercontent.com/39588094/109356996-7b38c680-784f-11eb-82e1-226012280510.png)

Thanks!

**Comment by chrisguindon** [comment]
@NaylDSouza,

Our event form is available to everyone in our community. Please submit your event to: https://newsroom.eclipse.org/node/add/events

This is the best way to promote your event!
