### ISSUE TITLE
Add NEC as Members on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#289]
Please add NEC Corporation as Member on OpenHW Group website
[NEC_Corporation_of_America-Logo.wine.zip](https://github.com/openhwgroup/openhwgroup.org/files/6078228/NEC_Corporation_of_America-Logo.wine.zip)

Website: https://www.necam.com/

**Comment by flora8984461** [comment]
Hi @ZahraFazli 
Please check the preview: https://github.com/openhwgroup/openhwgroup.org/pull/290

Thanks!

**Comment by flora8984461** [comment]
FYI: this change is merged to live. Please check openhwgroup.org,  Thanks!
