### ISSUE TITLE
Silicon Labs testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#29]
please add...

**Alessandro Piovaccari, Board Director of OpenHW Group and CTO of Silicon Labs**
“Within the next few years, most of the billions of SoCs in our smart, connected world will contain many specialized cores to address various tasks from subsystems supervision, to security and machine learning. I’m delighted to join the board of the OpenHW Group because I believe the CORE-V Family of open-source RISC-V cores will be vital in providing robust and accessible processors to address this need, which will ultimately help accelerate innovation in the IoT.”

**Comment by ericpoirier** [comment]
The Silicon Labs testimonials is now on the production website.
