### ISSUE TITLE
Add Imagination Technologies Limited to OpenHW Group Website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#293]
Please add Imagination Technologies Limited as Members to OpenHW Group Website
[Imagination_Logo_hor_Blk.zip](https://github.com/openhwgroup/openhwgroup.org/files/6117931/Imagination_Logo_hor_Blk.zip)

https://www.imaginationtech.com/

**Comment by autumnfound** [comment]
@ZahraFazli do we have another version of this logo? The provided ZIP contains an EPS file, which is a fancy font file with some graphic elements. We would need to export it to something we can use, which doesn't always work with EPS files flawlessly

**Comment by ZahraFazli** [comment]
Hi Martin, I don't unfortunately. I can reach out and ask.

**Comment by rickoco** [comment]
> Hi Martin, I don't unfortunately. I can reach out and ask.

@ZahraFazli - any progress here?

**Comment by ZahraFazli** [comment]
> > Hi Martin, I don't unfortunately. I can reach out and ask.
> 
> @ZahraFazli - any progress here?

I have reached out to John.

**Comment by ZahraFazli** [comment]
Please find png version 
![Imagination_Logo_hori_Blk](https://user-images.githubusercontent.com/50374570/112348821-922bd680-8c9e-11eb-92ce-f645e26ebc4e.png)
attached.
