### ISSUE TITLE
Add AMIQ EDA on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#298]
Please add AMIQ EDA's logo as Member on the OpenHW Group website.
![AMIQ](https://user-images.githubusercontent.com/50374570/112537593-40aa4700-8d85-11eb-9ea9-ddc323e62115.jpg)

**Comment by autumnfound** [comment]
Previews for this member can be seen on:
https://deploy-preview-299--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-299--eclipsefdn-openhwgroup.netlify.app/membership/members/

Let me know if any changes are needed!
