### ISSUE TITLE
Embecosm Testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#30]
please add...

**Ian Loveless, Commercial Director EMBECOSM**
"As a specialist in open source compiler tool chains and operating
systems, open standards are central to Embecosm's business. Our
customers, whether they use the smallest edge computing platform or the
largest of HPC systems, must have confidence in the ubiquity and
long-term stability of RISC-V cores. We see OPENHW GROUP as a crucible
of innovators, with CORE-V a set of trusted and reliable implementations
of the RISC-V open standard."

**Comment by ericpoirier** [comment]
The EMBECOSM testimonials is now on the production website.
