### ISSUE TITLE
update chairs page https://www.openhwgroup.org/working-groups/

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#304]
Under Verification Task Group
Please replace Jingliang (Leo) Wang with Robert Chu
(also of Futurewei)

Linked in profile https://www.linkedin.com/in/robertchu/

thank you
Duncan

**Comment by autumnfound** [comment]
Preview available on https://deploy-preview-307--eclipsefdn-openhwgroup.netlify.app, should be merged later today!
