### ISSUE TITLE
Add article to https://www.openhwgroup.org/news/

### ISSUE THREAD

**Issue by jph152** [openhwgroup/openhwgroup.org#305]
- **Headline**: Register for OpenHW TV S2 E04: Software Task Group Project Updates

-  **Summary**: Get the lowdown on some of the key projects spearheaded by the OpenHW Software Task Group, led by Jeremy Bennett (at Embecosm). The webinar, with a live Q&A session, is being broadcast live on Thursday, April 22 at 11am EST. 

- **Publish date:** as soon as convenient

- **Published to** https://www.openhwgroup.org/news/

- **Image**: Insert above main text body

<img width="712" alt="S2E4-OpenHW-TV-Promo" src="https://user-images.githubusercontent.com/69642121/114061026-f4bad000-9863-11eb-842f-29b8b8a74255.png">

- **Article body**

Register now for OpenHW TV's next episode:
New project updates from our Software Task Group

Get the lowdown on some of the key projects spearheaded by the OpenHW Software Task Group, led by Jeremy Bennett (at Embecosm). The webinar, with a live Q&A session, is being broadcast live on Thursday, April 22 at 11am EST. 

Any silicon chip is only as good as the software ecosystem which accompanies it. The Software Task Group's mission is to drive the creation of this ecosystem for OpenHW Group processors. The SW TG not only develops the key software elements that are needed, but it also encourages the growth of a thriving commercial community that can develop and maintain this software for the long term.

In this webinar, you will get insights about projects run by our Software Task Group including the CORE-V FreeRTOS project featuring a demo from Robert Balas (ETH Zürich) and Shteryana Shopova (Embecosm). There will also be updates about the GCC and Clang/LLVM compiler tool chains from Philipp Krones and Jessica Mills (Embecosm). And there is a presentation on IDE projects from Ivan Kravets (PlatformIO) and Alexander Fedorov (Arsysop/Eclipse).

Register here:
https://us02web.zoom.us/webinar/register/WN_noFvb6moSymqX0CP7R8gYQ

Watch trailer:
https://www.youtube.com/watch?v=HkJw8HcwBOA

**Comment by autumnfound** [comment]
Preview of article available at https://deploy-preview-307--eclipsefdn-openhwgroup.netlify.app/news/2021/04/14/register-for-openhw-tv-s2-e04-software-task-group-project-updates/

Production link (once merged) will be https://openhwgroup.org/news/2021/04/14/register-for-openhw-tv-s2-e04-software-task-group-project-updates/

**Comment by jph152** [comment]
+1 Looks good to go
