### ISSUE TITLE
Add USASK's logo on the OpenHW Group Website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#306]
Hello, 
USASk is a Supporter Member of OpenHW Group. Please add their logo as members of the OpenHW Group.
Thanks,
Zahra
![Usask logo](https://user-images.githubusercontent.com/50374570/114416480-ba607400-9b7e-11eb-9d6c-44a218c11e77.png)

**Comment by autumnfound** [comment]
Preview available on https://deploy-preview-307--eclipsefdn-openhwgroup.netlify.app, will be merged soon
