### ISSUE TITLE
DNS for custom docs domain

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/openhwgroup.org#308]
**Is your feature request related to a problem? Please describe.**
I want to set-up a custom domain (`docs.openhwgroup.org`) to our business read-the-docs account.

**Describe the solution you'd like**
This is going to be a two-step process:

1. Adding a CNAME record from `_32bd0502145c906a78d646de39f192a3.docs.openhwgroup.org` to `_verifye4089c14.domains.readthedocs.com` to verify ownership of the domain.
2. Wait for SSL certificate issuance and domain configuration (this may take a few days).
3. Add a CNAME record in your DNS pointing your custom domain `docs.openhwgroup.org` to `e4089c14.domains.readthedocs.com`

From the readthedocs side, I can handle everything. Thank you.

**Comment by rickoco** [comment]
@chrisguindon @autumnfound - Chris, Martin, can this be looked at pls?

**Comment by chrisguindon** [comment]
@zarubaf Step 1 is done!

Let me know when you need me to do step #3.

**Comment by zarubaf** [comment]
Thanks @chrisguindon, it was already picked up by RTD. We can please proceed to step 3. Thank you!

**Comment by chrisguindon** [comment]
@zarubaf Done!

Let me know if you need anything else!
