### ISSUE TITLE
Greenwaves testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#31]
please add...

**Loic Lietar, CEO GreenWaves Technologies**
"We believe the availability of high-quality RISC-V core designs, developed using industry best practices under the CORE-V banner, provide a unique contribution to the RISC-V ecosystem creating a platform for innovators to bring new products to market with unmatchable speed and capital efficiency; a path that GreenWaves has pioneered with the PULP project."

**Comment by ericpoirier** [comment]
The GreenWaves testimonials is now on the production website.
