### ISSUE TITLE
Fix CEA listing on membership page

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#311]
Please change the CEA entry on the "membership" list as follows:

* Currently the name is CEA List. Please change that to CEA.

* The weblink should be changed to https://www.cea-tech.fr/cea-tech/english/Pages/home-uk.aspx

thanks!

**Comment by autumnfound** [comment]
Preview available for this patch: https://deploy-preview-312--eclipsefdn-openhwgroup.netlify.app/membership/members/ Let me know if you need any other changes!
