### ISSUE TITLE
Post news item to openhwgroup.org

### ISSUE THREAD

**Issue by jph152** [openhwgroup/openhwgroup.org#313]
**Article heading:**
Register for our webinar on OpenHW CI and Regression Flows

**Article summary:**

We're just two weeks away from our next live webinar that highlights the motivation behind the OpenHW continuous integration (CI) environment and the benefits it delivers to open-source development.

**Content:**
We're just two weeks away from our next live webinar that highlights the motivation behind the OpenHW continuous integration (CI) environment and the benefits it delivers to open-source development. The webinar, with a live Q&A session, is being broadcast live on Thursday May 27 at 11am Eastern.

The episode dives into the importance of continuous integration, takes a closer look at the OpenHW CI environment, and examines how CI is employed specifically within the CORE-V Verification Test Bench and the CORE-V MCU projects.

Additionally, we look at the OpenHW core-v-verif GitHub repository, the distributed workflow in place, as well as the branching strategy used to manage multiple CORE-V core verification projects within a single repository.

In this webinar, you will get insights from Tim Saxe (CTO at QuickLogic) and Aimee Sutton (Platform Engineer at Metrics) alongside Mike Thompson and Florian Zaruba (both Directors of Engineering at OpenHW Group).

Register here:
https://us02web.zoom.us/webinar/register/WN_zx0s2q8EQ9eppiml4uPYug

**Publish date:**
As soon as convenient

**Comment by linkfang** [comment]
Hi @jph152 ,

Here is the preview link: https://deploy-preview-314--eclipsefdn-openhwgroup.netlify.app/news/2021/05/14/register-for-our-webinar-on-openhw-ci-and-regression-flows/

And the production one will be like this:  https://openhwgroup.org/news/2021/05/14/register-for-our-webinar-on-openhw-ci-and-regression-flows/

**Comment by jph152** [comment]
Thanks! Can we change the first sentence and article summary to the following:

Our next live webinar highlights the motivation behind the OpenHW continuous integration (CI) environment and the benefits it delivers to open source development.

--

Should be good to go live afterwards

**Comment by linkfang** [comment]
OK, changes are done, please review here:
https://deploy-preview-314--eclipsefdn-openhwgroup.netlify.app/news/2021/05/14/register-for-our-webinar-on-openhw-ci-and-regression-flows/

**Comment by jph152** [comment]
+1
