### ISSUE TITLE
Imperas testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#32]
please add...

**Simon Davidmann, President and CEO of Imperas**
“Open ISA’s, such as RISC-V, are at the forefront of the open source hardware momentum and processor design innovations and require high quality verification for broad adoption. Functional processor verification and compliance is best achieved with software-based methodologies based on comparison to a reference simulation model. As a founding member of the OpenHW group, Imperas is contributing the free riscvOVPsim ISS to support commercial-grade test and verification of the CORE-V Family of open-source RISC-V cores.”

**Comment by ericpoirier** [comment]
The Imperas testimonials is now on the production website.
