### ISSUE TITLE
Add new video to https://www.openhwgroup.org/resources/openhwtv/

### ISSUE THREAD

**Issue by jph152** [openhwgroup/openhwgroup.org#321]
Can we add the following to OpenHW TV? (https://www.openhwgroup.org/resources/openhwtv/)

OpenHW TV S02 E05
Software Task Group Project Updates
May 27, 2021

**YouTube video to embed**: https://www.youtube.com/watch?v=jVjqOGLBmBM

**TEXT:**

This OpenHW TV episode highlights the motivation behind the OpenHW continuous integration (CI) environment and the benefits it delivers to open source development.

The episode (broadcast live on May 27) dives into the importance of continuous integration, takes a closer look at the OpenHW CI environment, and examines how CI is employed specifically within the CORE-V Verification Test Bench and the CORE-V MCU projects.

Additionally, the webinar explores the OpenHW core-v-verif GitHub repository, the distributed workflow in place, as well as the branching strategy used to manage multiple CORE-V core verification projects within a single repository.

The expert panel includes Tim Saxe (QuickLogic) and Aimee Sutton (Metrics) alongside Mike Thompson and Florian Zaruba (OpenHW Group).

There is a 30 minute Q&A session moderated by Rick O'Connor, OpenHW Group President and CEO after around 30 minutes of presentations.

View on [youku.com](https://v.youku.com/v_show/id_XNTE2MzMxMDYzMg==.html
)

**Comment by rickoco** [comment]
Actually the title should be ‘OpenHW CI / CD Environment’ and not ‘Software Task Group Project Updates’

**Comment by linkfang** [comment]
Hi @jph152 , I am working on this now and find an issue about the video settings. It only allow user to watch it on Youtube, like so:
![image](https://user-images.githubusercontent.com/43075439/121553753-8fa86580-c9df-11eb-8212-4a775053c3bb.png)

Not sure if this is on purpose?

**Comment by linkfang** [comment]
> Thanks @linkfang. I'll let Nayl know and follow up when we have that sorted out.

Hi @jph152 , so just to confirm, would you like us to hold the changes and push it live after you fix the video settings? Or would you like to push the changes live first?

**Comment by jph152** [comment]
@linkfang the YouTube issue should be fixed now, so we are good to push it live. Thanks!

**Comment by linkfang** [comment]
> @linkfang the YouTube issue should be fixed now, so we are good to push it live. Thanks!

Awesome! Now it is live!
https://www.openhwgroup.org/resources/openhwtv/
