### ISSUE TITLE
Add CASPA to partner lists

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#323]
Please add CASPA to the partner lists on www.openhw.org

AFAIK there are two separate lists of members and partners. CASPA goes under partners at:

https://www.openhwgroup.org/membership/members/
https://www.openhwgroup.org/

Their web site is:
http://www.caspa.com/

Their name is 
CHINESE AMERICAN SEMICONDUCTOR PROFESSIONAL ASSOCIATION

Their logo is:
![caspalogo](https://user-images.githubusercontent.com/8946246/121971846-919b5d00-cd2e-11eb-92ae-2346ed9d968f.jpeg)

**Comment by linkfang** [comment]
Hi @DBees , please preview the changes here:
https://deploy-preview-330--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-330--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by DBees** [comment]
Looks great, thank you Zhou

Duncan

**Comment by linkfang** [comment]
Now the changes are live!
