### ISSUE TITLE
Add UCSB as Member to the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#324]
Hello,
Please add UCSB as Member to the OpenHW Group website. 
![UC-Santa-Barbara-Wordmark-Navy@1x (1)](https://user-images.githubusercontent.com/50374570/122062851-c73b5700-cdbd-11eb-938c-e0cf0f6ab584.png)
Thanks,
Zahra

**Comment by rickoco** [comment]
@ZahraFazli you also need to include the url to link the logo to... https://www.ucsb.edu/

**Comment by autumnfound** [comment]
Preview is available for the fix for this: https://deploy-preview-325--eclipsefdn-openhwgroup.netlify.app/?utm_source=github&utm_campaign=bot_dp

Let me know if you have any questions/concerns, and if its good to go!
