### ISSUE TITLE
Add Dolphin Design as Member of the OpenHW Group

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#326]
Hello,
Please add Dolphin Design as member on the OpenHW Group website
![logo-jaune](https://user-images.githubusercontent.com/50374570/122103525-b94cfc80-cde4-11eb-8857-eace38b83647.png)
Url: https://www.dolphin-design.fr/
Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the changes here:
https://deploy-preview-332--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZahraFazli** [comment]
LGTM. Thanks!

**Comment by linkfang** [comment]
NP!
Changes are live now!
