### ISSUE TITLE
Add news item to openhwgroup.org

### ISSUE THREAD

**Issue by jph152** [openhwgroup/openhwgroup.org#327]
**Article heading:**
Register for OpenHW TV S2 E06: CORE-V eXtension I/F (CVXIF)

**Article summary:**

This webinar will provide an overview of the CORE-V eXtension I/F, the project structure and roadmap as well as the SW tool chain implications of custom instructions.

**Content:**
This webinar will provide an overview of the CORE-V eXtension I/F, the project structure and roadmap as well as the SW tool chain implications of custom instructions. We'll also hear from one of the newest OpenHW Group members, Imagination Technologies, and its motivations for joining the OpenHW ecosystem. The webinar, with a live Q&A session, is being broadcast live on Thursday, June 24 at 11am EDT.

Speakers include:
Tim Whitfield – Chief of Engineering, Imagination Technologies  
Trefor Southwell – Senior Director of Hardware Engineering, Imagination Technologies
Jeremy Bennett – Chief Executive, Embecosm
Davide Schiavone – Director of Engineering, OpenHW Group

The session is moderated by Rick O'Connor, President & CEO, OpenHW Group.
After a series of brief presentations, there is a live Q&A roundtable session as usual.
 
Register for the webinar:
[http://ow.ly/RS2t50Fa9ab
](http://ow.ly/RS2t50Fa9ab
)

**Publish date:**
As soon as convenient

**Comment by linkfang** [comment]
Hi @jph152 , 

Please preview here: 
https://deploy-preview-331--eclipsefdn-openhwgroup.netlify.app/news/2021/06/16/register-for-openhw-tv-s2-e06-core-v-extension-i/f-cvxif/

Production link (once merged) will be:
https://openhwgroup.org/news/2021/06/16/register-for-openhw-tv-s2-e06-core-v-extension-i/f-cvxif/

**Comment by jph152** [comment]
Thanks. Can we list the speakers in a bulleted list? See below. Otherwise, looks good to me

- Tim Whitfield – Chief of Engineering, Imagination Technologies
- Trefor Southwell – Senior Director of Hardware Engineering, Imagination Technologies
- Jeremy Bennett – Chief Executive, Embecosm
- Davide Schiavone – Director of Engineering, OpenHW Group

**Comment by linkfang** [comment]
No problem. 
Changes have been made, please review here:
https://deploy-preview-331--eclipsefdn-openhwgroup.netlify.app/news/2021/06/16/register-for-openhw-tv-s2-e06-core-v-extension-i/f-cvxif/

**Comment by linkfang** [comment]
Now the changes are live!
https://www.openhwgroup.org/news/2021/06/16/register-for-openhw-tv-s2-e06-core-v-extension-i/f-cvxif/

**Comment by jph152** [comment]
Thanks!
