### ISSUE TITLE
Update TWG Chair

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#328]
Please remove existing TWG chairs at https://www.openhwgroup.org/working-groups/

For the moment we have one TWG Chair. Please add him.

name: Jérôme Quevremont
role: TWG Chair
company: Thales Group
LinkedIn https://www.linkedin.com/in/j%C3%A9r%C3%B4me-qu%C3%A9vremont-245335/?originalSubdomain=fr

**Comment by linkfang** [comment]
Hi @DBees , please preview the changes here:
https://deploy-preview-333--eclipsefdn-openhwgroup.netlify.app/

As there is just one TWG chair for now, so I made him in the center instead of the left side.

**Comment by DBees** [comment]
Looks good, thank you

**Comment by linkfang** [comment]
Now the changes are live!
