### ISSUE TITLE
Update MWG chair

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#329]
Please remove Kevin McDermott as co-chair of the MWG at https://www.openhwgroup.org/working-groups/

Please add Danny Hua as new co-chair

name: Danny Hua
company: Futurewei Technologies
role: MWG Co-chair

linked in handle: blank at the moment - to be confirmed with Danny Hua <dhua@futurewei.com>

**Comment by DBees** [comment]
Here is the linked in profile https://www.linkedin.com/in/danny-hua-85186ab/

**Comment by linkfang** [comment]
Hi @DBees , 
Please preview the changes here:
https://deploy-preview-334--eclipsefdn-openhwgroup.netlify.app/working-groups/

**Comment by DBees** [comment]
Looks good!

**Comment by linkfang** [comment]
Now the changes are live!
