### ISSUE TITLE
FOSSi Foundation quote

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#33]
please add...

**Philipp Wagner, Director at the FOSSi Foundation**
"The FOSSi Foundation welcomes the OpenHW Group to the Free and Open Source Silicon ecosystem. Their sustained development the CORE-V Family of open-source RISC-V cores
will be of great benefit to the community. We applaud their efforts to explore an open and meritocracy-based contribution model for free/open silicon, enabling individuals to work
as equals together with companies for the good of the whole ecosystem."

**Comment by ericpoirier** [comment]
The FOSSi Foundation testimonials is now on the production website.
