### ISSUE TITLE
Add McMaster University as a Member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#335]
Hi, 
Please add McMaster University as Members on the website.
Thanks,
Zahra

![mcm-col_png](https://user-images.githubusercontent.com/50374570/122603795-e991d680-d042-11eb-88cf-9b51463e27b4.png)
https://www.mcmaster.ca/

**Comment by autumnfound** [comment]
This is live!
