### ISSUE TITLE
Add Simon Fraser University as Member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#337]
Hello, 
Please add Simon Fraser University as Member of the OpenHW Group. 
![1596218642997](https://user-images.githubusercontent.com/50374570/122940808-ccab1b00-d342-11eb-817b-6e1351e58998.png)
URL: https://www.sfu.ca/

Thanks,
Zahra

**Comment by rickoco** [comment]
Actually - pls use this SFU logo
![SFU_horizontal_logo_rgb](https://user-images.githubusercontent.com/2498391/122946553-75f41000-d347-11eb-9e35-31b0a5a22e61.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the changes here:
https://deploy-preview-338--eclipsefdn-openhwgroup.netlify.app/

**Comment by rickoco** [comment]
@linkfang it appears @ZahraFazli is out / away so I'll chime in.  Changes look good, pls publish.

**Comment by linkfang** [comment]
Cool! Thanks @rickoco !
Now the changes are live!
