### ISSUE TITLE
Add Dover Microsystems as member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#339]
Please add Dover Microsystems as member on the OpenHW Group Website

![Dover-Microsystems](https://user-images.githubusercontent.com/50374570/123463984-35e89380-d5ba-11eb-913d-5e1ccc796d87.png)

URL: https://www.dovermicrosystems.com/

Thanks,
Zahra

**Comment by linkfang** [comment]
Now the changes are live!
https://www.openhwgroup.org/
