### ISSUE TITLE
Onespin testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#34]
please add...

**Raik Brinkmann, CEO of Onespin**
"The success of widespread RISC-V adoption hinges on design integrity of the processors and SoCs that contain them. We look forward to leveraging our verification expertise and working as a founding member of the OpenHW Group to make the highest quality CORE-V Family of open-source RISC-V cores available to the community."

**Comment by ericpoirier** [comment]
The Onespin testimonials is now on the production website.
