### ISSUE TITLE
OpenHW TV S2E06

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#340]
Can we add the following to the News feed as well as OpenHW TV page pls? (https://www.openhwgroup.org/resources/openhwtv/)

OpenHW TV S02 E06: CORE-V eXtension I/F
June 24, 2021

YouTube video to embed: https://youtu.be/W_a_K1T6Aj4

A key feature of the free and open RISC-V ISA is extensibility with the ability to add user-defined custom accelerators and instructions. The CORE-V eXtension I/F project within the OpenHW Group aims to provide a standard reusable interface to simplify how these custom accelerators can be connected to the family of CORE-V cores.

The webinar provides an overview of the CORE-V eXtension I/F, the project structure and roadmap as well as the SW tool chain implications of custom instructions. We'll also hear from one of the newest OpenHW Group members, Imagination Technologies and their motivations for joining the OpenHW ecosystem.

The session speakers include: Tim Whitfield and Trefor Southwell, Imagination Technologies; Jeremy Bennett, Embecosm; Davide Schiavone, OpenHW and the session will be moderated by Rick O'Connor, OpenHW.

View on [youku.com](https://v.youku.com/v_show/id_XNTE3NDE5ODA5Mg==.html)

**Comment by linkfang** [comment]
Hi @rickoco ,

Here is the OpenHW TV page preview link:
https://deploy-preview-342--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

Here is the news preview link: 
https://deploy-preview-342--eclipsefdn-openhwgroup.netlify.app/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-i/f/

Once the changes are merged, the production link will be this:
https://www.openhwgroup.org/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-i/f/

**Comment by rickoco** [comment]
> Hi @rickoco ,
> 
> Here is the OpenHW TV page preview link:
> https://deploy-preview-342--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/
> 
> Here is the news preview link:
> https://deploy-preview-342--eclipsefdn-openhwgroup.netlify.app/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-i/f/
> 
> Once the changes are merged, the production link will be this:
> https://www.openhwgroup.org/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-i/f/

Looks good @linkfang - publish away!

**Comment by linkfang** [comment]
Now the changes are live!

**Comment by rickoco** [comment]
I don't see the post on the News page... https://www.openhwgroup.org/news/

**Comment by autumnfound** [comment]
I see the article at the top of the page...unless you are referencing a different article?

![image](https://user-images.githubusercontent.com/23018241/124641432-b336c280-de5c-11eb-822d-e87e01f0db9d.png)

**Comment by linkfang** [comment]
> I see the article at the top of the page...unless you are referencing a different article?

I think @rickoco was saying about [this one](https://www.openhwgroup.org/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-if/), which I added to /content/news directory, and the url works fine, but it doesn't show in the news list on the page. 

This is the news in preview: 
https://deploy-preview-342--eclipsefdn-openhwgroup.netlify.app/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-if/
Here is the production version: 
https://www.openhwgroup.org/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-if/

Did I miss any steps?

**Comment by autumnfound** [comment]
> > I see the article at the top of the page...unless you are referencing a different article?
> 
> I think @rickoco was saying about [this one](https://www.openhwgroup.org/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-if/), which I added to /content/news directory, and the url works fine, but it doesn't show in the news list on the page. It's like the recap version of S2E06, the one in the screenshot is a register version.
> 
> This is the news in preview:
> https://deploy-preview-342--eclipsefdn-openhwgroup.netlify.app/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-if/
> Here is the production version:
> https://www.openhwgroup.org/news/2021/06/24/openhw-tv-s02-e06-core-v-extension-if/
> 
> Did I miss any steps?

This site uses the newsroom to populate lists and points at the pages we create as the source of the news. We need to ask whoever typically adds the news articles to newsroom for OHWG to just add a new submission and this is done. Our side is finished once we do that. I thought that was the article that was being referenced so I didn't push further.

I believe @jph152 typically takes care of that?

**Comment by jph152** [comment]
I just added the article to the openhwgroup.org news section. It should be live in a few minutes.

**Comment by linkfang** [comment]
Hi @rickoco , now it's fully live!
https://www.openhwgroup.org/news/

**Comment by rickoco** [comment]
thank you @linkfang and @jph152
