### ISSUE TITLE
Add Amazon as Member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#343]
Please add Amazon's logo as Member on OpenHW Group website
![1200px-Amazon_Web_Services_Logo svg](https://user-images.githubusercontent.com/50374570/124496208-2110ba80-dd87-11eb-888f-76d4fc24bcc8.png)

URL: https://www.amazon.com/

Thanks!

**Comment by rickoco** [comment]
actually this is the correct url https://aws.amazon.com/

**Comment by linkfang** [comment]
Hi @ZahraFazli @rickoco 

Please preview the changes here:
https://deploy-preview-344--eclipsefdn-openhwgroup.netlify.app/

**Comment by rickoco** [comment]
Looks good thank you.  Could you please also add the AWS logo to the Partner section and remove the IBM Cloud logo?

**Comment by autumnfound** [comment]
Should it be in both sections? Just double checking

**Comment by linkfang** [comment]
Hi @rickoco ,
Please preview the new changes here:
https://deploy-preview-344--eclipsefdn-openhwgroup.netlify.app/

And just would like to confirm what Martin mentioned earlier, now we have AWS logo in both Members and Partners. Is this what we expect to have?

**Comment by linkfang** [comment]
Hi @rickoco ,

Could you confirm if we are going to show AWS logo in both Members section and Partners section? Thanks!

**Comment by rickoco** [comment]
Yes pls - both sections.  Sorry for the delay, I haven't been getting notifications for some reason.
