### ISSUE TITLE
CMC Microsystems testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#35]
please add...

**Gordon Harling, President & CEO, CMC Microsystems**
"The CORE-V Family of open-source RISC-V cores from the OpenHW Group will provide important processor and sub-system infrastructure for Canada’s National Design Network, enabling leading-edge embedded system R&D with a path to proven silicon."

**Comment by ericpoirier** [comment]
The CMC testimonials is now on the production website.
