### ISSUE TITLE
Metrics testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#36]
please add...

**Doug Letcher, CEO, Metrics Technologies**
"Metrics is proud to be an early sponsor and contributor to the OpenHW Group CORE-V Family of open-source RISC-V cores and related processor sub-system.  Specifically, OpenHW's collaborative open-source verification test bench ensures the CORE-V RISC-V cores are suitable for high volume production SoCs."

**Comment by ericpoirier** [comment]
The Metrics testimonials is now on the production website.
