### ISSUE TITLE
Bluespec testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#37]
please add...

**Charlie Hauck, Board Director OpenHW Group and CEO, Bluespec**
“Bluespec is dedicated to making RISC-V safe and easy to use. We’re excited to see the growing adoption of RISC-V open-source processors and the new age of innovation that will enable. We look forward to contributing our expertise to the board of the OpenHW Group, whose aims we fully endorse."

**Comment by ericpoirier** [comment]
The Bluespec testimonials is now on the production website.
