### ISSUE TITLE
Add Whalemicro as a member

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/openhwgroup.org#370]
Please add Hefei Whale Microelectronics Co. Ltd logo on openHWgroup.org explore our members:
https://www.openhwgroup.org/membership/members

[logo.zip](https://github.com/openhwgroup/openhwgroup.org/files/7460850/logo.zip)

@meKokabi The file that we got is in .ai format. Can you please transform this into a .png for us?

**Comment by meKokabi** [comment]
@chrisguindon Here You Are: I shared these with Zahra last week.
[Loog Png-Svg.zip](https://github.com/openhwgroup/openhwgroup.org/files/7460927/Loog.Png-Svg.zip)

**Comment by linkfang** [comment]
I think this is a duplicated issue of this one? https://github.com/openhwgroup/openhwgroup.org/issues/367

Hefei Whale Microelectronics Co. Ltd has already been added

**Comment by linkfang** [comment]
Closing the issue as it's live
