### ISSUE TITLE
Add XMOS Ltd as Member

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#372]
Please add XMOS Ltd as member on the OpenHW Group website

URL: https://www.xmos.ai/
![XMOS_logo__colour_transparent copy](https://user-images.githubusercontent.com/50374570/141362667-de61ad47-a0b6-460e-89f4-b91c014019b0.png)

Thanks!

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the change here:
https://deploy-preview-373--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZahraFazli** [comment]
Looks good! Thanks!
