### ISSUE TITLE
Add Jade Design Automation as member

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#374]
Add Jade Design Automation as member on the OpenHW Group website

URL: https://jade-da.com/
![Jade-DA_logo_modified copy](https://user-images.githubusercontent.com/50374570/141495598-a057ad85-a085-4ea5-b324-86600a3f5c87.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the change here:
https://deploy-preview-377--eclipsefdn-openhwgroup.netlify.app/
