### ISSUE TITLE
Add C2MI as Member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#376]
Hello, 
Please add C2MI as Member on the OpenHW Group website

URL:  https://www.c2mi.ca/en/

![coul_c2mi_seul](https://user-images.githubusercontent.com/50374570/141824746-f008d02f-b182-4263-b2ef-8a11c042c4b8.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the change here:
https://deploy-preview-377--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZahraFazli** [comment]
Hi Zhou, Looks good. Thanks
