### ISSUE TITLE
OpenHW TV S2/Episode 8 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#379]
please add the following link to the OpenHW TV S2/Episode 8

View on youku 
https://v.youku.com/v_show/id_XNTgyMTA4MTA4MA==.html

**Comment by linkfang** [comment]
Hi @michelleclancy ,

Please preview the changes here:
https://deploy-preview-380--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by michelleclancy** [comment]
thank you!

**Comment by linkfang** [comment]
Actually, the changes are only live on preview site, not on production yet.

I am reopening the issue for now and will close it once it's live on production
