### ISSUE TITLE
RISC-V patterson testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#38]
please add...

**Dave Patterson, UC Berkeley Professor, Turing Laureate, & Vice-Chair RISC-V Foundation**
“As a passionate believer in open innovation, I’m delighted to see Rick leverage his successful experience with the RISC-V Foundation to lead the OpenHW Group, which will benefit the whole semiconductor industry by making open-source processor technology more accessible to a wider audience.”

**Comment by ericpoirier** [comment]
The RISC-V testimonials for Dave Patterson is now on the production website.
