### ISSUE TITLE
Update the broken link for Members & Partners

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#382]
Please update the link to the Members & Partners footer to lead to the "Explore Our Members" page: https://www.openhwgroup.org/membership/members/

Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the change here:
https://deploy-preview-383--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZahraFazli** [comment]
LGTM! Thanks!
