### ISSUE TITLE
working group calendar should be linkable 

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#384]
The working group calendar at the bottom of the page https://www.openhwgroup.org/working-groups/ should be linkable

That is, the heading "working group calls" should be linkable so that people can be given a link that takes them directly to this area of the webpage. 
![image](https://user-images.githubusercontent.com/8946246/144158186-3b49efc9-7b83-411a-aa3e-e5bd68ea383a.png)

**Comment by autumnfound** [comment]
Give https://www.openhwgroup.org/working-groups/#working-group-calls a shot ;)

**Comment by DBees** [comment]
Hello, you have given me a link to it, but that doesn't help anyone going to the page and trying to find a link that they can copy and share. How can a user find that link from that place on the wepage in order to share it? We are constantly referring people to the calendar, and anyone needs to be able to find that link you gave me easily.
thank you
Duncan

**Comment by chrisguindon** [comment]
There is a + Google Calendar button included in the widget:
![Screenshot 2022-01-04 163625](https://user-images.githubusercontent.com/893942/148127068-bb3d7893-5148-44d5-88f1-6e30e424fa57.jpg)


With that said, we can add a link  "working group calls" to https://calendar.google.com/calendar/u/0/r?cid=meetings@openhwgroup.org.

**Comment by linkfang** [comment]
Hi @DBees , please preview the change here:

https://deploy-preview-391--eclipsefdn-openhwgroup.netlify.app/working-groups/#working-group-calls

I added a button linking to https://calendar.google.com/calendar/u/0/r?cid=meetings@openhwgroup.org

**Comment by chrisguindon** [comment]
@linkfang I think @DBees wanted us to link on the **Working Calls** text in the paragraph.

I also think that the **Working Calls** is a typo that should be renamed to **Working Group Calls**

@DBees Can you confirm?

![Capture](https://user-images.githubusercontent.com/893942/148254186-cacfd705-4588-4410-9b91-fc10a20397aa.PNG)

**Comment by DBees** [comment]
Hi guys thanks for helping sort this out. @linkfang the button you added is the functionally what we need but it is a bit confusing as it looks similar to the existing Working Group Calls header.  @chrisguindon  said, I think it would be better to either link on the text in the paragraph that he highlighted (And yes it should say Working Group Calls not Working Calls) or else link on the existing header text Working Group Calls.  Thank you very much.

**Comment by DBees** [comment]
That looks good, thanks!
