### ISSUE TITLE
OpenHW working group listing on Eclipse website

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#388]
can you please add the EWG and AWG logos to this eclipse website https://www.eclipse.org/org/workinggroups/explore.php
[OPENHW Europe Group 4.zip](https://github.com/openhwgroup/openhwgroup.org/files/7672650/OPENHW.Europe.Group.4.zip)

**Comment by ericpoirier** [comment]
@shanda-eclipse @sharoncorbett can I get a +1 to add these logos on the explore page?

Thanks.

**Comment by SharonCorbett** [comment]
+1 Getting official logos up will be goodness.  They were asked to provide these logos.

**Comment by meKokabi** [comment]
Please find attached, I have added the svgs and resize the logos. Let me know if you. need more information/material.

[OPENHW Europe Group 4.zip](https://github.com/openhwgroup/openhwgroup.org/files/7677337/OPENHW.Europe.Group.4.zip)

**Comment by shanda-eclipse** [comment]
> Please find attached, I have added the svgs and resize the logos. Let me know if you. need more information/material.
> 
> [OPENHW Europe Group 4.zip](https://github.com/openhwgroup/openhwgroup.org/files/7677337/OPENHW.Europe.Group.4.zip)

@meKokabi can you please split Europe and Asia into two separate zip files? And we will need to create a separate issue for the updates to /artwork, as this issue deals with the explore working groups page.

**Comment by meKokabi** [comment]
@shanda-eclips
[OpenHW-Asia.zip](https://github.com/openhwgroup/openhwgroup.org/files/7677561/OpenHW-Asia.zip)
[OpenHW-Europe.zip](https://github.com/openhwgroup/openhwgroup.org/files/7677563/OpenHW-Europe.zip)
e

**Comment by shanda-eclipse** [comment]
FYI - seperate issue created for the artwork page: https://gitlab.eclipse.org/eclipsefdn/it/websites/eclipse.org/-/issues/29

**Comment by linkfang** [comment]
Hi, please preview the changes here:
https://staging.eclipse.org/org/workinggroups/explore.php

**Comment by shanda-eclipse** [comment]
+1 good to go live

**Comment by linkfang** [comment]
Cool, the changes are live!
