### ISSUE TITLE
RISC-V Redmond testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#39]
please add...

**Calista Redmond, CEO RISC-V Foundation**
“As we continue to cultivate the RISC-V community, we are excited to welcome organizations like OpenHW group as a forum for ongoing innovation and collaboration serving the many stakeholderss in the RISC-V revolution.”

**Comment by ericpoirier** [comment]
The RISC-V testimonials for Redmond is now on the production website.
