### ISSUE TITLE
Add Cobham Gaisler AB as a member on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#392]
Please add Cobham Gaisler AB as a member on the OpenHW Group website (https://www.openhwgroup.org/)
Thanks!
![caes-logo-no_tagline-blk copy](https://user-images.githubusercontent.com/50374570/148269436-89474936-0fd5-4a20-b7b9-07d35fdc927c.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:

https://deploy-preview-393--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-393--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
+1
