### ISSUE TITLE
Remove Aldec's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#394]
Aldec is no longer an OpenHW Group member. Please remove their logo from the website: https://www.openhwgroup.org/
Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli ,

Please preview the change here:
https://deploy-preview-396--eclipsefdn-openhwgroup.netlify.app/membership/members/
https://deploy-preview-396--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZahraFazli** [comment]
+1 Thanks!
