### ISSUE TITLE
OpenHW Group website blog page 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#395]
OpenHW Group website needs a page to post blogs from members. We are starting a blog campaign and will be posting monthly blogs to the website and driving track to the OpenHW Group website.  We currently have 3 blogs ready to go and need a page and a way to submit blogs for posting.

Paul has suggested -  I’ll leave this to Clark to work with the team.  My gut reaction is to change “OpenHW TV” to “Resources”, and from “Resources” get to “OpenHW TV” and “Blog” (and any other community links) - but that’s just a suggestion. Once designed, there is work to add a blog feature to the page.  See how Jakarta EE implements this - Clark can confirm, but I think this is the latest implementation we have.

**Comment by ericpoirier** [comment]
@shanda-eclipse can you confirm the suggested menu changes.

Thanks.

**Comment by shanda-eclipse** [comment]
Menu structure makes sense to me:

Resources
- OpenHW TV
- Blog

**Comment by linkfang** [comment]
Hi @michelleclancy  ,

Please preview the new menu here:
https://deploy-preview-397--eclipsefdn-openhwgroup.netlify.app/

Please note, I just added a "coming soon" as a placeholder on /blog page. Do we want to make the changes live after we add some blogs in?

**Comment by michelleclancy** [comment]
@linkfang thanks for the page update.. we have three blogs already.  Can you tell me how these will be uploaded, whats the process and how they will be listed? is it date, title, author, then click to read the blog?

**Comment by linkfang** [comment]
I think we could do something like the news list.
![image](https://user-images.githubusercontent.com/43075439/150026716-f08707b9-86e3-4606-b7a8-efe2d80b7b85.png)

And this is the same pattern as we do for the blog section on other site, like [Jakarta ee](https://jakarta.ee/blogs/) and [ecd tools](https://ecdtools.eclipse.org/resources/blogs/).
![image](https://user-images.githubusercontent.com/43075439/150026997-9edb0e48-ecb4-4b5c-8dbc-614b3a9e3157.png)

**Comment by michelleclancy** [comment]
@linkfang this is perfect, how would we post to the page? is there a summission site for me to upload the blogs too?  As mentioned I have two ready to go that we can post to get started

**Comment by chrisguindon** [comment]
@michelleclancy You can create an issue with the content and the team will create the page for you on the website. We will provide a preview which you will then need to approve before we would push it live!

**Comment by michelleclancy** [comment]
@chrisguindon great thanks, I'll send over the two that we have to populate the new page.

**Comment by chrisguindon** [comment]
@michelleclancy For this time, you can post them here since we are still working on this new section but once the section is live, we will expect you to create new issues for adding new posts!

**Comment by linkfang** [comment]
Hi @michelleclancy , just would like to confirm this issue is still on your radar :)

**Comment by michelleclancy** [comment]
@linkfang here is the first blog to post
[Imperas OpenHW DV blog (Oct 26 2021) v2.docx](https://github.com/openhwgroup/openhwgroup.org/files/7944448/Imperas.OpenHW.DV.blog.Oct.26.2021.v2.docx)

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the 1st blog here:
https://deploy-preview-397--eclipsefdn-openhwgroup.netlify.app/resources/blog/

**Comment by michelleclancy** [comment]
thank you, linkfang, this looks good. can we get this updated on the website?

**Comment by linkfang** [comment]
Sure, will request a code review from webdev team and then push live after that.

**Comment by linkfang** [comment]
Hi @michelleclancy , now the changes are live on production site!
