### ISSUE TITLE
Updating membership section to EF style

### ISSUE THREAD

**Issue by shanda-eclipse** [openhwgroup/openhwgroup.org#399]
We would like to update https://www.openhwgroup.org/membership/ to a tabbed style like https://www.eclipse.org/membership/.

The content was started in 2021, but needs to be finalized before web dev can complete the work. 

Here is the draft content: https://docs.google.com/document/d/1Pre1AEODp8dAaXu3A4p7LAesNy4HUYimYK0zS5-YZ80/edit?usp=sharing

CC @michelleclancy @ZahraFazli @DBees

**Comment by shanda-eclipse** [comment]
@michelleclancy would you be able to review and finalize the content with the OpenHW team by end of next week? If not, please provide a timeline.

**Comment by DBees** [comment]
Hi Shanda I think from the OpenHW perspective the updated content is basically good to go. I think if you can accept/remove all the editing marks as editor, we can do a final pass-through. Cheers! Duncan

**Comment by shanda-eclipse** [comment]
> Hi Shanda I think from the OpenHW perspective the updated content is basically good to go. I think if you can accept/remove all the editing marks as editor, we can do a final pass-through. Cheers! Duncan

Ready for your final review.

**Comment by shanda-eclipse** [comment]
Additionally, we should think about updating the "Members" top-level menu to have the following links:

- Explore our Members
- Member Benefits and Services
- Membership Levels
- Membership Fees
- Become a Member

To be discussed whether "Explore our Members" should be the first or last item on the list. WDYT @michelleclancy?

**Comment by shanda-eclipse** [comment]
@DBees @michelleclancy is this content considered final? https://docs.google.com/document/d/1Pre1AEODp8dAaXu3A4p7LAesNy4HUYimYK0zS5-YZ80/edit?usp=sharing

**Comment by DBees** [comment]
Hi Shanda,

Yes it is

Cheers

Duncan

**Comment by shanda-eclipse** [comment]
@ericpoirier this is ready for the webdev team

**Comment by ericpoirier** [comment]
> @ericpoirier this is ready for the webdev team

Hi @shanda-eclipse, do we have a deadline for this?

**Comment by shanda-eclipse** [comment]
> Hi @shanda-eclipse, do we have a deadline for this?
This was a Q1 MBO for webdev, but we took longer than expected to prep the content, so I think it's OK if it slips a little.

**Comment by ericpoirier** [comment]
@linkfang I looked into the styles of the Membership page on eclipse.org and it seems to be all in solstice-assets already.

**Comment by linkfang** [comment]
Hi @shanda-eclipse , @DBees , @michelleclancy , please preview the updates here:
https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/

**Comment by linkfang** [comment]
And based on current content, I don't see a link to [explore members page](https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/members/), do we want to add a button in jumbotron to link to there? Just like what we have on [EF membership page](https://www.eclipse.org/membership/)

**Comment by DBees** [comment]
Hi, nice work Zhou.

 

 

Some initial comments, probably I’ll have more when I have a bit more time:

 

1.	At the bottom of this page 

https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-benefits

, “contact us about membership” should say “How to become a member” and take one to the 

“Become a member” tab

 

2.	At the bottom of the pages “Eclipse Foundation Events” seems very out of place. Don’t we have an “events” section of the website where Eclipse events can be listed?

 

Duncan

**Comment by michelleclancy** [comment]
nice work all!! it reads so much better - I agree with Duncan's comments above.  @DBees if someone goes to view all on events, they can access the EF events also, I would suggest we remove the box below regarding the EF events on this membership page as it seems out of place.

**Comment by shanda-eclipse** [comment]
> At the bottom of this page https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-benefits , “contact us about membership” should say “How to become a member” and take one to the “Become a member” tab

I think we still need to include an option for people to "contact us about membership" if they have questions about the info on the page. In EF's case, we almost always have contacts reach out to our team with questions/clarifications before they are ready to commit to membership. Is that the case with OpenHW?

**Comment by shanda-eclipse** [comment]
@michelleclancy @DBees I think the events section is using the "Featured Story" functionality that is managed through our newsroom. It's on every page of your template (see https://www.openhwgroup.org/projects/) and we can easily update this content to something more relevant to OpenHW group. Just let me know what you want.

**Comment by shanda-eclipse** [comment]
> And based on current content, I don't see a link to [explore members page](https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/members/), do we want to add a button in jumbotron to link to there? Just like what we have on [EF membership page](https://www.eclipse.org/membership/)

See comment https://github.com/openhwgroup/openhwgroup.org/issues/399#issuecomment-1040301083 for menu updates

**Comment by shanda-eclipse** [comment]
- [ ] On https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-benefits I think we should remove the "Take advantage of marketing programs" and "Networking opportunities" sections, as they don't really match the style of the other bullets and are covered elsewhere. 
- [ ] On https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#platinum can we link "Eclipse Foundation Contributing Membership" to https://www.eclipse.org/membership/#contributing

Note to @DBees and @michelleclancy - I noticed that we reference OpenHW Asia and Europe in this content but don't have pages for either of those yet. Any idea when we will have pages for those working groups so we can add links?

**Comment by linkfang** [comment]
I updated the page based on feedback: 
https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/

Changes made:
- Updated top level "Membership" menu item
- Removed "Take advantage of marketing programs" and "Networking opportunities" sections
- Linked "Eclipse Foundation Contributing Membership" to https://www.eclipse.org/membership/#contributing for both instances in platinum and gold members

Things to be confirmed:
- "contact us about membership" button. Please let me know how you would like to proceed based on Shanda's comment here: https://github.com/openhwgroup/openhwgroup.org/issues/399#issuecomment-1060766425

**Comment by linkfang** [comment]
Hi @DBees , @michelleclancy , let me know if the preview above looks good to you. And how would you like to proceed with the "contact us about membership" button based on [Shanda's comment](https://github.com/openhwgroup/openhwgroup.org/issues/399#issuecomment-1060766425).

Thanks!

**Comment by linkfang** [comment]
Hi @DBees , @michelleclancy , just would like to confirm if this is still on your radar? Thanks!

https://github.com/openhwgroup/openhwgroup.org/issues/399#issuecomment-1066822747

**Comment by DBees** [comment]
@linkfang @shanda-eclipse OK how about we have two buttons - one the existing "contact us about membership" which should email to membership@openhwgroup.org and the other "become a members" which takes you directly to the "become a member" section.

**Comment by DBees** [comment]
@shanda-eclipse For the template that links to you Eclipse Foundation Events on every page, that really needs to instead take you to the OpenHW News and Events page https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/#news that is very buried in the fine print. In turn, the OpenHW Events page can point to the EF Events.  I suggest we setup a conf call to review this all and discuss the EWG and AWG page

**Comment by shanda-eclipse** [comment]
> @shanda-eclipse For the template that links to you Eclipse Foundation Events on every page, that really needs to instead take you to the OpenHW News and Events page https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/#news that is very buried in the fine print. In turn, the OpenHW Events page can point to the EF Events. I suggest we setup a conf call to review this all and discuss the EWG and AWG page

I've updated the current footer call-to-action so it highlights OpenHW news rather than EF events. This section is very easy for the marketing team to update, without webdev, so you can just let us know what you want it to say.

**Comment by linkfang** [comment]
@DBees , cool! Updated it with 2 buttons, please preview here:

https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/

**Comment by DBees** [comment]
@linkfang the two buttons look good to me
@shanda-eclipse your changes look good also.

**Comment by DBees** [comment]
@linkfang can you please change the new "contact us about membership button" to lead to membership@openhwgroup.org instead of info@openhwgroup.org. Also for the same button on this page https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-membership

**Comment by linkfang** [comment]
> 

Cool! 
Sorry I didn't notice the email address has changed. Updated all 4 instances:

https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/
https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-levels
https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-fees
https://deploy-preview-417--eclipsefdn-openhwgroup.netlify.app/membership/#tab-membership

**Comment by DBees** [comment]
@linkfang Excellent thanks. 
While we're at it can you look at the create account section (which is actually aimed at creating an EF account). First question is why is duplicated in the green bar? Shouldn't that be removed?

![image](https://user-images.githubusercontent.com/8946246/159773034-838523f6-4466-440d-87fe-2f713e8f299e.png)

**Comment by DBees** [comment]
Second question @shanda-eclipse @linkfang "Create Account" and Edit Account" lead to exactly the same material. Why not replace it with a single "Create or Edit Eclipse Foundation Account"

Third question why don't we put that under "resources" instead of a separate menu bar

Fourth question "Manage cookies" doesn't do anything, why don't we get rid of it, unless you are planning to introduce a cookie management function.

**Comment by linkfang** [comment]
Agreed with @shanda-eclipse , and I created https://github.com/openhwgroup/openhwgroup.org/issues/424 to discuss them

And for the membership section, based on the preview, are we good to go live? @DBees

**Comment by DBees** [comment]
As far as I'm concerned yes

**Comment by michelleclancy** [comment]
Go live – thanks


From: Zhou Fang ***@***.***>
Reply-To: "openhwgroup/openhwgroup.org" ***@***.***>
Date: Wednesday, March 23, 2022 at 3:39 PM
To: "openhwgroup/openhwgroup.org" ***@***.***>
Cc: michelleclancy ***@***.***>, Mention ***@***.***>
Subject: Re: [openhwgroup/openhwgroup.org] Updating membership section to EF style (Issue #399)


Agreed with @shanda-eclipse<https://github.com/shanda-eclipse> , and I created #424<https://github.com/openhwgroup/openhwgroup.org/issues/424> to discuss them

And for the membership section, based on the preview, are we good to go live? @DBees<https://github.com/DBees>

**Comment by linkfang** [comment]
NP! The change is now live!
