### ISSUE TITLE
Eclipse testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#40]
please add...

**Mike Milinkovich, Executive Director of the Eclipse Foundation**
"The Eclipse Foundation has been at the forefront of community-based open source software development for many years. We are pleased to provide our guidance and expertise for the launch and growth of the OpenHW Group. We look forward to the future success of the CORE-V Family of open source RISC-V based processors and related subsystem IP, tools, and software.”

**Comment by ericpoirier** [comment]
The Eclipse Foundation testimonials is now on the production website.
