### ISSUE TITLE
Blog submission for posting 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#401]
[Blog_cv32e40p.docx](https://github.com/openhwgroup/openhwgroup.org/files/8025642/Blog_cv32e40p.docx)

**Comment by linkfang** [comment]
Hi @michelleclancy ,

Please preview the changes here:

Blog list: https://deploy-preview-402--eclipsefdn-openhwgroup.netlify.app/resources/blog/
Blog: https://deploy-preview-402--eclipsefdn-openhwgroup.netlify.app/resources/blog/open-source-hardware-the-new-reality-cv32e40p-project/

**Comment by michelleclancy** [comment]
Looks good thank you!

**Comment by linkfang** [comment]
The change is now live!
