### ISSUE TITLE
Update Membership Application Form on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#403]
Attached, is the updated Member Contact Form (previously known as the Membership Application Form) on the "Become A Member" page" https://www.openhwgroup.org/membership/contact/

The updated form is called Member Contact Form, therefore, update the name from Membership Application Form to Member Contact Form. 

Thanks!
[OpenHW Group - Member Contact Form.docx](https://github.com/openhwgroup/openhwgroup.org/files/8034850/OpenHW.Group.-.Member.Contact.Form.docx)

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the updates here:

https://deploy-preview-408--eclipsefdn-openhwgroup.netlify.app/membership/contact/
https://deploy-preview-408--eclipsefdn-openhwgroup.netlify.app/membership/contact/openhw-membership-contact-form.pdf

I have set up a redirect from the old URL (/openhw-membership-application-form.pdf) to the new one (/openhw-membership-contact-form.pdf), just in case the old URL is being used somewhere else. 

So, https://deploy-preview-408--eclipsefdn-openhwgroup.netlify.app/membership/contact/openhw-membership-application-form.pdf will also take the user to our new doc.
Thanks @ericpoirier for the support!

**Comment by ZahraFazli** [comment]
LGTM! @michelleclancy if you think this is okay, we can make it live

**Comment by michelleclancy** [comment]
@ZahraFazli has Duncan approved the update to the form?

**Comment by ZahraFazli** [comment]
Yes, he approved the content, just want to confirm the layout with you.

**Comment by ZahraFazli** [comment]
Thanks! All good @linkfang

**Comment by linkfang** [comment]
NP! Now the change is live!
