### ISSUE TITLE
Add ICT-CAS as a Member on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#404]
Please add ICT-CAS as a Member on the OpenHW Group website.
![header_ict](https://user-images.githubusercontent.com/50374570/153255456-6b5f5528-ecdc-4619-8b29-5e502cedd996.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the update here:

https://deploy-preview-407--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-407--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by linkfang** [comment]
NP! The change is live!
