### ISSUE TITLE
mailchimp sign up 

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#41]
need to add mail list sign up page to collect the std data: first name, last name, company, country, email and include both the OpenHW and CORE-V logos if we can as well as the following text:
 
“Join our mailing list to learn more about the OpenHW Group CORE-V Family of open-source RISC-V cores and how you can contribute to the evolution of open-source processor core development.”

**Comment by ericpoirier** [comment]
Hi Rick,

The mailing list link has been added to the production website. The link was provided by Stephanie, if there are any changes to be made on the Mailchimp page itself, please let her know directly.
