### ISSUE TITLE
New OpenHW TV episode to post

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#410]
Hi can we post the January episode on the OPenHW TV webpage - 

OpenHW TV S03/E01 
Fireside Chat with Nitin Dahad, Editor, embedded.com & Rick O'Connor, OpenHW Group

In this discussion, Nitin and Rick will discuss the key drivers for growth of open-source processor development, among other topics including the latest milestones and projects of the OpenHW Group. A live chat with attendees will be featured at the end of the interview.  Youtube link: https://www.youtube.com/watch?v=KDs5gVxPOr8&t=15s

View on Youku (https://v.youku.com/v_show/id_XNTg0MTg1NzcyOA==.html)

**Comment by linkfang** [comment]
Hi @michelleclancy ,

Please preview the change here:
https://deploy-preview-411--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

BTW, I found the title on Youku has an extra "-t", not sure if that's on purpose or a typo.
![image](https://user-images.githubusercontent.com/43075439/154354811-36229fd2-6aa1-4e95-9e02-028bb1bd4d4f.png)

**Comment by michelleclancy** [comment]
@linkfang can you add CEO after Rick's name.. Rick O'Connor, CEO, OpenHW Group.. otherwise looks good.. thanks for the extra t find but I can't fix that.. I don't think it's a big deal.

**Comment by linkfang** [comment]
Updated it, please preview here:
https://deploy-preview-411--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by michelleclancy** [comment]
@linkfang looks good - approved
