### ISSUE TITLE
Add Espressif Systems (Shanghai) Co. Ltd as Member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#412]
Please add Espressif Systems (Shanghai) Co. Ltd as a member on OpenHW Group website: 
![Espressif_Logo_EN_01](https://user-images.githubusercontent.com/50374570/156625279-c448e23d-36fc-4760-946f-bb35fee15c10.png)

URL: https://www.espressif.com/

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:

https://deploy-preview-413--eclipsefdn-openhwgroup.netlify.app/#members-partners
https://deploy-preview-413--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
+1

**Comment by linkfang** [comment]
The change is now live!
