### ISSUE TITLE
New Episode for openhw TV for website

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#414]
OpenHW TV S03/E02

Driving AI/ML Innovation with CORE-V, Open-Source RISC-V Based Processors

This episode features the artificial intelligence angle of the OpenHW Group CORE-V family. We will focus specifically on the CV32E40P RISC-V CPU. In the last decade we experienced that as technology scales, silicon devices become smarter and smarter, capable of implementing complex functions on hand-sized (or lower) objects such as: face recognition on mobile phones; wearable sport and health monitoring products; smart glasses; augmented reality headset; etc. Such features have become real not only due to silicon scaling but also thanks to innovative computer architectures and software stacks.

In this webinar we will show how custom extensions to the baseline RISC-V architecture and advanced parallel computer architectures enable edge-computing pattern recognition algorithms running at high energy efficiency on battery-powered systems. We will conclude by showing applications leveraging it as autonomous driving drones and mobile vision applications.

YouKu: https://v.youku.com/v_show/id_XNTg0NjU3NTQwNA==.html 
 
OpenHW Youtube:
https://youtu.be/ekMwejZlJEo

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the change here:
https://deploy-preview-415--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by michelleclancy** [comment]
@linkfang looks good!! approved

**Comment by linkfang** [comment]
The change is now live!
