### ISSUE TITLE
Remove NEC's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#416]
NEC Corporation is no longer a member of OpenHW Group. Kindly remove the logo from the website. 
Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:

https://deploy-preview-418--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-418--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
+1

**Comment by ZahraFazli** [comment]
Hi Zhou, NEC is still appearing here: https://www.openhwgroup.org/membership/members/

**Comment by linkfang** [comment]
> Hi Zhou, NEC is still appearing here: https://www.openhwgroup.org/membership/members/

Yes, as the changes are not live on prod site yet. 

If you check on preview version, it should look like this:
![image](https://user-images.githubusercontent.com/43075439/157330325-22131810-971b-4d4a-9cd4-1c4991c55d08.png)

**Comment by ZahraFazli** [comment]
Thanks, looks good.

**Comment by linkfang** [comment]
The change is now live!
