### ISSUE TITLE
Add OSFPGA as a Partner

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#419]
Please add OSFPGA as a Partner and link their logo here https://osfpga.org/

![open fpga_profile](https://user-images.githubusercontent.com/2498391/157741856-a3141eea-552f-4e50-a9ce-87370bda5e61.png)

**Comment by linkfang** [comment]
Hi @rickoco , please preview the update here:

https://deploy-preview-420--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-420--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by linkfang** [comment]
Hi @rickoco , just would like to confirm if this is still on your radar?

**Comment by linkfang** [comment]
Hi @rickoco , we are still on hold for pushing the change live, let me know if it looks good to you, thanks!
