### ISSUE TITLE
Remove University of Utah's logo on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#421]
University of Utah is no longer an OpenHW Group member. Kindly remove their logo from the website. 
Thanks,
Zahra

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:

https://deploy-preview-422--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-422--eclipsefdn-openhwgroup.netlify.app/membership/members/
