### ISSUE TITLE
Add link to OpenHW Mattermost on website

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#425]
Put "OpenHW Mattermost" under the resources menu leading to the following URL

https://mattermost.openhwgroup.org/all-users/channels/town-square

**Comment by linkfang** [comment]
Hi @DBees , please preview the change here:
https://deploy-preview-427--eclipsefdn-openhwgroup.netlify.app/

I put it as the 1st item under Resources, let me know if you would like a different order

**Comment by DBees** [comment]
That is brilliant @linkfang thank you!

**Comment by linkfang** [comment]
NP! The change is now live!
