### ISSUE TITLE
Add Rumble Development Corp as member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#426]
Rumble Development Corp is a new member. Please add their logo on the website. Thanks
[Rumble logo 2018.pdf](https://github.com/openhwgroup/openhwgroup.org/files/8344622/Rumble.logo.2018.pdf)

**Comment by linkfang** [comment]
Hi @ZahraFazli , I am afraid we can't use a pdf version. Do they have a png or svg version? Thanks!

**Comment by linkfang** [comment]
Hi @ZahraFazli , just would like to confirm if this is still on your radar?

**Comment by ZahraFazli** [comment]
Hi Zhou, I will ask for the png version and get back to you. Thanks

**Comment by ZahraFazli** [comment]
Update: We have requested a png version of the company's logo from the member but we have not heard back.

**Comment by rickoco** [comment]
@ericpoirier @linkfang - it is simple to convert PDF to PNG which I have done (took about 30sec using Preview on a Mac) and attached here.  In the future, pls make these simple changes instead of causing delays and more work from our members.
![Rumble logo 2018](https://user-images.githubusercontent.com/2498391/168910376-42acab43-0dcd-4100-a214-3652c954793e.png)

**Comment by chrisguindon** [comment]
Hi @rickoco,

Please understand that there is more to this than simply converting a PDF to a png. Most organizations have strict logo guidelines. The logo guidelines might or might not have strict rquirement on things like the whitespace around the logo, the color.

By converting to a PDF, you might be in violation of the brand/logo guidelines. Depending on how you converted the logo, you might have altered the color. This might not be a problem for all organization but larger corporations are very strict about how their brand is used.

To avoid any issue and to keep thing simple for us, we ask our staff to NOT modify any organization logo. We prefer to use the logo that was provided by the orginzation. If you have any concerns with that, please feel free to reach out to me.

The only exception would be logos that we own such as the EF logo. Any modification must adhere to our brand guidelines: https://www.eclipse.org/legal/documents/eclipse_foundation_branding_guidelines.pdf

**Comment by rickoco** [comment]
Appreciate your comments @chrisguindon.  In this instance Rumble is a very small company and no graphics team.  Please use the attached logo and post to the OpenHW site.

**Comment by chrisguindon** [comment]
Sounds good @rickoco. I will take you word that had permission to create that file and we will do the update!

@linkfang Can you make sure this is done before EOD Thursday please?

**Comment by linkfang** [comment]
Hi @rickoco , @ZahraFazli , please preview the update here:

https://deploy-preview-459--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-459--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by rickoco** [comment]
Thx @chrisguindon and @linkfang - deploy preview looks good.

**Comment by linkfang** [comment]
NP, the change is now live!
