### ISSUE TITLE
Additional resources under the resource menu

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#428]
Please add these resources under the Resources Menu

OpenHW Read The Docs
https://readthedocs.com/organizations/openhw-group/

OpenHW Project Dashboard
https://github.com/openhwgroup/core-v-docs/blob/master/program/dashboard/Dashboard.md

OpenHW Project Descriptions
https://github.com/openhwgroup/core-v-docs/tree/master/program/Project-Descriptions-and-Plans

**Comment by DBees** [comment]
Spelling of first item should be "OpenHW Read the Docs"

**Comment by linkfang** [comment]
Please see it in action here:
https://deploy-preview-429--eclipsefdn-openhwgroup.netlify.app/

**Comment by DBees** [comment]
Looks great. Just double checking on the Read The Docs, hang on

**Comment by DBees** [comment]
@linkfang for now please go ahead with the changes except the Read The Docs one. Actually we need to identify the proper way for general public to access the RTD OpenHW menu and the link I provided isn't the right method. As soon as we get that sorted out with RTD I will open another issue. Sorry for the confusion.

**Comment by linkfang** [comment]
The change is now live!
