### ISSUE TITLE
blog post for openHW

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#431]
Can we add a direct link on the Blog page to Duncan's article on the News page
Date it March 29 - 

title: OpenHW Group: An Open Approach to Microprocessor Design

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the update here:
https://deploy-preview-433--eclipsefdn-openhwgroup.netlify.app/resources/blog/

It's the 2nd item in the list

**Comment by linkfang** [comment]
NP! The change is now live!
