### ISSUE TITLE
OpenHW TV Season 03/Episode 03

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#432]
please post on the OpenHW TV web page

 
OpenHW TV S03/E03 - CORE-V Cores: Seeding the Next Generation of Innovators with Open-source RISC-V Processors
 
Open-source technologies have revolutionized industrial hardware and software development. These approaches are now bringing new energy to engineering education. Universities use open-source hardware and software to teach architectures and concepts while providing students hands-on experience with coding, design, and research.
 
In this webinar, we highlight the use of OpenHW Group CORE-V open-source RISC-V CPUs at leading Universities to teach CPU architecture, instruction-sets, and HW design. CORE-V platforms are used in bachelor’s level engineering coursework, at the master’s thesis level, and also in doctoral research. Students have contributed their work back to open-source projects at OpenHW Group, gaining valuable industrial experience. The PULP Training workshop developed by ETH Zurich compliments for-credit courses to help companies and universities start working with CORE-V CPUs and PULP microcontrollers.
 
The OpenHW TV presentation will be led by Davide Schiavone from OpenHW Group and Nils Wistoff from ETH Zurich.
 
YouTube: https://youtu.be/mSjJ478p0Zs 
 
Yuku: https://v.youku.com/v_show/id_XNTg1NTIzMDUwNA==.html

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the new video here:
https://deploy-preview-433--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

I found the youku video showed a 404 not found.

**Comment by michelleclancy** [comment]
thanks, it looks good, I'm checking on the youku link now

**Comment by michelleclancy** [comment]
we are all good with the blogs and openHW tv

**Comment by linkfang** [comment]
Hi @michelleclancy , just would like to confirm 1 thing on the blog, we had the words "INSERT IMAGE 1" (and "INSERT IMAGE 2") before each image. Are we planning to keep those words or to remove them?

![image](https://user-images.githubusercontent.com/43075439/161565232-0e8b3890-4f7b-4511-a4ce-3bdb49577ab9.png)

**Comment by michelleclancy** [comment]
@linkfang please remove insert image 1 and 2.. that was jsut a place holder

**Comment by linkfang** [comment]
Sounds good! The change is now live!
