### ISSUE TITLE
Expand "Working Groups" menu to include info on OpenHW Asia and OpenHW Europe

### ISSUE THREAD

**Issue by shanda-eclipse** [openhwgroup/openhwgroup.org#434]
We would like expand the "Working Groups" menu item on https://www.openhwgroup.org/ to have some child pages. The new menu would be:

Working Groups

- Technical and Marketing Working Groups - move https://www.openhwgroup.org/working-groups/ to a child page
- OpenHW Asia - new page, with new content that needs to be developed
- OpenHW Europe - new page with new content that needs to be developed

This is not yet ready for the webdev team, as we need to prepare the content for the new pages. @michelleclancy @DBees @ZahraFazli how would you like to work on this content?

**Comment by shanda-eclipse** [comment]
@michelleclancy please send the content you have so far. Once we know what's going to be on the pages, we can determine how long it will take to implement.

**Comment by ZahraFazli** [comment]
Hi @shanda-eclipse I am happy to forward you the working group members., along with their participation levels and their logos.

**Comment by michelleclancy** [comment]
here are the page content we have. @ZahraFazli @shanda-eclipse if we can add the members to each page that would be great.
[AWG website v1 4.5.docx](https://github.com/openhwgroup/openhwgroup.org/files/8420960/AWG.website.v1.4.5.docx)

[EWG webpage v1 4.5.docx](https://github.com/openhwgroup/openhwgroup.org/files/8420959/EWG.webpage.v1.4.5.docx)

**Comment by linkfang** [comment]
I assume I can start working on this based on the content above?

I will probably get preview site up today and I think we can get it finalized sometime next week (some tweaks based on feedback).

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the 3 new pages here:

https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-europe/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/membership/join-awg-and-ewg/

Please note, 

- Using placeholders for the chair info on each page as it's not in the word docs. Can you share me the info of it? 
- Haven't added the members to each page. Can add them in once I get them. @ZahraFazli , can you please share the list with me as well?
- Let me know if the URL structure for joining AWG and or EWG (3rd URL above) looks good.

Thanks!

**Comment by linkfang** [comment]
For sure, @DBees , @rickoco , please preview the 3 new pages here:

https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-europe/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/membership/join-awg-and-ewg/

**Comment by DBees** [comment]
@linkfang @michelleclancy @davideschiavone @rickoco I have simplified and revised the AWG text. Please review and once we finalize we can extend to EWG. https://docs.google.com/document/d/1lVf_Ukmzr__seGO-cWQcx6xEqK660t5chTVrYqgyLDA/edit#heading=h.bjbn11fp7xul

**Comment by linkfang** [comment]
Hi @michelleclancy @davideschiavone @rickoco , let me know if we are good with the updated doc Duncan provided above and if we would like to do the same for EWG text. Thanks!

**Comment by michelleclancy** [comment]
@linkfang yes, the updates on the AWG look good and we can duplicate for EWG.  @ZahraFazli can we add the members to these two pages?? we have a press release, that I'd like to get out the first week in May announcing these two groups.

**Comment by linkfang** [comment]
Hi @DBees , can you please provide a simplified version of EWG? 

@ZahraFazli if we are good to display the members on these 2 pages, you could send them to me and I will add them in. 

Thanks!

**Comment by linkfang** [comment]
@michelleclancy , @DBees , here is the updated AWG preview:
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/

I can update EWG and add members when they are ready!

**Comment by ZahraFazli** [comment]
Below is the working group member's list

**OpenHW Group Asia**
- Futurewei Technologies, Inc.
- Institute of Software Chinese Academy of Sciences
- NXP USA, Inc.
- Pingtouge Semiconductors Co. Ltd (C-Sky)

**OpenHW Group Europe**
- Barcelona Supercomputing Center (BSC)
- ETH Zurich
- Imagination Technologies Limited
- NXP USA, Inc.
- University of Bologna

**Comment by DBees** [comment]
OpenHW Asia Working Group also includes Institute of Computing Technology - Chinese Academy of Sciences in addition to hose listed

**Comment by DBees** [comment]
@davideschiavone you should provide the EWG text to correspond to the AWG text above

**Comment by DBees** [comment]
Instructions for joining: slight modification
replace:
and a commitment to follow Eclipse Foundation policies and processes.
with:
and a commitment to follow the Eclipse Foundation policies and processes and logo use as described above.

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the members here:
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-europe/

Hi @DBees , please preview the updated instructions for joining here:
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/membership/join-awg-and-ewg/

**Comment by DBees** [comment]
@linkfang there are two separate companies. 

We should have all the company's logos at https://www.openhwgroup.org/membership/members/

Note that Pingtouge should be replaced by Alibaba Group.

**Comment by DBees** [comment]
@linkfang actually you can make the text:
instead of "policies and processes and logo use", use "policies and logo use"
thanks!

**Comment by shanda-eclipse** [comment]
Looping in @sharoncorbett to confirm that we are OK to publish the OpenHW Europe and Asia pages:
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-europe/

**Comment by linkfang** [comment]
@DBees , cool, updated the text content and the members. They are using the short name in openhw members, so I did not find them earlier. 

https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/

**Comment by davideschiavone** [comment]
Thanks for carrying this!

Here is the text for EWG

The OpenHW Europe Working Group (EWG) focuses on the European ecosystem requirements for open-source hardware, and related software, complementing the work program of the OpenHW Group. 
Those initiatives may address strategic or market analysis, technical requirements, and digital sovereignty. By working collaboratively, members of Eclipse Foundation and OpenHW Group can pursue those initiatives and have a positive impact with strategic open hardware and related open software projects. 

Specific tasks of EWG include will drive towards:

1. Meeting European data sovereignty requirements for OpenHW Group, for example by creating Europe-based OpenHW open-source repositories

2. Aiming to participate in, and potentially to lead, European Projects (i.e. those funded by the European Commission or similar funding bodies)

3. Gathering European requirements and technology needs for an open hardware ecosystem and from this, help to initiate projects of the OpenHW Group. This could include identifying processor cores, other IP of interest and/or software needs for European market segments

4. Supporting marketing for Eclipse Foundation and/or OpenHW Group initiatives in the European context by creating content, disseminating it, and by recruiting EWG members. 

EWG will not itself undertake open-source or standardization projects but will prepare and present Project Concept proposals to the OpenHW Group Technical Working Group (TWG).

EWG is organized as an Eclipse Foundation Working Group and reports to the Board of Directors (BoD) of OpenHW Group, in parallel with the OpenHW Group Technical and Marketing WGs.

**Comment by DBees** [comment]
yes all good now.

**Comment by michelleclancy** [comment]
@linkfang @DBees all good now to go live :) thank you!! nice work

**Comment by SharonCorbett** [comment]
@DBees 

The "_reports to the board_" in the last sentence, "EWG is organized as an Eclipse Foundation Working Group and reports to the Board of Directors (BoD) of OpenHW Group, in parallel with the OpenHW Group Technical and Marketing WGs." is unnecessary.

Suggested edit: "The OpenHW EWG is a joint initiative of the Eclipse Foundation AISBL and the OpenHW Group.  The EWG works collaboratively with OpenHW Group's Technical and Marketing Working Groups."

Feel free to provide another suggestion.

Thanks and Regards,
Sharon

**Comment by DBees** [comment]
@SharonCorbett that sort of misses the point which is to inform that EWG (AWG) are setup as EF working groups. 
while describing their forming a part of OpenHW Group scope. 'Working collaboratively' doesn't really catch it in my view, sounds distant, you can work collaboratively with anyone. I'd leave as it.

@linkfang can you make the line spacing of the EWG blurb the same as AWG?

**Comment by SharonCorbett** [comment]
@DBees Feel free to revise both without using the "reports to the board"...

**Comment by DBees** [comment]
@SharonCorbett from OpenHW perspective that's accurate. Let's talk off line.

**Comment by michelleclancy** [comment]
@shanda-eclipse @SharonCorbett  do we know when the EWG and AWG webpages will be live?? we are trying to schedule a press release and need to have the pages live when the release goes out

**Comment by SharonCorbett** [comment]
@DBees and I were collaborating offline on one final adjustment.  Duncan can update here the neceessary changes for EGW and AWG.  When those changes are in place, you'll be good to go!

**Comment by DBees** [comment]
@linkfang you can replace the sentence in question with 
"EWG is organized as an Eclipse Foundation Working Group which forms part of the OpenHW Group working structure alongside the OpenHW Technical Working Group (TWG), Marketing Working Group (MWG), and Asia Working Group (AWG)”.  

And the same change for AWG 
"AWG is organized as an Eclipse Foundation Working Group which forms part of the OpenHW Group working structure alongside the OpenHW Technical Working Group (TWG), Marketing Working Group (MWG), and Europe Working Group (EWG)”.

**Comment by linkfang** [comment]
Cool! I updated the text and also the line spacing, please preview here:

https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-europe/
https://deploy-preview-436--eclipsefdn-openhwgroup.netlify.app/working-groups/openhw-asia/

**Comment by DBees** [comment]
Good to go, thank you.

**Comment by linkfang** [comment]
NP!

And the pages are now live!
https://www.openhwgroup.org/working-groups/openhw-asia/
https://www.openhwgroup.org/working-groups/openhw-europe/

cc// @michelleclancy
