### ISSUE TITLE
Update the URL linked to "Become a member" button in the side bar

### ISSUE THREAD

**Issue by linkfang** [openhwgroup/openhwgroup.org#437]
Just found we still have the [old "Become a member" page](https://www.openhwgroup.org/membership/contact/) live and it's linked to the "Become a member" button in the side bar. See this page: https://www.openhwgroup.org/membership/members/

![image](https://user-images.githubusercontent.com/43075439/162281009-c567c187-b114-4f02-9b1c-94acc1909dad.png)

After we updated the membership page based on https://github.com/openhwgroup/openhwgroup.org/issues/399, I assume we don't want to keep the old one anymore? Instead, we can link the new ["Become a member" page](https://www.openhwgroup.org/membership/#tab-membership) to the button?

WDYT? @DBees @michelleclancy

**Comment by michelleclancy** [comment]
@linkfang correct, after the updated new page, we don't need the old page

**Comment by linkfang** [comment]
Cool, but I don't manage the content of the form/pdf. 
@ZahraFazli , can you please confirm and update the pdf file? Thanks!

**Comment by DBees** [comment]
@zahrafazli see my request via email March 22, thanks.

**Comment by ZahraFazli** [comment]
@linkfang Attached, please find the updated Member Contact Form. Thanks.
[OpenHW Group - Member Contact Form.pdf](https://github.com/openhwgroup/openhwgroup.org/files/8516130/OpenHW.Group.-.Member.Contact.Form.pdf)

**Comment by DBees** [comment]
@ZahraFazli it still says info@ instead of membership@

**Comment by ZahraFazli** [comment]
[OpenHW Group - Member Contact Form.pdf](https://github.com/openhwgroup/openhwgroup.org/files/8516157/OpenHW.Group.-.Member.Contact.Form.pdf)
 Please check if all's good now.

**Comment by DBees** [comment]
looks good

**Comment by linkfang** [comment]
Hi @DBees , are we all good on the changes and push them live?

**Comment by DBees** [comment]
@linkfang go ahead

**Comment by linkfang** [comment]
The change is now live!
