### ISSUE TITLE
OpenHW Calendar on resources menu

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#439]
Please add the OpenHW Calendar (found at bottom of the working group page) to the resources menu.

**Comment by linkfang** [comment]
Hi @DBees , please preview the change here:
https://deploy-preview-440--eclipsefdn-openhwgroup.netlify.app/

I put it as the last item in resources, let me know if this order works for you, thanks!

**Comment by DBees** [comment]
Perfect!!! Thanks a lot

**Comment by linkfang** [comment]
NP! The change is live!
