### ISSUE TITLE
Add GroupGets as a member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#441]
Please add GroupGets LLC as a Member on the OpenHW Group website. 
Thanks,
Zahra
![GroupGets Logo (1)](https://user-images.githubusercontent.com/50374570/164079566-ca95cc41-0069-4aaf-9638-b859609c73b1.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the update here:

https://deploy-preview-442--eclipsefdn-openhwgroup.netlify.app/#members-partners
https://deploy-preview-442--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, thanks!

**Comment by linkfang** [comment]
NP! The change is live!
