### ISSUE TITLE
OpenHW TV S03/E04  to be added to OpenHW TV webpage

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#444]
add to OpenHW TV 

OpenHW TV S03/E04  
What’s Behind the Infrastructure of the CORE-V Family
 
Automated code validation, continuous integration and test regression are cornerstones of OpenHW Group's community-based engineering process to develop and verify high-quality processor cores. OpenHW Group is deploying a state-of-the-art Test Automation and Continuous Integration environment to achieve these objectives across our diverse projects, resulting in faster development cycles with increased quality. In this webinar, Florian Zaruba and Massimiliano (Max) Giacometti of the OpenHW Group staff will review OpenHW’s CI requirements and approaches. 

A critical component to highlight is the robust design equivalence checking solution, which ensures that only the expected changes have been implemented at check-in points and no downstream functional bugs are introduced across logical Boolean, low power intent, and clock/reset domain contexts. David Stratman, Product Management Director at Cadence Design Systems, will discuss the Cadence Conformal suite of tools anchored by their Logical Equivalence Checking (LEC) solution. 

Rick O'Connor of OpenHW Group will be moderating the discussion.

YouTube Link: https://youtu.be/-KUrfYI6jkk 
 
Youku: https://v.youku.com/v_show/id_XNTg2NTM5NjY2OA==.html

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the new video here:
https://deploy-preview-445--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by michelleclancy** [comment]
perfect great.. approved
