### ISSUE TITLE
update to news posting request on OpenHW Group

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#451]
after hitting send in the submit news, I noticed there was a typo.  Title should be 

OpenHW Group Expands Global Footprint by Adding Regional Working Groups in Europe and Asia to Foster a Worldwide, Unified Open Hardware Ecosystem

ECOSYSTEM was missing an M

**Comment by shanda-eclipse** [comment]
Updated, but page is still in moderation with the content team.
