### ISSUE TITLE
OpenHW TV S03/E05 – Verification Strategies for the CORE-V-MCU: Past, Present and Future

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#461]
please add this to OpenHW TV on the website 
 
This episode of OpenHW TV will focus on the verification of the CORE-V-MCU currently under development by the OpenHW Group. Followers of OpenHW TV may recall that the CORE-V-MCU started out its life as the Arnold device (https://bit.ly/3PrfMCb) from the PULP-Platform team at ETH Zürich. Arnold has been successfully implemented in silicon, so a reasonable question is: “Why does the CORE-V-MCU need more verification?"  

The answer to this question lies in the goals of the CORE-V-MCU which are to enable rapid deployment of hardware and software development kits and to accelerate the design of commercial SoC devices based on CV32E40P.

Enabling hardware and software dev-kits calls for an accelerated development cycle that puts an SoC (ASIC) implementation of CORE-V-MCU into developers hands as soon as possible. To support this goal, a verification project that employs processor-driven testing is being used. This has enabled rapid deployment of a set of simple C test-programs called “cli-test”, running under FreeRTOS.

To support developers of commercial grade SoC devices requires the same level of verification that has previously been deployed on the CV32E40P core. The CORE-V-MCU-VERIF project aims to deploy a complete UVM verification environment that is capable of fully verifying the MCU as well as future commercial SoC devices based on CV32E4 cores.

This presentation will be led by:

Mike Thompson, OpenHW Group Director of Engineering, Verification Task Group
Tim Saxe, CTO of QuickLogic
David Poulin, President of Datum Technology Corporation

Mike will (briefly) re-introduce the CORE-V-MCU before handing the discussion over to Tim, who will summarize the goals of the first SoC device based on the CORE-V-MCU, and David, who will introduce a project to fully verify CORE-V-MCU with an "industrial grade" UVM verification environment.
 
YouTube Link:
 
https://youtu.be/xKzsK87gMEU 
 
Youku Link:
 
https://v.youku.com/v_show/id_XNTg3NDUwNzY3Mg==.html
 
 
--

**Comment by linkfang** [comment]
Hi @michelleclancy , please preview the update here:
https://deploy-preview-462--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/

**Comment by michelleclancy** [comment]
Please delete this at the end: 
This presentation will be led by:
Mike Thompson, OpenHW Group Director of Engineering, Verification Task Group Tim Saxe, CTO of QuickLogic David Poulin, President of Datum Technology Corporation

Mike will (briefly) re-introduce the CORE-V-MCU before handing the discussion over to Tim, who will summarize the goals of the first SoC device based on the CORE-V-MCU, and David, who will introduce a project to fully verify CORE-V-MCU with an “industrial grade” UVM verification environment.

REPLACE WITH THIS AT THE END: 
The presentation is lead by Mike Thompson, OpenHW Group Director of Engineering.  Joining Mike are members of the Verification Task Group, Tim Saxe, CTO of QuickLogic David Poulin, President of Datum Technology Corporation

**Comment by michelleclancy** [comment]
looks good, just need a "." period at the end of last paragraph.. approved to go live after that.
thank you

**Comment by linkfang** [comment]
NP, the change is now live!
