### ISSUE TITLE
OpenHW CORE-V MCU Press Release

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/openhwgroup.org#465]
I am creating this issue on behalf of @michelleclancy .

We need to post the following PR on the website before the end of the day. Let's create the page this morning so that we can get approval before EOD.

https://docs.google.com/document/d/1nlsSlPUaJu_KEV0m2G-M6iRQNgAEr_eb/edit

**Comment by ZacharySabourin** [comment]
Hey @shanda-eclipse! [Here is the requested page:](https://deploy-preview-466--eclipsefdn-openhwgroup.netlify.app/news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/)

**Comment by chrisguindon** [comment]
@shanda-eclipse Just to clarify, the URL that @ZacharySabourin is sharing is the netlifyt preview URL.

https://deploy-preview-466--eclipsefdn-openhwgroup.netlify.app/news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/  

SHOULD BECOME 

https://www.openhwgroup.org//news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/  

When https://github.com/openhwgroup/openhwgroup.org/pull/466 is merged...

**Comment by shanda-eclipse** [comment]
This has been added to the newsroom and scheduled for 2:45 AM ET: https://newsroom.eclipse.org/news/announcements/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-iot-built-open

Note that I used the [link Chris provided,](https://www.openhwgroup.org//news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/) so we will need to double check that is live by EOD.

**Comment by shanda-eclipse** [comment]
> Hey @shanda-eclipse! [Here is the requested page](https://deploy-preview-466--eclipsefdn-openhwgroup.netlify.app/news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/)

I think you already got approval on the merge request, but you have my +1 if you need it.

**Comment by michelleclancy** [comment]
﻿Thank you


From: Shanda Giacomoni ***@***.***>
Reply-To: "openhwgroup/openhwgroup.org" ***@***.***>
Date: Monday, June 20, 2022 at 12:45 PM
To: "openhwgroup/openhwgroup.org" ***@***.***>
Cc: michelleclancy ***@***.***>, Mention ***@***.***>
Subject: Re: [openhwgroup/openhwgroup.org] OpenHW CORE-V MCU Press Release (Issue #465)


This has been added to the newsroom and scheduled for 2:45 AM ET: https://newsroom.eclipse.org/news/announcements/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-iot-built-open

Note that I used the link Chris provided,<https://www.openhwgroup.org/news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/> so we will need to double check that is live by EOD.

**Comment by chrisguindon** [comment]
The page is now live: https://www.openhwgroup.org/news/2022/06/20/openhw-group-announces-risc-v-based-core-v-mcu-development-kit-for-iot-built-with-open-source-hardware-software/
