### ISSUE TITLE
PRess release: CV32E40P Core From OpenHW Group Sets the RISC-V Quality Standard For Open-Source Hardware IP

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#468]
below please find a press release to be posted on the OpenHW Website under News for one of our members who is sending this out to coordinate with the launch scheduled for June 21 
thank you,
Michelle

CV32E40P Core From OpenHW Group Sets the RISC-V Quality Standard For Open-Source Hardware IP
Quality goals achieved with functional verification through member collaboration in the OpenHW verification working group using leading commercial tools and RVVI methodology

Oxford, United Kingdom, June 21, 2022 — [Imperas Software Ltd.](http://www.imperas.com/), the leader in RISC-V simulation solutions, congratulates the OpenHW Group on the announcement of the [CORE-V MCU Dev/Kit](https://www.openhwgroup.org/) project based on the high-quality CV32E40P open-source processor IP core, the first core to be fully verified within the OpenHW CORE-V family. This marks the first of many projects based on the CV32E40P, which was verified using the Imperas RISC-V golden reference model, now in development both within open-source community projects and commercial designs. Imperas is a founding member of the OpenHW Group which was established with a clear objective to drive the adoption of open-source hardware by delivering quality IP cores based on industrial strength verification and compatibility with the established commercial EDA design tools and flows. The use of the Imperas lock-step-compare methodology for the verification of the CV32E40P now sets the standard for quality verification for RISC-V processor cores, not just open-source IP.

As an open standard ISA (Instruction Set Architecture) RISC-V is a natural option for open-source hardware projects. The RISC-V specifications are based on a modular framework with many standard extensions, each with significant options and configuration flexibility. All the design flexibility of RISC-V increases the requirements for extensive verification plans, including full dynamic operations with asynchronous events and debug modes of operation. The OpenHW Verification Task Group set up the CORE-V-VERIF verification testbench to verify not just the core, but with built-in flexibility to accommodate future adopters as they extend the base core features and thus the associated test requirements.

To help leverage the investment in verification IP and test infrastructure, the new open standard RVVI (RISC-V Verification Interface) has been adopted for OpenHW CORE-V projects to support the roadmap of IP cores. RVVI provides a common methodology for the key components of the testbench to connect the RTL instruction trace and reference models to fully support the lock-step-compare comparisons. The RVVI flexibility supports the full range of RISC-V specifications and features and can be adopted with increasing levels of complexity for designs with privilege modes, vector extensions, out-of-order pipelines, multi-threading, multi-hart, plus user-defined custom instructions and extensions. RVVI supports the innovation of RISC-V with the flexibility required for verification IP and reuse as DV teams scale up to support the rapid growth in RISC-V verification projects.

“The open RISC-V ISA specification is an excellent starting point and open-source processor IP cores, such as the CORE-V family, have real potential to change the industry,” said Rick O’Connor, President & CEO OpenHW Group. “The high-quality open-source CORE-V CV32E40P core now allows the broadest participation in the RISC-V revolution, the OpenHW MCU Dev/Kit project is just one example of the innovations that can now be developed from the quality foundation provided by the CV32E40P core, having been verified the CORE-V-VERIF testbench which leverages the Imperas RISC-V golden reference model.”

“OpenHW is determined to provide high-quality open-source hardware IP compatible with the established EDA tools and flows for adoption in commercial designs,” said Simon Davidmann, CEO at Imperas Software Ltd. “The CV32E40P as the first IP core to be completed in the CORE-V-VERIF flow marks not just the completion of a project, but the start of the era when open-source cores can be adopted in commercial designs without compromise. Research may well drive some aspects of innovation, but quality verification drives adoption.”

Availability
The free riscvOVPsimCOREV simulator supports the entire family of OpenHW CORE-V processors and platforms configured as an ISS (Instruction Set Simulator) with a programmers view of the key hardware features to support software development. riscvOVPsimCOREV is available on GitHub at https://github.com/openhwgroup/riscv-ovpsim-corev

The open standard RVVI (RISC-V Verification Interface) offers adaptability and verification IP reuse for the expanding community of developers undertaking processor verification, the open specification is available on GitHub at https://github.com/riscv-verification/RVVI

The free riscvOVPsimPlus package, including the Imperas RISC-V Reference Model, latest test suites, and instruction coverage analysis, including updates for the latest RISC-V ratified specifications is now available on OVPworld at [www.ovpworld.org/riscvOVPsimPlus](https://www.ovpworld.org/riscvOVPsimPlus). 

The ImperasDV RISC-V processor verification technology is already in active use with many leading customers, some of which have working silicon prototypes and are now working on 2nd generation designs. These customers, partners, and users span the breadth of RISC-V adopters from open source to commercial; research to industrial; microcontrollers to high-performance computing. A select sample of these include - Codasip, EM Microelectronics (Swatch), NSITEXE (Denso), Nvidia Networking (Mellanox), OpenHW Group, MIPS Technology, Seagate Technology, Silicon Labs, and Valtrix Systems, plus many others yet to be made public.

ImperasDV is available now, more details are available at [Imperas.com/ImperasDV](https://www.imperas.com/ImperasDV).

Imperas at Embedded World 2022 and Design Automation Conference 2022 (DAC 59)
Imperas will participate at the Embedded World Conference, June 21-23 in Nuremberg Germany, and also DAC, July 10-14 in San Francisco, California. Please stop by and see the latest developments for RISC-V Verification. For more details on all the panels, presentations, and talks, or to request a demo please visit [www.imperas.com/industry-events](https://www.imperas.com/industry-events).

About Imperas
Imperas is the leading provider of RISC-V processor models, hardware design verification solutions, and virtual prototypes for software simulation. Imperas, along with Open Virtual Platforms (OVP), promotes open source model availability for a spectrum of processors, IP vendors, CPU architectures, system IP, and reference platform models of processors and systems ranging from simple single core bare metal platforms to full heterogeneous multi-core systems booting SMP Linux. All models are available from Imperas at [www.imperas.com](http://www.imperas.com/) and the [Open Virtual Platforms (OVP)](http://www.ovpworld.org/) website.

For more information about Imperas, please see [www.imperas.com](http://www.imperas.com/). Follow Imperas on [LinkedIn](https://www.linkedin.com/company/imperas), [Twitter](https://twitter.com/imperassoftware) @ImperasSoftware, and [YouTube](https://www.youtube.com/channel/UCm_KdSmGZlccboLWP7tgKxQ).

All trademarks or registered trademarks are the property of Imperas Software Limited or their respective holders.

**Comment by chrisguindon** [comment]
@michelleclancy Are you expecting us to create a page on the openhwgroup website with this content or do you want us to add an entry to the homepage with a link to this PR from the member's website?

//cc @shanda-eclipse

**Comment by michelleclancy** [comment]
@chrisguindon this should go under OpenHW news but under the CORE-V announcement, it's a supporting announcement to the launch   thank youl

**Comment by chrisguindon** [comment]
@michelleclancy Thanks for the clarification on the ordering for the homepage. @shanda-eclipse Should be able to manage the order by changing the post date to be before the CORE-V announcement,

Typically, for PRs like this, we usually link to the members website but from what I can understand from your request, you do not want to do that. Instead you would like us to create a new page under the openhwgroup website for this content.

Is that correct?

**Comment by michelleclancy** [comment]
@shanda-eclipse yes that would work. thank you

**Comment by shanda-eclipse** [comment]
I've added this to the newsroom. You should see it in 10-15 min. 

If other supporting article come in, you can submit them through the newsroom: https://newsroom.eclipse.org/node/add/news

**Comment by chrisguindon** [comment]
@shanda-eclipse I can the posting but the order is not what @michelleclancy was asking. I believe she wants this post to show below the OpenHWGroup PR.

**Comment by chrisguindon** [comment]
You are right. My bad. I was looking at https://newsroom.eclipse.org/ instead of https://www.openhwgroup.org/

Thanks @shanda-eclipse
