### ISSUE TITLE
Thales testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#47]
please add...

**Marko Erman, Chief Technology Officer, Thales**
“Thales, as a dedicated supporter of the open source community through both the RISC-V and Eclipse Foundations, is proud to support the development of the OpenHW Group CORE-V Family of open-source RISC-V based cores. This is a major step to bring safety and security properties in open hardware solutions.”

**Comment by ericpoirier** [comment]
I just merged a patch which adds this item to the site. We should see it in a few minutes after the site is done rebuilding.
