### ISSUE TITLE
Add http://downloads.openhwgroup.org/ to resource menu

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#472]
Please add "OpenHW Downloads" under the resources menu with the URL http://downloads.openhwgroup.org/
thanks!

**Comment by ZacharySabourin** [comment]
Hey @DBees! The changes should be available for preview here: https://deploy-preview-479--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZacharySabourin** [comment]
Hey @DBees! Just making sure this issue is still on your radar :)

**Comment by DBees** [comment]
Looks good @ZacharySabourin
