### ISSUE TITLE
Add to OpenHW TV.  S03/E06  OpenHW Group's CORE-V Processor Lineup: Asia-Focused Seminar

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#477]
OpenHW Group is the leading global organization developing fully open-source and industry-ready RISC-V IP. Our membership spans the globe and has increasing membership within the Asia region. This seminar will introduce OpenHW Group and the objectives of OpenHW Group Asia, our Asia-focused working group. We will feature talks on CORE-V processor roadmaps, verification approaches, and software support for CORE-V cores. Please join us for this informative seminar! 

Participants include Duncan Bees, Davide Schiavone and Mike Thompson from the OpenHW Group Staff, along with Wei Wu, IS-CAS, and Kan Shi, ICT-CAS.
 
YouTube Link:
 
https://youtu.be/if4kzMU1z8A 
 
Youku Link:
 
https://v.youku.com/v_show/id_XNTg4MjcwMDIwNA==.html

**Comment by ZacharySabourin** [comment]
@michelleclancy NP! 
Without accepted cookies, we retrieve the best efforts thumbnail which may not always be present from YouTube. Once cookies are accepted we can fetch actual thumbnails and get an accurate thumbnail. We are going to look into this and see if we can improve this, but accepting cookies should help!

**Comment by chrisguindon** [comment]
@michelleclancy I just merged in a PR that should fix the thumbnail: https://github.com/openhwgroup/openhwgroup.org/pull/482

This should go live any minute now!

Closing this issue! Thanks @ZacharySabourin
