### ISSUE TITLE
Remove AB Open from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#478]
AB Open's membership has been terminated effective immediately. Kindly remove their logo from the OpenHW Group website https://www.openhwgroup.org/ 
https://www.openhwgroup.org/membership/members/

**Comment by ZacharySabourin** [comment]
Hey @ZahraFazli! The changes should be available for preview here: https://deploy-preview-481--eclipsefdn-openhwgroup.netlify.app/

and here: https://deploy-preview-481--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZacharySabourin** [comment]
Hey @ZahraFazli! Just making sure this is still on your radar :)

**Comment by ZahraFazli** [comment]
Looks good, Thanks!
