### ISSUE TITLE
Mythic testimonial

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#48]
please add...

**Ty Garibay, VP Engineering, Mythic AI**
“Mythic relies on the ability to customize processor cores to optimize our system performance.  RISC-V based cores have therefore become a critical component of our novel AI inference processor architecture. We look forward to working with the OpenHW Group to develop the CORE-V Family of open-source RISC-V cores that will meet the growing demands of our products, including vital eco-system support, tools and friendly licensing alternatives.”

**Comment by ericpoirier** [comment]
I just merged a patch which adds this item to the site. We should see it in a few minutes after the site is done rebuilding.
