### ISSUE TITLE
OpenHW TV episode submitted to news page

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#488]
Hi, I've submitted the next episode of OpenHW TV to the news page for posting. Can we post the Date?  August 25 @ 11:00 EDT
thanks

**Comment by ZacharySabourin** [comment]
@michelleclancy Can you provide me with content for the page, as well as any videos required? Thanks!

**Comment by michelleclancy** [comment]
this is to promote the next episode under news - there is no video yet. 
thanks
Michelle

OpenHW TV - S03/E07 On the Road at Embedded World: The New CORE-V MCU DevKit
 
Did you miss out on Embedded World in Nuremburg, Germany in June? This episode of OpenHW TV will give you another chance to view OpenHW Group's live presentation and hear all of the details on the new CORE-V MCU DevKit! OpenHW Group and its members announced one of the industry’s most comprehensive open-source RISC-V Development Kits at Embedded World 2022. The CORE-V MCU DevKit features the OpenHW CORE-V MCU, the CORE-V software developer kit (SDK) with full-featured Eclipse-integrated development environment (IDE) and an open printed circuit board (PCB) design that supports AWS via AWS IoT ExpressLink. The ground-breaking RISC-V-based CORE-V MCU DevKit enables software development for embedded, internet-of-things (IoT), and artificial intelligence (AI)-driven applications.

Join Rick O’Connor, President of OpenHW Group, and Richard Barry, Senior Principal Engineer at AWS, for a live Q&A session at the end of the webinar.

Register: https://us02web.zoom.us/webinar/register/WN_otcGqCmGSzKAdMjDRQp7Zw

**Comment by ZacharySabourin** [comment]
@michelleclancy A preview of the requested changes is available here: https://deploy-preview-492--eclipsefdn-openhwgroup.netlify.app/news/2022/08/11/openhw-tv-s03-e07-on-the-road-at-embedded-world-the-new-core-v-mcu-devkit/

**Comment by chrisguindon** [comment]
I merged this!

@michelleclancy Let us know if you need us to make a change.
