### ISSUE TITLE
Add Silicon Assurance as member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#490]
Attached is the logo for Silicon Assurance. Please add the logo the membership webpages https://www.openhwgroup.org/ and https://www.openhwgroup.org/membership/members/
![silicon-assuarance-logo-2](https://user-images.githubusercontent.com/50374570/184190171-3dd1c0b6-dd33-44e8-a746-cbcb881389fa.png)

**Comment by autumnfound** [comment]
@oliviergoulet5 could you look at this since Zach is out? TIA!
