### ISSUE TITLE
Silver member benefits section incorrect

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#495]
It looks like the Silver Member description https://www.openhwgroup.org/membership/#tab-levels has been transposed with Eclipse Foundation Associate membership benefits. The correct wording for Silver Member is as follows (following the same formatting as Platinum and Gold):

Silver Member 
Silver members contribute to the development of OpenHW Group’s global ecosystem of open-source, industrial-quality processor IP, and can participate in and contribute to all technical activities and task groups. Silver Member benefits:

- Entitled to cast one vote on any matter presented to the Members (including the election of directors).
- Employees are entitled to join and make technical contributions to all OpenHW Group technical committees and projects.
- Entitled through their OpenHW Group and Eclipse Foundation memberships to join the OpenHW Asia and OpenHW Europe Working Groups.
- Receive a complementary Eclipse Foundation Contributing Membership

**Comment by oliviergoulet5** [comment]
@DBees Here is a preview link with the changes: https://deploy-preview-498--eclipsefdn-openhwgroup.netlify.app/membership/#tab-fees

Let me know if it's ready to go live!

**Comment by DBees** [comment]
Perfect
