### ISSUE TITLE
Add Codasip to OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#497]
Attached, please find Codasip's logo and URL. They have recently joined OpenHW Group as members. 
URL: https://codasip.com/
![Logotype-Full_SAFE-Blue](https://user-images.githubusercontent.com/50374570/186437545-95fbd138-7976-437c-aa9c-cc6274a7fe31.png)

**Comment by ZacharySabourin** [comment]
Hey, @ZahraFazli! Here is a preview of the available changes: https://deploy-preview-500--eclipsefdn-openhwgroup.netlify.app/

**Comment by ZahraFazli** [comment]
+1 Thanks
