### ISSUE TITLE
testimonial sort order

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#50]
Rob Oshana
Alessandro Piovaccari
Xiaoning Qi
Charlie Hauck
Luca Benini
Gord Harling
Ian Loveless
Simon Davidmann
Loic Letar
Doug Letcher
Ty Garibay
Raik Brinkmann
Marko Erman
Mike Milinkovich
Philipp Wagner
Dave Patterson
Calista Redmond

**Comment by ericpoirier** [comment]
I reordered the testimonials on the front page.
