### ISSUE TITLE
Link to Membership Contact Form

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#501]
The link text in Step 1 should read 'Membership Contact Form' and not 'Membership Application Form'.  The linked url and PDF filename are both correct.  Its just the Step 1 link text that needs to be fixed.
https://www.openhwgroup.org/membership/#tab-membership

**Comment by ZacharySabourin** [comment]
Hey @rickoco! Here is the preview of the requested change: https://deploy-preview-502--eclipsefdn-openhwgroup.netlify.app/membership/#tab-membership

**Comment by rickoco** [comment]
ready to go - thx @ZacharySabourin

**Comment by rickoco** [comment]
@ZacharySabourin is this being pushed live?
