### ISSUE TITLE
OpenHW Group Blog for posting

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#503]
can we please post this blog on the OpenHW website under the blog page and also on the News Page.  It would be great if we can get this posted by Thursday September 1. 
[Intel Pathfinder OpenHW blog final.docx](https://github.com/openhwgroup/openhwgroup.org/files/9455074/Intel.Pathfinder.OpenHW.blog.final.docx)

**Comment by rickoco** [comment]
Actually pls use the text below.  Small tweak...

The Professional Edition of Intel® Pathfinder for RISC-V is available free of charge (subject to Intel approval) to all OpenHW Group member organizations. Start your journey with Intel® Pathfinder for RISC-V at [pathf](https://pathfinder.intel.com/)

**Comment by rickoco** [comment]
@autumnfound @oliviergoulet5 is this being worked on?  We'd like it to go live today.

**Comment by michelleclancy** [comment]
@autumnfound @oliviergoulet5   please let us know when the blog is live and on the news page.  We will need to get it out on social and also let Intel know the blog is live.  thanks!

**Comment by oliviergoulet5** [comment]
Sorry for the delay everyone!

Here is a preview link of the blog post: https://deploy-preview-508--eclipsefdn-openhwgroup.netlify.app/resources/blog/intel-pathfinder-for-risc-v-launch-bolstered-by-openhw-group-core-v-family-open-source-cores/

Who am I putting down as the author?

**Comment by autumnfound** [comment]
@shanda-eclipse @michelleclancy the [article](https://www.openhwgroup.org/resources/blog/intel-pathfinder-for-risc-v-launch-bolstered-by-openhw-group-core-v-family-open-source-cores/) is now live. All that's left is for one of you two to add the node and go through the normal publishing steps for news room and the item should appear in the news list https://newsroom.eclipse.org/node/add/news

**Comment by oliviergoulet5** [comment]
I can publish it to make it go faster.

**Comment by oliviergoulet5** [comment]
@rickoco The blog post now appears on the homepage.

**Comment by rickoco** [comment]
Thx @oliviergoulet5 for getting this up today.  I just noticed the logos are not in the blog post.  Please add them at the top of the blog, on the same line / row, spaced appropriately.

![04-Intel Classis Blue  Energy Spark PathFinder for RISC-V Stacked Logo](https://user-images.githubusercontent.com/2498391/188004253-4d545501-57ed-4c5f-a8fe-c981b11f5ba2.png)

linked to url https://pathfinder.intel.com/

![CORE-V-landscape®](https://user-images.githubusercontent.com/2498391/188004374-ffb0fc6e-76d6-47d8-b845-9ec6c4489ca5.png)

linked to url https://github.com/openhwgroup/core-v-cores

**Comment by rickoco** [comment]
@oliviergoulet5  re-opening for logo comment above

**Comment by oliviergoulet5** [comment]
https://deploy-preview-509--eclipsefdn-openhwgroup.netlify.app/resources/blog/intel-pathfinder-for-risc-v-launch-bolstered-by-openhw-group-core-v-family-open-source-cores/

Logos have been added @rickoco

**Comment by rickoco** [comment]
Thx @oliviergoulet5 - pls deploy
