### ISSUE TITLE
Add AMD/Xilinx as partner

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#504]
Please add AMD/Xilinx as a Partner and link to the following url https://www.amd.com/en/products/xilinx

![21928600-A_AMD_Xilinx_Lockup_RGB_BLK](https://user-images.githubusercontent.com/2498391/187528400-dd46d543-4ab4-4a5c-8383-6ff3b8e12019.png)

**Comment by ZacharySabourin** [comment]
@rickoco Here is a preview of the changes for this issue and for https://github.com/openhwgroup/openhwgroup.org/issues/505

https://deploy-preview-506--eclipsefdn-openhwgroup.netlify.app/

**Comment by rickoco** [comment]
Thx @ZacharySabourin - you actually had AMD / AWS order correct the first time :-)

AMD is Advanced Micro Devices, so AMD comes first in an alpha sort.

**Comment by ZacharySabourin** [comment]
@rickoco I've updated the order. Let me know if you need me to tweak anything else

**Comment by rickoco** [comment]
looks good @ZacharySabourin thank you.  Please deploy.
