### ISSUE TITLE
Add Intel as a Partner

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#505]
Add Intel as a Partner and link to the following URL https://pathfinder.intel.com/
![Intel-logo](https://user-images.githubusercontent.com/2498391/187530139-48697f04-135d-4687-979c-a3a0b1664e07.png)

**Comment by ZacharySabourin** [comment]
@rickoco Here is a preview of the changes for this issue and for https://github.com/openhwgroup/openhwgroup.org/issues/504

https://deploy-preview-506--eclipsefdn-openhwgroup.netlify.app/
