### ISSUE TITLE
Add Synopsys as Partner

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#507]
... and link to synopsys.com

<img width="229" alt="Synopsyslogo" src="https://user-images.githubusercontent.com/2498391/187698851-8f60a830-fccb-49dc-884a-17fecbf80fa1.png">

**Comment by ZacharySabourin** [comment]
@rickoco I've added Synopsys to the same preview as Intel and AMD/Xilinx: https://deploy-preview-506--eclipsefdn-openhwgroup.netlify.app/
