### ISSUE TITLE
Add MU Electronics' logo as a member for OpenHW Group

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#510]
Please add the attached logo for MU Electronics on OpenHW Group website: https://www.openhwgroup.org/membership/members/
https://www.openhwgroup.org/

URL: https://www.mu-e.com/
![LOGO-MU-ELECTRONICS](https://user-images.githubusercontent.com/50374570/189171233-4047245a-c3f9-46b9-9ef1-773dd1b699d4.png)

**Comment by oliviergoulet5** [comment]
Hey @ZahraFazli 

Here are the links to the preview:
- https://deploy-preview-511--eclipsefdn-openhwgroup.netlify.app/
- https://deploy-preview-511--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, 
Thanks

**Comment by oliviergoulet5** [comment]
MU Electronics should now appear on the site.
