### ISSUE TITLE
Add Harvey Mudd College's logo on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#512]
Please add the attached logo to the OpenHW Group website: https://www.openhwgroup.org/ https://www.openhwgroup.org/membership/members/

URL: https://www.hmc.edu/
![HMC BGW RGB 150dpi](https://user-images.githubusercontent.com/50374570/189394601-91ce599e-6292-48e3-aed9-5f08c225f0da.png)

**Comment by oliviergoulet5** [comment]
Hey @ZahraFazli 

Here is the logo: 

https://deploy-preview-513--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-513--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, thanks!
