### ISSUE TITLE
Add Oklahoma State University's logo to the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#514]
Please add the attached logo to the OpenHW Group website: https://www.openhwgroup.org/ https://www.openhwgroup.org/membership/members/

URL:  https://go.okstate.edu/
![osu-nomenclature](https://user-images.githubusercontent.com/50374570/189998089-c7e0a2da-2426-4a28-b6e3-8167e46e1a00.png)

**Comment by ZacharySabourin** [comment]
Hey @ZahraFazli! You can preview the requested changes here: https://deploy-preview-515--eclipsefdn-openhwgroup.netlify.app/#members-partners

and here: https://deploy-preview-515--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
+1 Thanks
