### ISSUE TITLE
Add PlanV GmbH to the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#516]
Please add the attached logo as members on the OpenHW Group website https://www.openhwgroup.org/membership/members/
https://www.openhwgroup.org/

URL: https://planv.tech/
![planv_logo](https://user-images.githubusercontent.com/50374570/190675853-aaad7af3-11e8-4c1b-a0e4-4cd03ecf1995.png)

**Comment by oliviergoulet5** [comment]
Hey @ZahraFazli 

Here are preview links with the change: 
https://deploy-preview-517--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-517--eclipsefdn-openhwgroup.netlify.app/membership/members

**Comment by oliviergoulet5** [comment]
PlanV has been added to production. Closing the issue now.
