### ISSUE TITLE
Add Cryptoquantique's logo to the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#518]
Attached, please find Cryptoquantique 's logo to be added to the OpenHW Group website: https://www.openhwgroup.org/
https://www.openhwgroup.org/membership/members/

URL: https://www.cryptoquantique.com/
![CQ_LogoV1(Purple)](https://user-images.githubusercontent.com/50374570/193100656-3f5cdcbf-f96a-4b29-bb46-21478ffc8fa7.png)

**Comment by oliviergoulet5** [comment]
Hey @ZahraFazli , here are the links with the changes:

- https://deploy-preview-519--eclipsefdn-openhwgroup.netlify.app/
- https://deploy-preview-519--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, thanks
