### ISSUE TITLE
OpenHW TV S03/E07 – On the Road at Embedded World: The New CORE-V MCU DevKit

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#521]
Please add to the OpenHW TV website page - 
 
OpenHW TV S03/E07 – On the Road at Embedded World: The New CORE-V MCU DevKit
 
Abstract:
 
Did you miss out on Embedded World in Nuremburg, Germany in June? This episode of OpenHW TV will give you another chance to view OpenHW Group's live presentation and hear all of the details on the new CORE-V MCU DevKit! OpenHW Group and its members announced one of the industry’s most comprehensive open-source RISC-V Development Kits at Embedded World 2022. The CORE-V MCU DevKit features the OpenHW CORE-V MCU, the CORE-V software developer kit (SDK) with full-featured Eclipse-integrated development environment (IDE) and an open printed circuit board (PCB) design that supports AWS via AWS IoT ExpressLink. The ground-breaking RISC-V-based CORE-V MCU DevKit enables software development for embedded, internet-of-things (IoT), and artificial intelligence (AI)-driven applications.

Join Rick O’Connor, President of OpenHW Group, and Richard Barry, Senior Principal Engineer at AWS, for a live Q&A session at the end of the webinar.
 
YouTube Link:
 
https://youtu.be/ADD2PL2w5nM
 
Youku Link:
 
https://v.youku.com/v_show/id_XNTg5ODQ1NDE2OA==.html

**Comment by ZacharySabourin** [comment]
@michelleclancy Here is a preview of the requested changes: https://deploy-preview-522--eclipsefdn-openhwgroup.netlify.app/resources/openhwtv/
