### ISSUE TITLE
Mock up member logo page for Intel approval 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#523]
We need to add the Intel logo to the OpenHW Group member page, although Intel has guidelines that need to be followed for their internal approval of logo usage.   
 
From Intel: as part of our logo usage approval process we need to have the attached logo and build out a temporary version of the members logo page and send it back to us so our internal team can approve the logo usage.
 
https://www.openhwgroup.org/membership/members/
 
![intel-logo-ub-RGB_PL-Energy-low-res](https://user-images.githubusercontent.com/88848029/194137400-59fbed1e-c339-4f4d-abfa-fb1dd12e4b5c.png)

**Comment by oliviergoulet5** [comment]
@michelleclancy Here are some links with the FPO logo: 
- https://deploy-preview-530--eclipsefdn-openhwgroup.netlify.app/
- https://deploy-preview-530--eclipsefdn-openhwgroup.netlify.app/membership/members/

Just to be sure, we are not merging this PR right?

**Comment by michelleclancy** [comment]
@oliviergoulet5 correct, we need to get their internal approval before we post any intel logo.  Thank you for the mock ups. i'll send this over now

**Comment by ericpoirier** [comment]
@michelleclancy, any news to get this issue moving?

**Comment by rickoco** [comment]
@michelleclancy is out, so replying on her behalf.  Yes, @ericpoirier this has been approved by Intel.  Assuming you have the logo you need, please publish.

**Comment by rickoco** [comment]
Yes @ericpoirier - that is the one although it looks low res...

**Comment by ericpoirier** [comment]
> Yes @ericpoirier - that is the one although it looks low res...

@rickoco I think for what we need here, the low res is good enough so we'll start with that but you can provide a larger image if you think it's needed.

**Comment by michelleclancy** [comment]
@ericpoirier I have a call with the Intel marketing person early next week and will get a new logo file for the website and other material as needed

**Comment by ericpoirier** [comment]
> @rickoco @ericpoirier I have a call with the Intel marketing person early next week and will get a new logo file for the website and other material as needed

@michelleclancy Ok thx, will put this issue on hold until then.

**Comment by michelleclancy** [comment]
@ericpoirier @rickoco  here is the logo for Intel. If you need an EPS please let me know as I have two file formats.
![logo-classicblue-3000px](https://user-images.githubusercontent.com/88848029/197264426-35a3d5af-915f-413b-833b-ceabb16b5dc0.png)

**Comment by ericpoirier** [comment]
> @ericpoirier @rickoco here is the logo for Intel. If you need an EPS please let me know as I have two file formats. ![logo-classicblue-3000px](https://user-images.githubusercontent.com/88848029/197264426-35a3d5af-915f-413b-833b-ceabb16b5dc0.png)

@michelleclancy Thanks!

**Comment by oliviergoulet5** [comment]
@michelleclancy Here is a preview: 

https://deploy-preview-530--eclipsefdn-openhwgroup.netlify.app/
https://deploy-preview-530--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by michelleclancy** [comment]
@oliviergoulet5 this is approved. Thank you Michelle
