### ISSUE TITLE
Update Working Group Page

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#524]
https://www.openhwgroup.org/working-groups/
(1) Technical Working Group 

Jerome should be listed as Co-Chair

Additional Co-Chair:
David Lynch, CMC
https://www.linkedin.com/in/david-lynch-3514474/

(2) Verification TG chairs should be

Chair: Simon Davidmann, Imperas
https://www.linkedin.com/in/simon-davidmann-57656b143/

Vice-Chair: Jean-Roch Coulon, Thales 
https://www.linkedin.com/in/jeanrochcoulon/?originalSubdomain=fr

**Comment by oliviergoulet5** [comment]
Here is a link of the changes: https://deploy-preview-529--eclipsefdn-openhwgroup.netlify.app/working-groups

**Comment by DBees** [comment]
perfect, thanks!
