### ISSUE TITLE
Move Intel's logo from Partner's section to Member's section

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#525]
Intel has joined OpenHW Group as a Silver Member. Please remove the logo from the Partner's section (https://www.openhwgroup.org/membership/members/) to Member's section (https://www.openhwgroup.org/membership/members/ https://www.openhwgroup.org/)

Thank you!

**Comment by ZahraFazli** [comment]
Looks good! Thanks

**Comment by oliviergoulet5** [comment]
The changes are live!
