### ISSUE TITLE
Update dashboard reference please (broken link)

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#526]
The dashboard pointer under the resources menu at 
https://www.openhwgroup.org/

should point to this file
https://github.com/openhwgroup/core-v-docs/blob/master/program/dashboard/Dashboard_SpreadSheetFriendly.md

**Comment by oliviergoulet5** [comment]
I updated the dashboard link to point to the specified file. Please check the preview https://deploy-preview-527--eclipsefdn-openhwgroup.netlify.app/

**Comment by DBees** [comment]
Yes please go live, thank you Olivier
Duncan
