### ISSUE TITLE
Another broken link

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#536]
The "project descriptions and plans" link from the Resources menu should be:
https://github.com/openhwgroup/programs/tree/master/Project-Descriptions-and-Plans

instead of:
https://github.com/openhwgroup/programs/tree/master/program/Project-Descriptions-and-Plans

thank you
Duncan

**Comment by oliviergoulet5** [comment]
Hey @DBees,

Here is a preview: https://deploy-preview-537--eclipsefdn-openhwgroup.netlify.app/

**Comment by DBees** [comment]
looks good, thanks
