### ISSUE TITLE
Changes to "Become a Member"

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#539]
Under Become a Member at https://www.openhwgroup.org/membership/#tab-membership

Step 1. The document referred to is now the "Membership Information Form".  This form is being updated by @ZahraFazli as part of completion of https://github.com/openhwgroup/openhwgroup.org/issues/491. When that new form is finalized please change the link text here accordingly. 

Step 3. The text should say:  For Platinum, Gold and Silver level memberships, complete and sign the [Member Committer and Contributor Agreement](https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf). This agreement is not required for Supporter level memberships. 

Step 4. The text should say: [Email us](mailto:membership@openhwgroup.org) the documents 1-3 above, as well as a full colour, vector based member logo on transparent background for our OpenHW member directory.

@ZahraFazli @rickoco please check this over.

**Comment by DBees** [comment]
@chrisguindon I take it this is ok, please go ahead now that 491 is complete

**Comment by ZahraFazli** [comment]
The Membership Information Form is still referred to as Member Contact Form under point 1. 
Its referred to as Membership Application Form under point 4. 
We need to standardize the form name to be Membership Information Form

**Comment by DBees** [comment]
@ZahraFazli the issue is raised to correct that. See above and let us know if you agree with the revised wording I proposed.

**Comment by DBees** [comment]
@chrisguindon @oliviergoulet5 please move ahead with this one, thanks

**Comment by oliviergoulet5** [comment]
Here is a preview link @DBees: https://deploy-preview-543--eclipsefdn-openhwgroup.netlify.app/membership/#tab-membership

**Comment by DBees** [comment]
This looks great. I noticed one additional thing that should be changed

"Once you have chosen the level of membership (e.g., Platinum, Gold, Silver, Supporter):"

should be replaced by

"Once you have chosen the level of membership (Platinum, Gold, Silver, or Supporter):"

**Comment by oliviergoulet5** [comment]
Updated!

**Comment by DBees** [comment]
Thank you, all looks good Olivier.
