### ISSUE TITLE
OpenHW European Working Group Job description for OpenHW Website 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#542]
hi,  We need to post the following job description for the OpenHW European Working Group. Not sure where to post on the website, open to suggestions  - Maybe on the European Working Group page? Maybe under Resources as a Careers or Job posting page? 

thanks, MIchelle

Statement of Work for OpenHW Europe WG
Tristan activities

Do you like open-source HW RISC-V CPUs?
...and even more, do you like to have HIGH-QUALITY, VERIFIED, open-source HW IPs?

If the answer is YES, and you want to help us build them, this job offer is for you.

We are looking for a Hardware Verification Engineer that extends our ecosystem.

You will:

** Use SystemVerilog and UVM to create and extend our testbenches: you should know how to verify IPs with random instructions
** Use GitHub to integrate and maintain everything open-source on GitHub under [core-v-verif](https://)
** Verify CPUs based on RISC-V
** Verify peripherals such as UART, SPI, GPIOs, interrupt controllers and interconnects
** Integrate and extend existing CPUs to support extra features
** Integrate and extend new co-processors
** Work fully remotely in a large and global team.

To accomplish the above missions, you should:

** Be very confident with SystemVerilog and UVM for use with coverage-driven, constrained-random verification strategies.
** A working knowledge of:
-- Linux, Make and Python.
-- Computer architectures of general-purpose CPUs
-- Peripheral busses, interrupt controllers and peripherals such as UART, SPI, GPIOs.
- A commercial SystemVerilog simulator and associated debug and coverage tools.
** Familiarity with Formal Verification, RTL design, RISC-V ISA and Git would also be an as

Qualifications:
** A Bachelor's degree (or higher) in EE or CS with 5+ years of experience
** You must be resident in European Union, in particular in Italy, France, or Germany.

**Comment by oliviergoulet5** [comment]
I could make a careers page, and a simple page displaying the individual job posting. But it would be important to know whether or not OpenHWGroup has a JazzHR like this: https://eclipsefoundation.applytojob.com/apply/. 

If not, how should the user apply? Is there a link you want to add to the page (email, or another webpage)?

**Comment by oliviergoulet5** [comment]
Hey @michelleclancy,

Here is a preview: https://deploy-preview-545--eclipsefdn-openhwgroup.netlify.app/careers/

This can work as a career page for all of the OpenHW working groups. 

The link to the careers page can be found in the footer... Let me know if this is a good place for it. I originally placed the link to the "resources" menu as you suggested but I'm finding this menu to be already crammed. 

How should the user contact for the job? Is there an email or form link you want me to add to the page?

**Comment by DBees** [comment]
Hi @oliviergoulet5 I think the careers page is a good initiative! Thank you for that. However, we won't likely often have a careers post so it may look empty in those times.  Accordingly, I would suggest that we put this one on the landing page under News and not use the careers page for now. 

That is, put this posting as the top item under the News Section

The news item text can be the first few lines, ie.

"Do you like open-source HW RISC-V CPUs?
...and even more, do you like to have HIGH-QUALITY, VERIFIED, open-source HW IPs?

If the answer is YES, and you want to help us build them, this job offer is for you.

We are looking for a Hardware Verification Engineer that extends our ecosystem

Click here for more details!
"


I would recommend to bold the Hardware Verification Engineer.

The link would pop up a page with the full text.

Does this make sense? Thankyou!

**Comment by DBees** [comment]
@oliviergoulet5 if possible please action this soon as I believe it is urgent to get this visible. Thanks D.

**Comment by rickoco** [comment]
@davideschiavone @michelleclancy @DBees - this has the outdated content.  Pls provide the current, updated job posting content for the web team.  Also, @oliviergoulet5 as @DBees suggests, this should be a blog post as we will have very infrequent career postings (no need for a careers page which will be empty most of the time).

**Comment by oliviergoulet5** [comment]
Here is a preview of what it would look like: https://preview-545--openhwgroup-org.eclipsecontent.org/

The job posting is now part of the blog. It will remain at the top of the homepage's blog post list until I remove it manually.

There's one trade-off with having it pinned at the top. I had to avoid publishing the blogpost to  [newsroom.eclipse.org](https://newsroom.eclipse.org/) unlike your other blog posts. Let me know if this would cause a problem.

**Comment by davideschiavone** [comment]
hi @oliviergoulet5 , please find the updated text here: https://docs.google.com/document/d/12FzxpZEA6ZdukfcCdfixGq7ebG41KHO6YekSbV22AlA/edit?usp=sharing

you should have view rights, let me know if you cannot access it

**Comment by oliviergoulet5** [comment]
Thanks @davideschiavone!

The page has been updated with the new content

**Comment by DBees** [comment]
@oliviergoulet5 @davideschiavone I will let Davide approve this. Looks ok to me. Duncan

**Comment by davideschiavone** [comment]
LGTM

**Comment by davideschiavone** [comment]
hi @oliviergoulet5 , I actually see PAGE NOT FOUND

https://www.openhwgroup.org/careers

**Comment by DBees** [comment]
@davideschiavone it is at www.openhwgroup.org under News
