### ISSUE TITLE
Add Universidade do Minho as a member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#544]
Please add the attached logo of Universidade do Minho
![UMinho-C](https://user-images.githubusercontent.com/50374570/204344280-9576c21e-9458-49dc-88a1-5f365d0ffa0a.png)
 on the website https://www.openhwgroup.org/ and https://www.openhwgroup.org/membership/members/

URL: https://www.uminho.pt/PT

**Comment by oliviergoulet5** [comment]
Hi @ZahraFazli 

Here is a preview: 
- https://deploy-preview-546--eclipsefdn-openhwgroup.netlify.app/
- https://deploy-preview-546--eclipsefdn-openhwgroup.netlify.app/membership/members/

**Comment by ZahraFazli** [comment]
LGTM
