### ISSUE TITLE
New blog post

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#548]
@chrisguindon - is it possible to get this blog post up on Wed Nov 30th?

https://docs.google.com/document/d/1_Z3uvOHcFoOH0VLsnose66buG7JWNHoXRsNWx3lvU8s/edit?usp=sharing

please use the following URL for the blog

https://www.openhwgroup.org/resources/blog/core-v-cva6-open-source-manycore-risc-v/

**Comment by chrisguindon** [comment]
@oliviergoulet5 Please prioritize this task. @rickoco and I would like to see this done today.

**Comment by oliviergoulet5** [comment]
@rickoco 

Here is the preview for the blog post: https://preview-549--openhwgroup-org.eclipsecontent.org/resources/blog/core-v-cva6-open-source-manycore-risc-v/

**Comment by rickoco** [comment]
@oliviergoulet5 - thanks for the quick turnaround!  Looks great.  Just one small change.  Pls use upper case for CORE-V in the figure text.

**Comment by oliviergoulet5** [comment]
I capitalized the CORE-V's. The page is now live!

**Comment by rickoco** [comment]
Great!  Thank you @oliviergoulet5 and @chrisguindon for such a quick response.  Can you please have the blog show in our News feed?  This should be the case for all blog posts so they show up on the front page.

**Comment by oliviergoulet5** [comment]
I submitted the blog post to the newsroom. I'll let you know when this is added.

**Comment by rickoco** [comment]
> NP! I submitted the blog post to the newsroom. I'll let you know when this is added.

Thank you @oliviergoulet5 - can this be automated so all blog posts are automatically in our news feed?

**Comment by oliviergoulet5** [comment]
@rickoco We can create an issue to discuss automating blog posts into the news widget.

**Comment by oliviergoulet5** [comment]
@rickoco It is now on the homepage

**Comment by rickoco** [comment]
Thx very much @oliviergoulet5 !!

Sorry for this but Intel has just asked us for another change as follows:

Can you please make a few minor edits:

Please add the registered trade mark to Intel and the asterisk with footnote: Intel® Pathfinder for RISC-V*

 
![image001](https://user-images.githubusercontent.com/2498391/204868120-9996df48-05b1-46c9-9d67-83fb610baede.png)


* Intel, the Intel logo, and other Intel marks are trademarks of Intel Corporation or its subsidiaries. Other names and brands may be claimed as the property of others.

**Comment by oliviergoulet5** [comment]
Here is a preview link for adding registered trademark: https://preview-552--openhwgroup-org.eclipsecontent.org/resources/blog/core-v-cva6-open-source-manycore-risc-v/

But shouldn't the "Intel" in "Intel FPGAs" also have one?
