### ISSUE TITLE
Remove listed members from the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#560]
Please remove the following members' logos from the website

1. YosysHQ GmbH
2. OPERSYS Inc.
3. C2MI

Thanks

**Comment by oliviergoulet5** [comment]
@ZahraFazli Here is a preview for these changes: https://preview-561--openhwgroup-org.eclipsecontent.org/membership/members/

Let me know if it is good to go live

**Comment by ZahraFazli** [comment]
Looks good
