### ISSUE TITLE
Security alert email from GitHub

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/openhwgroup.org#562]
Hello, from time to time I receive security advisory emails from GitHub on this repo.  An example is shown below.  To my uneducated eye this one looks serious.  Is there any action required, specifically any action from the OpenHW staff.
![image](https://user-images.githubusercontent.com/55248931/211569249-c71c947e-fb4c-41c7-911d-5d6d5fb0830b.png)

**Comment by oliviergoulet5** [comment]
@chrisguindon json5 is being used by @babel/core and loader-utils. Updating babel and loader-utils to a version which doesn't have the vulnerability seems to be the fix. See [EFSA's yarn.lock](https://github.com/EclipseFdn/solstice-assets/blob/master/yarn.lock)

For @babel/core, the latest release has the fix. [source](https://github.com/babel/babel/commit/6e9f7b77151654f59feee7b9bc6ecd420869edae)
