### ISSUE TITLE
Add Empaiot Pte. Ltd as member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#563]
Attached, please find the logo for Empaiot Pte. Ltd to be added under Members on the OpenHW Group website

@rickoco do you happen to have the URL of the company? I can't find them online 
![Empaiot logo2](https://user-images.githubusercontent.com/50374570/211916934-93804f43-efd2-4fa0-a1e1-32a569ebab54.png)

**Comment by ericpoirier** [comment]
Hi @ZahraFazli, there seems to be a lot of white space around the logo. Would it be possible to provide us with a logo without any white space? Otherwise it's going to look like there's a lot of padding around it.

Thanks.

**Comment by rickoco** [comment]
> Attached, please find the logo for Empaiot Pte. Ltd to be added under Members on the OpenHW Group website
> 
> @rickoco do you happen to have the URL of the company? I can't find them online ![Empaiot logo2](https://user-images.githubusercontent.com/50374570/211916934-93804f43-efd2-4fa0-a1e1-32a569ebab54.png)

@ZahraFazli - reach out to Alfred for their url

**Comment by rickoco** [comment]
@oliviergoulet5 - pls go ahead and publish without the url

we can update the listing once @ZahraFazli comes back with url details

**Comment by oliviergoulet5** [comment]
@rickoco Sounds good to me.

@ZahraFazli Here is the preview: 

- https://preview-568--openhwgroup-org.eclipsecontent.org/
- https://preview-568--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by rickoco** [comment]
looks good - pls publish
