### ISSUE TITLE
add RT-Thread as a Partner

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#564]
please find the attached RT-Thread Logo and the URL for https://www.rt-thread.org/ to be added as a Partner
![RT-Thread-Color](https://user-images.githubusercontent.com/2498391/212751137-4bfbea2a-bbb1-4f81-b1d3-f7528cc49741.svg)

**Comment by oliviergoulet5** [comment]
@rickoco Here is a preview: 

- https://preview-566--openhwgroup-org.eclipsecontent.org/
- https://preview-566--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by rickoco** [comment]
Thx @oliviergoulet5 - the order on the home page should be alpha and come before Synopsys in the partner logo section 
https://preview-566--openhwgroup-org.eclipsecontent.org/

**Comment by rickoco** [comment]
looks good @oliviergoulet5 - pls publish
