### ISSUE TITLE
Add Bylaws to member section

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#565]
At https://www.openhwgroup.org/membership/#tab-membership

The text describing points 1-4 should be updated as follows

1. Instead of the current numbered list 1-4, use bullets (the numbers will now be used to refer to forms)
2. The text should be updated as follows using the bullet type the web designer feels appropriate:

* Complete and sign the [Membership Information Form](https://www.openhwgroup.org/membership/openhw-membership-information-form.pdf) (form # 1).
* Read the [OpenHW Bylaws] (link to the bylaws to be inserted here). 
* Complete and sign the [Membership Agreement](https://www.openhwgroup.org/membership/openhw-group-membership-agreement-2019-10-16.pdf) (form # 2).
* For Platinum, Gold and Silver level memberships, complete and sign the [Member Committer and Contributor Agreement](https://www.eclipse.org/legal/committer_process/EclipseMemberCommitterAgreement.pdf) (form # 3). Form # 3 is not required for Supporter level memberships.
* [Email us](mailto:membership@openhwgroup.org) forms # 1, # 2, and # 3 (if applicable), as well as a full colour, vector-based member logo on a transparent background for our OpenHW member directory.

I will email the PDF file for the bylaws to @chrisguindon

**Comment by DBees** [comment]
@oliviergoulet5 I wasn't sure how to escape Github interpreting # + number as an issue, so I inserted a space between them above.

**Comment by oliviergoulet5** [comment]
Here is a preview of this change @DBees: https://preview-567--openhwgroup-org.eclipsecontent.org/membership/#tab-membership

Let me know whether it is good to go live!

**Comment by rickoco** [comment]
looks good @oliviergoulet5 - one small change to the first sub - bullet.  It should read:
- Complete the Membership Information Form

(delete "and sign" as there is no sign off block or need to sign off)

Once you've made that change pls go ahead and publish

**Comment by oliviergoulet5** [comment]
This is now live!
