### ISSUE TITLE
Add 10xEngineers as a member on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#569]
Please add 10xEngineers as members on OpenHW Group website: https://www.openhwgroup.org/ and https://www.openhwgroup.org/membership/members/

URL: https://10xengineers.ai/
![10x_logo_inkspace (3)](https://user-images.githubusercontent.com/50374570/214411039-0ad645df-4dac-455d-97c0-f1e566a420be.png)

**Comment by ericpoirier** [comment]
Hi @ZahraFazli, this logo is pretty big. Can we get a smaller/optimized version of it?

Thanks.

**Comment by rickoco** [comment]
@ericpoirier - pls scale it accordingly

**Comment by ericpoirier** [comment]
@oliviergoulet5 can you reduce the size of the logo a bit while adding it to the page?

Thanks.

**Comment by oliviergoulet5** [comment]
@rickoco @ZahraFazli Here is a preview: https://preview-570--openhwgroup-org.eclipsecontent.org/
