### ISSUE TITLE
Add UKRI Science and Technology Facilities Council to the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#571]
Please add attached logo of UKRI Science and Technology Facilities Council to the member's page on the website.

URL: https://www.ukri.org/councils/stfc/
![UKRI_STF_Council-Logo_Horiz-RGB](https://user-images.githubusercontent.com/50374570/216440153-d15fe730-7629-42ba-95bb-72badc6f95b6.png)

**Comment by oliviergoulet5** [comment]
Hi @ZahraFazli here is a preview: https://preview-573--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
LGTM!
