### ISSUE TITLE
Add EuroPractice as Partner on the website 

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#572]
Add attached logo for EuroPractice under Partners section on the website
 URL: https://europractice-ic.com/
![EP](https://user-images.githubusercontent.com/50374570/216440767-84873a75-673c-46ea-850c-8c133927f8a1.png)

**Comment by oliviergoulet5** [comment]
Hi @ZahraFazli here is the preview: https://preview-573--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
LGTM!
