### ISSUE TITLE
Remove University of Toronto's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#574]
University of Toronto is no longer a member of OpenHW Group. Kindly remove their logo from the website, 
Thanks!

**Comment by ZacharySabourin** [comment]
@ZahraFazli  here is a preview of the requested changes: https://preview-575--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZacharySabourin** [comment]
@ZahraFazli Just making sure this is still on your radar :)

**Comment by ZahraFazli** [comment]
Sorry about that! Yes, that looks good.
