### ISSUE TITLE
Add Sorbonne Universite as member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#576]
Please add the attached Sorbonne Universite's logo on the OpenHW Group website

URL: https://www.sorbonne-universite.fr/en

![Logo-SU-transp](https://user-images.githubusercontent.com/50374570/220740349-f8c51ed5-ec87-4f12-9b51-fef946fe9746.png)

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 

https://preview-577--openhwgroup-org.eclipsecontent.org/membership/members/

https://preview-577--openhwgroup-org.eclipsecontent.org/

Let me know if it is good to go live
