### ISSUE TITLE
Remove VeriSilicon Logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#578]
VeriSilicon is no longer an OpenHW Group member,. Kindly remove their logo from the website. 
Thanks

**Comment by oliviergoulet5** [comment]
@ZahraFazli Here is the preview:

https://preview-580--openhwgroup-org.eclipsecontent.org/

Let me know if it is good to go live

**Comment by ZahraFazli** [comment]
The link is not working for me

**Comment by oliviergoulet5** [comment]
It works for me... I'm wondering if it was still in the middle of deploying when you first clicked it?

**Comment by ZahraFazli** [comment]
I am getting a safety warning 
![image](https://user-images.githubusercontent.com/50374570/221638642-34f2fe40-377f-43b6-bcc8-bbb21d16e995.png)

**Comment by ZahraFazli** [comment]
@oliviergoulet5 the previous links worked fine. When I click "ignore" it takes me to the live OpenHW Group website where the logo still exists.

**Comment by oliviergoulet5** [comment]
I'll share a screenshot then since you can't access the page. I would imagine changing browsers would work if this ever happens again.

![image](https://user-images.githubusercontent.com/17685861/222451240-735a756d-569e-4a04-b993-04296549a567.png)
