### ISSUE TITLE
Remove Hensoldt Cyber GmbH logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#582]
Hensoldt Cyber GmbH is no longer a member. Kindly remove the logo from the website. 
Thanks

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 

https://preview-583--openhwgroup-org.eclipsecontent.org/

https://preview-583--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
LGTM
