### ISSUE TITLE
Removal of the job posting under the news section

### ISSUE THREAD

**Issue by oliviergoulet5** [openhwgroup/openhwgroup.org#586]
The job posting for a Hardware Verification Engineer has been pinned to the top of the news section for a few months now. I'm assuming the job posting has been closed. Are we ready to remove it?

/cc @rickoco @davideschiavone

**Comment by davideschiavone** [comment]
yes thanks

**Comment by oliviergoulet5** [comment]
@davideschiavone Here is a preview:

Removal from homepage: https://preview-592--openhwgroup-org.eclipsecontent.org/
Update to job posting blog post: https://preview-592--openhwgroup-org.eclipsecontent.org/resources/blog/hardware-verification-engineer/

I added an alert saying the position is closed. If you would prefer to remove the page entirely then let me know.

**Comment by rickoco** [comment]
Thx @oliviergoulet5 - keep the posting with the alert you added and remove the pinned sorting
