### ISSUE TITLE
Blog for OpenHW Blog page 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#587]
please add this blog to the OpenHW Blog page 
[Security for all - OpenHW Group leads the charge towards a secure future.docx](https://github.com/openhwgroup/openhwgroup.org/files/10885066/Security.for.all.-.OpenHW.Group.leads.the.charge.towards.a.secure.future.docx)

**Comment by oliviergoulet5** [comment]
Here is a preview @michelleclancy 

https://preview-593--openhwgroup-org.eclipsecontent.org/resources/blog/security-for-all-openhw-group-leads-the-charge-towards-a-secure-future/

**Comment by michelleclancy** [comment]
@oliviergoulet5 this blog is approved.. please post thank you

**Comment by michelleclancy** [comment]
@oliviergoulet5  do we know when this will be posted on the OpenHW site? We are waiting for the link for our newsletter to go out. thank you

**Comment by oliviergoulet5** [comment]
@michelleclancy I submitted the post to [newsroom](https://newsroom.eclipse.org/) and should appear on homepage once accepted. 


Here is a link to the blog post: https://www.openhwgroup.org/resources/blog/security-for-all-openhw-group-leads-the-charge-towards-a-secure-future/

**Comment by oliviergoulet5** [comment]
As an update: the post now displays on homepage.
