### ISSUE TITLE
Blog Post for OpenHW Blog page

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#588]
Please add this to the blog page 
[Embedded world blog .docx](https://github.com/openhwgroup/openhwgroup.org/files/10885069/Embedded.world.blog.docx)

**Comment by michelleclancy** [comment]
@oliviergoulet5  do you know when this will be posted on the OpenHW Website?  we need it to promote Embedded World on  social. thank you Michelle

**Comment by oliviergoulet5** [comment]
Here is a preview @michelleclancy: 

https://preview-596--openhwgroup-org.eclipsecontent.org/resources/blog/embedded-world/

As for the timeline, it is the same as I commented in the [other issue](https://github.com/openhwgroup/openhwgroup.org/issues/587).

I understand that this blog post is important for an event upcoming in the very near future. Let me know if the timeline I provided works.

**Comment by michelleclancy** [comment]
@oliviergoulet5 this is approved, please post to live. thank you

**Comment by oliviergoulet5** [comment]
@michelleclancy Here is the link to the live page: https://www.openhwgroup.org/resources/blog/embedded-world/

I'll be submitting this through the newsroom for it to show up on the front page.

**Comment by oliviergoulet5** [comment]
As an update: the post now displays on homepage.
