### ISSUE TITLE
Remove Imagination Technologies' logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#594]
Imagination Technologies is no longer a member. Kindly remove their logo from the website.

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 

https://preview-600--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
![image](https://user-images.githubusercontent.com/50374570/225040167-f523ecd2-c50b-45a9-a8f1-5f2e3e20c5d8.png)
It appears that there's an error in the link

**Comment by oliviergoulet5** [comment]
I believe this should be fixed now.

**Comment by ZahraFazli** [comment]
Looks good! Thanks
