### ISSUE TITLE
Add CRVA's logo as Partner on OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#595]
Please add CRVA's logo on the Partner section of OpenHW Group website. 

URL: http://crva.ict.ac.cn/
![微信图片_20230302103531](https://user-images.githubusercontent.com/50374570/223202560-5a37a74d-fa85-4f39-9a0c-ef93f89b43b5.png)

**Comment by autumnfound** [comment]
Duplicate of issue #589, closing
