### ISSUE TITLE
wrong sorting

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#597]
the news / blog posts on the main site page https://www.openhwgroup.org/ are not chronologically sorted

**Comment by oliviergoulet5** [comment]
@rickoco They should be already sorted. I believe you were looking at the top news item which we "pinned" for the job ad. 

I created this issue to get it removed: #586

**Comment by oliviergoulet5** [comment]
Sounds good, I'll keep the page. I'll be closing this issue since it is a duplicate.
