### ISSUE TITLE
Replace CORE-V MCU DevKit image

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#598]
Please update the https://www.openhwgroup.org/core-v-devkits/ page by replacing the current CORE-V MCU DevKit image with the one attached here...
![UPDATED MCU DevKit](https://user-images.githubusercontent.com/2498391/224813385-ada07b90-fd32-4aa3-bd8f-c697ba868fff.png)

**Comment by oliviergoulet5** [comment]
Hi @rickoco. Here is a preview: https://preview-599--openhwgroup-org.eclipsecontent.org/core-v-devkits/

**Comment by rickoco** [comment]
thx @oliviergoulet5 - looks good.  Pls also update the 2nd last sentence at the bottom of the page to read: "delivery in Q4 2023."

**Comment by oliviergoulet5** [comment]
@rickoco The 2nd last sentence has been updated

**Comment by rickoco** [comment]
looks good @oliviergoulet5 - publish away...
