### ISSUE TITLE
GreenWaves logo and Calista's quote

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#60]
Hey team – there’s a typo in Calista’s quote (see below) and the GreenWaves logo in both the sponsor and testimonial sections is messed up.  Logo sent via email...
Rick

stakeholderss in the RISC-V revolution

**Comment by ericpoirier** [comment]
Hi Rick,

I just merged a patch to fix both the typo and the logo. We should see these changes in a few minutes.
