### ISSUE TITLE
Remove Metrics Technologies' logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#609]
Metrics Technologies is no longer a member. Kindly remove the logo from the website. 
Thanks

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli: 

- https://preview-610--openhwgroup-org.eclipsecontent.org/
- https://preview-610--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, thanks
