### ISSUE TITLE
OpenHW TV S04/E01 – Security for All: OpenHW Group Leads the Charge Towards a Secure Future

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#611]
Please post under OpenHW TV. thank you
 
Title:                      OpenHW TV S04/E01 – Security for All: OpenHW Group Leads the Charge Towards a Secure Future
 
Abstract:
Security has become a critical issue for the entire IoT supply chain in recent years, as the number of connected devices continues to grow and our reliance on them increases. With more devices connected to the internet, the potential for security breaches and data theft also increases. The following topics will be discussed in this episode:
 
Brief overview of the CORE-V Trusted MCU Project. (This project was developed to ensure there is an option for the very best security starting from the design phase on all OpenHW devices.)
The complexity of IoT security
The current vulnerabilities of hardware
The benefits of having a root of trust or physical uncountable function (PUF) in your device
 
Featured presenters for this episode will include: Dr. Abdoulaye Berthe, Founder & President of Low Power Futures and Chris Jones, Director of Applications at Crypto Quantique. Rick O'Connor, President & CEO of OpenHW Group, will host a live Q&A session at the end of the webinar.
 
YouTube:              https://youtu.be/MNYOaJGltYY

**Comment by oliviergoulet5** [comment]
Here is a preview @michelleclancy: https://preview-612--openhwgroup-org.eclipsecontent.org/resources/openhwtv/

**Comment by michelleclancy** [comment]
@oliviergoulet5 thank you this is approved
