### ISSUE TITLE
Updated logo on OpenHW Member page

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#613]
Hi,
can you please update the logo for Codasip on the OpenHW member logo page? 
[Logo kit.zip](https://github.com/openhwgroup/openhwgroup.org/files/11399218/Logo.kit.zip)

**Comment by oliviergoulet5** [comment]
@michelleclancy Here is an updated Codasip logo preview: https://preview-614--openhwgroup-org.eclipsecontent.org/

**Comment by chrisguindon** [comment]
@DBees Maybe you can approve this preview? Thanks

**Comment by michelleclancy** [comment]
@chrisguindon approved
