### ISSUE TITLE
Update Cobham Gaisler's name and logo on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#615]
Please update Cobham Gaisler's name and logo on the website. 

Their new name is "Frontrgrade Gaisler" and the logo is attached. 
![Gaisler_Horiz_Dark on Transparent](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/12e70d25-9dfb-4362-bc43-951d6a4020b0)
The website stays the same (https://www.gaisler.com/)

**Comment by oliviergoulet5** [comment]
Hi @ZahraFazli 

I'll share screenshots of the changes as opposed to sharing a preview link. The preview builds haven't been performing well for the last couple of days.

**Homepage:**
![image](https://github.com/openhwgroup/openhwgroup.org/assets/17685861/5dfca822-c840-47fe-b7e0-73a49cba1d4c)


**Explore Members page:**
![image](https://github.com/openhwgroup/openhwgroup.org/assets/17685861/70016b5b-74f1-4ddf-8cca-66fc903ab492)

**Comment by chrisguindon** [comment]
@ZahraFazli Can you review and approve @oliviergoulet5 change please?

**Comment by ZahraFazli** [comment]
Looks good. Thanks
