### ISSUE TITLE
Blog posting on OpenHW site 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#619]
hi, 
can you post the following two blogs on the openHW blob site.  The job description should come before the UVM blog post.  Please also place the job description blog under the homepage News section.  Let me know if you have any questions.

1. Title: OpenHW Group Seeking CEO - Job Description

2. Title: UVM Verification of OpenHW Group’s CORE-V MCU in the Cloud for Pennies per Minute

thank you,
Michelle
[UVM datum blog post 5.23.docx](https://github.com/openhwgroup/openhwgroup.org/files/11568111/UVM.datum.blog.post.5.23.docx)

[OpenHW Group CEO Job Description.docx](https://github.com/openhwgroup/openhwgroup.org/files/11568092/OpenHW.Group.CEO.Job.Description.docx)

**Comment by rickoco** [comment]
@oliviergoulet5 - is the CEO job posting up yet?

**Comment by oliviergoulet5** [comment]
Here's a preview for this @rickoco @michelleclancy: https://preview-620--openhwgroup-org.eclipsecontent.org/resources/blog/openhw-group-seeking-ceo/

**Comment by rickoco** [comment]
Thx @oliviergoulet5 - pls publish the CEO post.

**Comment by oliviergoulet5** [comment]
No problem! I'm deploying the CEO post.

@michelleclancy Please use this new preview link for the UVM post: https://preview-621--openhwgroup-org.eclipsecontent.org/resources/blog/uvm-verification-of-openhw-groups-core-v-mcu-in-the-cloud-for-pennies-per-minute/

**Comment by rickoco** [comment]
Thx @oliviergoulet5 - I see the CEO post is up.  Thank you.  Were you able to pre-pend the Subject line in the mailto link with [OpenHW CEO]?  Its not coming up for me.

**Comment by oliviergoulet5** [comment]
@michelleclancy Are we good to go live?

**Comment by michelleclancy** [comment]
Yes please go live – sorry I was out for the week in Barcelona.

Thank you


From: Olivier Goulet ***@***.***>
Reply-To: "openhwgroup/openhwgroup.org" ***@***.***>
Date: Friday, June 9, 2023 at 4:51 PM
To: "openhwgroup/openhwgroup.org" ***@***.***>
Cc: michelleclancy ***@***.***>, Mention ***@***.***>
Subject: Re: [openhwgroup/openhwgroup.org] Blog posting on OpenHW site (Issue #619)


@michelleclancy<https://github.com/michelleclancy> Are we good to go live?

**Comment by rickoco** [comment]
@oliviergoulet5 - for the OpenHW CEO post, it does not show here as a pinned item... https://www.openhwgroup.org/news/

**Comment by oliviergoulet5** [comment]
Should be fixed @rickoco. The pinned news item now displays on homepage and the news page.
