### ISSUE TITLE
Remove IAR Systems Group's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#628]
IAR Systems Group AB is  no longer a member of OpenHW Group. Kindly remove their logo from the website
https://www.openhwgroup.org/
https://www.openhwgroup.org/membership/members/

Thanks

**Comment by rickoco** [comment]
Please also remove the "Secure Thingz" logo as this is a sub-brand of IAR.

**Comment by autumnfound** [comment]
> Please also remove the "Secure Thingz" logo as this is a sub-brand of IAR.

+1, pushed an update, should be live in a minute

**Comment by ZahraFazli** [comment]
Looks good. Thanks
