### ISSUE TITLE
Add Politecnico di Torino as member on the OpenHW Group site

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#633]
Politecnico di Torino is a new member. Please add their attached logo to the website. Thanks

URL: https://www.polito.it/
![logo-01](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/a420dbf8-3fa9-4304-9e65-893a7595b13a)

**Comment by autumnfound** [comment]
@ZahraFazli see https://preview-634--openhwgroup-org.eclipsecontent.org/ for the preview of the changes. Let me know if you need further changes or if we are good to go live. Thanks!

**Comment by ZahraFazli** [comment]
Hi Martin, preview is not available 
![image](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/cdff43c3-9fb9-4087-aad6-038fec2cdd2c)
