### ISSUE TITLE
Remove Mitacs as a member on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#635]
Mitacs is no longer a member. Kindly remove their logo from the website.

**Comment by oliviergoulet5** [comment]
@ZahraFazli Mitacs no longer displays on the members page. 

Question for you: We currently have a Mitacs employee as co-chair under the Outreach Task Group. Does this also get impacted or does the employee remain? See https://www.openhwgroup.org/working-groups/#university-outreach-task-group. 

Here is a screenshot of the change:

![image](https://github.com/openhwgroup/openhwgroup.org/assets/17685861/78ce02c7-86fc-484e-80e5-9d5908e2de75)

**Comment by ZahraFazli** [comment]
Thank you Olivier
@rickoco can you please advice on Mitacs' employee co-chairing the Outreach Task Group. Thanks
