### ISSUE TITLE
OpenHW TV video/episodes for website 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#639]
can we add the following videos to the OpenHW TV webpage?  They should be under the main header:

OpenHW Group TRISTAN Workshop at the RISC-V European Summit
Barcelona -- 5-9 June 2023

Title:                      TRISTAN Workshop: Open-Source Hardware Basic Training (Part 1)

This workshop segment is led by:
César Fuguet, Research and Development Engineer, CEA
Mario Rodriguez, OpenHW Group Verification Engineer, Verification Task Group
Davide Schiavone, OpenHW Group Director of Engineering, Cores Task Group
Mike Thompson, OpenHW Group Director of Engineering, Verification Task Group
 
YouTube:              https://youtu.be/Twihznkd7-U 
 
 
Title:                      TRISTAN Workshop: Open-Source Hardware Basic Training (Part 2)

This workshop segment is led by:
César Fuguet, Research and Development Engineer, CEA
Mario Rodriguez, OpenHW Group Verification Engineer, Verification Task Group
Davide Schiavone, OpenHW Group Director of Engineering, Cores Task Group
Mike Thompson, OpenHW Group Director of Engineering, Verification Task Group
 
YouTube:              https://youtu.be/3r5STMiUq9s
 
 
Title:                      TRISTAN Workshop: A Quick Introduction to CORE-V-VERIF

                        This workshop segment is led by Mario Rodriguez, OpenHW Group Verification Engineer, Verification Task Group
 
YouTube:          https://youtu.be/N3nQJpZN2_0 
 
 
Title:                      TRISTAN Workshop: Simulating CV32E40P in CORE-V-VERIF
 
                        This workshop segment is led by Mike Thompson, OpenHW Group Director of Engineering, Verification Task Group
 
YouTube:          https://youtu.be/nGs6riKUZLU
 
 
Title:                TRISTAN Workshop: Simulating CVA6 in CORE-V-VERIF

                        This workshop segment is led by Mario Rodriguez, OpenHW Group Verification Engineer, Verification Task Group
 
YouTube:          https://youtu.be/8p7TMX4GPmo

**Comment by oliviergoulet5** [comment]
@michelleclancy Here is a preview @michelleclancy: https://preview-640--openhwgroup-org.eclipsecontent.org/resources/openhwtv/

To create a separate section for non-season videos I added "series". This allows us to categorize non-season videos together and can be used for events such as the RISC-V European Summit here.  They work very similarly to seasons. I'm open to naming this differently... maybe playlists? 

The main OpenHW TV page will only display the latest series.

You can view all series here: https://preview-640--openhwgroup-org.eclipsecontent.org/resources/openhwtv/series/

This page isn't linked anywhere. I think it would be best to link it when we have 2 or more. 

Also going to include @shanda-eclipse in the discussion as this is somewhat a big change for the OpenHW TV section. 

Let me know what you all think, or if you have better ideas.

**Comment by shanda-eclipse** [comment]
> Also going to include @shanda-eclipse in the discussion as this is somewhat a big change for the OpenHW TV section.

No opinion on my side. It looks good.
