### ISSUE TITLE
Update DevKit page on website

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#645]
Hi, please update this page https://www.openhwgroup.org/core-v-devkits/ as follows. Keep the same styles and fonts for text and headers, etc. 

(1) Re-order so that the "CORE-V MCU DevKit" section comes first and the "CORE-V MCU Emulation Platform" section comes second
(2) Replace the diagram of the CORE-V MCU DevKit section with this one https://github.com/openhwgroup/core-v-mcu-devkit/blob/main/images/OpenHW%20DevKit.png
(3) Update the text of the CORE-V MCU DevKit section as follows. 

The [CORE-V MCU DevKit](https://github.com/openhwgroup/core-v-mcu-devkit) is a turnkey, open-source development and 
prototyping platform for the CORE-V MCU System on Chip. The CORE-V MCU DevKit enables makers of IoT and embedded systems to evaluate the performance of the CORE-V MCU, to interconnect with WiFi and the IoT cloud, and to develop and test software using the [CORE-V SDK](https://github.com/openhwgroup/core-v-sdk).

The CORE-V MCU DevKit includes these features:
CORE-V MCU
CV32E40P processor core
Quicklogic ArticPro 2 eFPGA
4 MB flash memory
Ashling Opella-LD onboard JTAG debug module
USB-C for terminal and onboard debug access
JTAG connector for external debug access
Espressif AWS IoT ExpressLink Module for AWS IoT cloud interconnect
mikroBUS onboard socket, allowing access to a vast range of mikroBUS modules
Himax HM01B0 Ultralow Power CMOS Image Sensor
I2C temperature sensor
Several LEDs
Reset button and general purpose button
Dimensions 75 mm x 100 mm
Power supply via USB-C or barrel connector (5V - 18V in)

The CORE-V MCU DevKit is supported by OpenHW Group’s open-source [CORE-V MCU SDK](https://github.com/openhwgroup/core-v-sdk). The SDK comprises the following features

Eclipse based IDE
Debug support
FreeRTOS
CORE-V GNU GCC tool chain
Peripheral driver libraries
Example Code

The [CORE-V MCU SDK Quickstart Guide](https://github.com/openhwgroup/core-v-sdk/blob/main/README.md) includes links and instructions to download and bring up the SDK on Linux and Windows.

Ordering the CORE-V MCU DevKit
The CORE-V MCU DevKit is currently available for early access order on the [GroupGets website](https://groupgets.com/) with anticipated delivery of November 14, 2023. Visit the [GroupGets CORE-V MCU DevKit early access campaign page](https://groupgets.com/campaigns/1040-core-v-mcu-devkit) to reserve your DevKit, as early access quantities are limited.

**Comment by ZacharySabourin** [comment]
@DBees There seems to be an issue with the image URL provided: https://github.com/openhwgroup/core-v-mcu-devkit/blob/main/images/OpenHW%20DevKit.png

I'm getting a 404

**Comment by DBees** [comment]
I @ZacharySabourin apology these files were reorganized. The image files are now in https://github.com/openhwgroup/core-v-mcu-devkit/tree/main/docs/images

**Comment by ZacharySabourin** [comment]
@DBees Not a problem! Here is a preview with the requested changes https://preview-646--openhwgroup-org.eclipsecontent.org/core-v-devkits/

**Comment by DBees** [comment]
Thanks @ZacharySabourin looks good but please hold off until we can you an updated image that includes the appropriate logo in place of the black and yellow square where the CORE-V device goes.  Stand by.

**Comment by ZacharySabourin** [comment]
Hey @DBees! What's the status of the updated image?

**Comment by DBees** [comment]
@ZacharySabourin sorry to keep you on hold. We have some new images but there will be one more iteration. Please stand by, should have them soon.

**Comment by DBees** [comment]
@ZacharySabourin at last we have the image for you
https://drive.google.com/file/d/1J3MxBiP_YuFuoV7cXcvT0cvH5JRtb6ga/view?usp=drive_link

**Comment by ZacharySabourin** [comment]
@DBees Awesome! Here is a preview with the requested changes: https://preview-646--openhwgroup-org.eclipsecontent.org/core-v-devkits/

**Comment by DBees** [comment]
Looks good. 

Please add this sentence as the last sentence of the paragraph immediately above "ordering the DevKit": 

The [DevKit User Manual](https://docs.openhwgroup.org/projects/core-v-mcu-devkit-user-manual/en/latest/) is available on Read rhe Docs.

Please add a couple of hotlinks as indicated:
.. is a turnkey, open-source development and prototyping platform for the [CORE-V MCU System on Chip](https://github.com/openhwgroup/core-v-mcu)

..The [CORE-V MCU SDK Quickstart Guide](https://github.com/openhwgroup/core-v-sdk/blob/main/README.md)

When you've added these things please go live, no need for further review. Thankyou!

**Comment by ZacharySabourin** [comment]
The page is now live! https://www.openhwgroup.org/core-v-devkits/
