### ISSUE TITLE
Add Technology Innovation Institute logo to the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#647]
Attached is the logo for Technology Innovation Institute. Please add it to the OpenHW Group website

![Outlook-ngqcnyp1-1](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/83a34a9b-e860-4283-884c-b6d7c25e9761)

URL: https://www.tii.ae/

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli: https://github.com/openhwgroup/openhwgroup.org/pull/648

Please let me know if we're good to go live!

**Comment by ZahraFazli** [comment]
Looks good, thanks
