### ISSUE TITLE
update OpenHW about us - Board of Director page 

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#650]
can you please remove Xiaoning Qi- Chairman of the Board with his bio from this page https://www.openhwgroup.org/about-us/

also, please remove John D. Davis- Board Member and REPLACE with: 

Miquel Moreto 

Miquel Moreto is an Associate Professor at the Computer Architecture Departament (DAC) of the Universitat Politècnica de Catalunya (UPC), and he leads the High Performance Domain Specific Architectures team at the Barcelona Supercomputing Center (BSC). Miquel received the PhD from UPC in 2010. After finishing the PhD, he spent 15 months at the International Computer Science Institute (ICSI), affiliated with UC Berkeley, as a Fulbright Postdoctoral Research Fellowship Holder during 2011 and 2012. In 2013, he returned to Barcelona to work on multiple European projects (RoMoL, Mont-Blanc, EPI, DeepHealth, eProcessor) and industrial projects (Arm, IBM, Lenovo). Miquel has published over 125-refereed conference and journal papers and co-advised 12 PhD students. In 2019, he led the design and fabrication of Lagarto, the first academic processor developed in Spain based on the open source RISC-V instruction set architecture. Finally, he coordinates the DRAC project, which is promoting the Lagarto initiative with new generations of the processor and accelerators.

https://www.linkedin.com/in/miquelmoreto/

thanks
MIchelle

**Comment by oliviergoulet5** [comment]
Hi @michelleclancy. I will look into writing a patch for this tomorrow.

**Comment by oliviergoulet5** [comment]
Here is a preview @michelleclancy: https://preview-652--openhwgroup-org.eclipsecontent.org/about-us/

I placed Miquel Moreto with the exact ordering as John D. Davis. Please let me know if it should be alphabetical instead.

**Comment by michelleclancy** [comment]
@oliviergoulet5 thanks for getting this up quickly.. I'll find out about the order, but for now leave as is and post.
thanks
