### ISSUE TITLE
Update Working Group page

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#651]
Changes to https://www.openhwgroup.org/working-groups/

1) Remove David Lynch as co-chair of TWG and leave that position blank

2) Remove Simon Davidmann as chair of the Verification TG and leave that position blank. Change Jean-Roch Coulon to "Co-Chair".

3) Remove Jeremy Bennet as Chair and Yunhai Shang as Vice-Chair of the SW TG. Add Paolo Savini of Embecosm as Chair. https://www.linkedin.com/in/paolo-savini-56b833147/?originalSubdomain=uk

4) Create Safety and Security TG and add Jaume Abella of Barcelona Supercomputer Centre as Co-Chair https://www.linkedin.com/in/jaume-abella-860575/ as well as Chris Jones of Crypto Quantique as Co-Chair https://www.linkedin.com/in/chris-jones-1791b71/

Mailing list https://accounts.eclipse.org/mailing-list/openhw.safety-security

5) Create Interconnect TG and add Jonathan Balkind of UC Santa Barbara as Co-Chair  https://www.linkedin.com/in/jbalkind/ and well as César Fuguet of CEA as Co-Chair https://www.linkedin.com/in/cesar-fuguet/

(Mailing list not yet available)

**Comment by oliviergoulet5** [comment]
Hi @DBees, under what working groups should these new task groups belong?

**Comment by oliviergoulet5** [comment]
Here is a preview @DBees: https://preview-653--openhwgroup-org.eclipsecontent.org/working-groups/

**Comment by DBees** [comment]
Overall this looks good @oliviergoulet5 with the following changes please:

- Let's align on using or not using a hyphen; so we'll follow Vice Chair and make the others Co Chair (without the hyphen). My bad.
- For Verification TG, please make Jean-Roch a Co Chair and move him to the left side, and show the vacancy as Co Chair on the right
- The Interconnect TG should go under the TWG just as Cores, SW, etc.
- Please remove entirely the "University Outreach Task Group" and the "Task Groups" Heading above it

Thank you
Duncan

**Comment by oliviergoulet5** [comment]
@DBees The changes have been made!

**Comment by DBees** [comment]
@oliviergoulet5 good but please show vacancy in Verif TG as Co Chair (preview shows it as Chair)

**Comment by oliviergoulet5** [comment]
Updated @DBees

**Comment by DBees** [comment]
@oliviergoulet5 thank you, looks great
