### ISSUE TITLE
Remove Silicon Assurance logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#654]
Silicon Assurance is no longer a member. Kindly remove their logo from the OpenHW Group website. Thanks

**Comment by ZacharySabourin** [comment]
@ZahraFazli Here is a preview of the requested changes: https://preview-655--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Looks good. Thanks
