### ISSUE TITLE
Github advisory - please comment

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#656]
Can the webdev team please comment on this, I don't understand it
https://github.com/advisories/GHSA-67hx-6x53-jw92/dependabot?query=user:openhwgroup

**Comment by autumnfound** [comment]
The mentioned packages only impact the build of the site, not the running site in this case. While we should get it fixed, since we review any Javascript code that gets submitted, we're pretty low-risk here!

**Comment by DBees** [comment]
so no action needed then?

**Comment by autumnfound** [comment]
> so no action needed then?

In that there is no active risk for this project, there is no action needed, no. The webdev team will look into resolving this in the near future so that sites like this one can be fixed through the natural update process!

**Comment by chrisguindon** [comment]
@DBees I am releasing a new version of our front-end stack and our hugo theme that addresses all these vulnerabilities. I will make sure all the OpenHWGroup websites are patched before I leave for the week-end.

Thanks for letting us know.

**Comment by chrisguindon** [comment]
@DBees openhwgroup.org and osdforum.org where updated. We should be good now.
