### ISSUE TITLE
OpenHW homepage website

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#657]
can we post this under news or under events of the activities at the upcoming RISC-V Summit?  we need to have a link to use for social postings. Let me know if you have any questions.
thanks
Michelle
[RISCV summit for website .docx](https://github.com/openhwgroup/openhwgroup.org/files/13121338/RISCV.summit.for.website.docx)

**Comment by michelleclancy** [comment]
@oliviergoulet5 thanks! anytime is fine, hoping to have it up by end of week, best M

**Comment by oliviergoulet5** [comment]
Here is a preview @michelleclancy: https://preview-659--openhwgroup-org.eclipsecontent.org/news/2023/10/25/please-join-openhw-group-staff-and-members-at-the-upcoming-risc-v-summit/

**Comment by oliviergoulet5** [comment]
@michelleclancy Are we good to go live?

**Comment by DBees** [comment]
@oliviergoulet5  @michelleclancy  - I  suggest you change
Main Stage: Open Source HW Commercial Adoption – Lessons Learned: Rick & Flo
to 
Main Stage: Open Source HW Commercial Adoption – Lessons Learned: Rick O'Connor, OpenHW Group CEO Emeritus & Flo Wolhrab, OpenHW Group CEO 

Michelle is away and not reliably accessing Github. Please go live ASAP as the summit is fast approaching.

**Comment by oliviergoulet5** [comment]
@DBees The page is live, and I have submitted the post to the newsroom. I've mentioned to them that it is a high priority. Hopefully, it should appear on the homepage later today!

Here is a link to the news item on the live website: https://www.openhwgroup.org/news/2023/10/31/please-join-openhw-group-staff-and-members-at-the-upcoming-risc-v-summit/

**Comment by oliviergoulet5** [comment]
It was approved the moment I sent my last comment. It is now on the homepage.

Closing the issue!

**Comment by DBees** [comment]
thank you @oliviergoulet5
