### ISSUE TITLE
OpenHW TV Episode to be added to OpenHW TV website page

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#658]
please add the latest OpenHW TV episode to the OpenHW TV webpage - YouTube:
 
Title: OpenHW TV S04/E02 – Destination: ASIC-Ready – Journey of the Open-Source Application-Class RISC-V Processor CVA6
 
Description:
 
This episode of OpenHW TV focuses on the incredible journey of the open-source RISC-V processor CVA6, from its inception as Ariane to its present state. The discussion covers its current features, supported configurations (e.g., multicore) accelerators (e.g., RISC-V Vector), and platforms. Details of the ongoing design improvements and rigorous verification work will be shared along with a demo of DOOM running on CVA6 (on an FPGA platform). Finally, we will discuss the future roadmap of CVA6 with multiple OpenHW Group members. Featured Presenters: - Florian Zaruba, Axelera AI and OpenHW Group - Fatima Saleem, 10xEngineers - Jean-Roch Coulon, Thales - Sébastien Jacq, Thales Flo Wohlrab, CEO of OpenHW Group, will host a live Q&A session at the end of this episode.
 
 https://youtu.be/LXBfv3OAuhU

**Comment by oliviergoulet5** [comment]
Here is a preview of the addition of S04E02:

- https://preview-662--openhwgroup-org.eclipsecontent.org/resources/openhwtv/
- https://preview-662--openhwgroup-org.eclipsecontent.org/resources/openhwtv/seasons/season4/

@DBees @michelleclancy

**Comment by michelleclancy** [comment]
@oliviergoulet5 the openHW TV episodes is approved to post. thank you, sorry for the delay
