### ISSUE TITLE
Remove Huawei's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#668]
Huawei is no longer an OpenHW Group member. Please remove their logo from the website. 
Thanks

**Comment by oliviergoulet5** [comment]
@ZahraFazli Here is a preview of the removal of Huawei: https://preview-670--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
LGTM. Thanks
