### ISSUE TITLE
Add Cirrus Logic to the website as an OpenHW Group member

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#669]
Attached, please find Cirrus Logic's logo to be added to the website under members.

![Cirrus Logic logo](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/bc3ec06a-8e47-4801-a570-c7ff356debfa)

URL: https://www.cirrus.com/

Thanks

**Comment by oliviergoulet5** [comment]
@ZahraFazli Here is a preview of cirrus logic being added: https://preview-670--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
Looks good, thanks
