### ISSUE TITLE
Add Red Hat as a member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#671]
Red Hat has joined OpenHW Group, Please add their logo and URL to OpenHW Group's website. 

Please add the logo and URL: https://www.redhat.com/en
![731-web](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/33f185a9-8553-4b0e-98d8-64e37c93822f)

**Comment by oliviergoulet5** [comment]
@ZahraFazli Here is a preview: https://preview-672--openhwgroup-org.eclipsecontent.org/

**Comment by oliviergoulet5** [comment]
@ZahraFazli any update?

**Comment by ZahraFazli** [comment]
Looks good. Sorry for the delay.
