### ISSUE TITLE
Remove staff from OpenHW GRoup website

### ISSUE THREAD

**Issue by michelleclancy** [openhwgroup/openhwgroup.org#673]
hi 
can we remove Max from the Staff page? 
thank you,
Michelle

Massimiliano (Max) Giacometti
- Staff Member
Massimiliano is responsible for Continuous Integration and DevOps for the OpenHW Group. He has more than 15 years of experience as digital designer and has been passionately working on several RISC-V-related projects over the last 5 years. Since his graduation (BSc and MSc in Electronic Engineering from the University of Parma) he's been working as contributor and manager in Italy, France and Germany.

**Comment by michelleclancy** [comment]
can this request be addressed? Please let me know if there are any issues with the request.
michelle

**Comment by oliviergoulet5** [comment]
Here is a preview @michelleclancy https://preview-675--openhwgroup-org.eclipsecontent.org/about-us/
