### ISSUE TITLE
Remove Low Power Futures logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#685]
Low Power Futures is no longer an OpenHW Group member. Please remove their logo from the website. Thank you.

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 

- https://preview-686--openhwgroup-org.eclipsecontent.org
- https://preview-686--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
LGTM. Thanks
