### ISSUE TITLE
Add Corelab Technology's logo to the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#687]
Corelab Technology Pte.Ltd is a new member. Please add the attached logo to the website. 

<img width="128" alt="corelab Logo" src="https://github.com/openhwgroup/openhwgroup.org/assets/50374570/d7678fe9-528f-4db7-b824-5f7b62ed9d92">

Thank you

**Comment by oliviergoulet5** [comment]
@ZahraFazli do you have a transparent version that we can use instead?

**Comment by ZahraFazli** [comment]
That's the only version they have sent

**Comment by oliviergoulet5** [comment]
Here's a preview @ZahraFazli:  

- https://preview-689--openhwgroup-org.eclipsecontent.org/
- https://preview-689--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Looks good. Thanks

**Comment by ZahraFazli** [comment]
Please embed the following URL to Corelab's logo
https://www.corelabtech.com/en

**Comment by ZacharySabourin** [comment]
Hey @ZahraFazli! Here is a preview of the requested changes https://preview-693--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
LGTM. Is the URL added on [this](https://www.openhwgroup.org/) page as well?

**Comment by ZacharySabourin** [comment]
@ZahraFazli Yup! You can see it here: https://preview-693--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
Thank you.
