### ISSUE TITLE
 security advisory on webpack-dev-middleware

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/openhwgroup.org#690]
Hi @oliviergoulet5.  A GitHub `dependabot` generated the following security advisory: https://github.com/openhwgroup/openhwgroup.org/security/dependabot/50.  The file in question is auto-generated, so a manual fix is not likely to work.  Can you have a look?

FYI @DBees and @Floadv298.

**Comment by oliviergoulet5** [comment]
Our dependencies have been updated via #696
