### ISSUE TITLE
Remove Espressif's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#691]
Espressif Systems (Shanghai) Co. Ltd is no longer an OpenHW Group member. Please remove their logo from the website. Thanks

**Comment by ZacharySabourin** [comment]
@ZahraFazli Here is a preview of the requested changes:
- https://preview-692--openhwgroup-org.eclipsecontent.org/membership/members/
- https://preview-692--openhwgroup-org.eclipsecontent.org/

**Comment by ZahraFazli** [comment]
Looks good. Thanks
