### ISSUE TITLE
Remove NXP's logo from the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#694]
NXP is no longer an OpenHW Group member. Kindly remove their logo from the website.

**Comment by ZacharySabourin** [comment]
Hey @ZahraFazli! Here is a preview of the requested changes:
- https://preview-695--openhwgroup-org.eclipsecontent.org/
- https://preview-695--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Looks good! Thank you!
