### ISSUE TITLE
Add Axelera AI's logo on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#698]
Axelera AI is a new member. Please add the attached logo to openhwgroup website

URL: https://www.axelera.ai/

![Axelera-AI-Logo-Black-and-Yellow-High-Resolution](https://github.com/openhwgroup/openhwgroup.org/assets/50374570/f2166a4e-187f-4e27-9f9a-ff602b857775)

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 

https://preview-699--openhwgroup-org.eclipsecontent.org/
https://preview-699--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Looks good, thanks!
