### ISSUE TITLE
Update TG page

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#700]
https://www.openhwgroup.org/working-groups/

TWG co-chair should be added: Jeremy Bennett, Embecosm  https://www.linkedin.com/in/jeremypbennett/?originalSubdomain=uk

Please remove HW TG from the page. We will put it back when we acquire a TG chair

**Comment by oliviergoulet5** [comment]
Here is a preview @DBees https://preview-701--openhwgroup-org.eclipsecontent.org/working-groups/

Please let me know whether we're good to go live!

**Comment by DBees** [comment]
Actually looks good but one more change. Can you please remove Chris Jones as co-chair of the Safety and Security Group? YOu can indicate the position is vacant.

**Comment by oliviergoulet5** [comment]
@DBees I updated the co-chair position as vacant in the latest update to the preview.

**Comment by DBees** [comment]
good to go!
