### ISSUE TITLE
remove links to groupgets order page

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#704]
https://www.openhwgroup.org/core-v-devkits/

Please remove the section as follows and leave the rest as-is

Ordering the CORE-V MCU DevKit
The CORE-V MCU DevKit is currently available for early access order on the [GroupGets website](https://groupgets.com/) with anticipated delivery of November 14, 2023. Visit the [GroupGets CORE-V MCU DevKit early access campaign page](https://groupgets.com/campaigns/1040-core-v-mcu-devkit) to reserve your DevKit, as early access quantities are limited.

No need for preview

**Comment by oliviergoulet5** [comment]
This change is now live!

**Comment by DBees** [comment]
thank you!
