### ISSUE TITLE
Add Acceler Logic (Pvt) Ltd logo on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#706]
Acceler Logic (Pvt) Ltd is a new member. Please add their logo to the website

![LOGO-01-1](https://github.com/user-attachments/assets/8ea43e18-8a50-4b76-8a6d-d87e51243e4d)

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 

- https://preview-707--openhwgroup-org.eclipsecontent.org/
- https://preview-707--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Hi Can you please link it to https://accelr.lk/

**Comment by ZahraFazli** [comment]
On this page https://preview-707--openhwgroup-org.eclipsecontent.org/membership/members/ the full name is not appearing. It seems like Ltd is cut off from the name.

**Comment by oliviergoulet5** [comment]
Good catch, I must have left it out accidentally.

**Comment by ZahraFazli** [comment]
Good to go. Thanks
