### ISSUE TITLE
Update About-Us Page

### ISSUE THREAD

**Issue by Floadv298** [openhwgroup/openhwgroup.org#708]
**Please remove inactive Memebrs from About-Us page**
-Remove Daniel Cooley- Board Member 
-Remove Duncan Bees- Staff Member

+ New Board Member (will have data next week)

Thanks
Flo

**Comment by oliviergoulet5** [comment]
Hi @Floadv298 

Here is a preview of the change: https://preview-709--openhwgroup-org.eclipsecontent.org/about-us/

Let me know if it is good to go live!

**Comment by Floadv298** [comment]
Hi @oliviergoulet5 
Looks Good Do you want to add the new Director Keith with this PR or should I make another PR?

**Comment by oliviergoulet5** [comment]
Hi @Floadv298, I welcome either option!

However, to prevent merge conflicts, I'll need to merge my current PR before you can start working on it.

I could also add the new director myself if you could provide their full name and bio.

It's up to you!

**Comment by Floadv298** [comment]
Hi @oliviergoulet5 
Cool, Here are his Bio (He has no LinkedIn):

Keith Hopkins

Keith Hopkins is a serial entrepreneur.  He started in Design with Intel and transitioned to Sales/Business Development for EDA, Consulting and Semiconductor IP licensing.  Over the past 2 decades, he has worked with multiple early/mid stage companies as VP Sales/Business Development including ARM, Artisan, Denali, PLDA and EVE where he created comprehensive business strategies, developed the Sales/Business Plans, built the Sales teams and accelerated revenues leading to 4 company M&A exits with valuations in excess of $1.5B. He is currently an Executive Advisor, member of multiple Boards and the EVP of Sales and Business Development for Corelab Technology. He has been a part of CPU evolution from Intel to ARM and is excited to get a front row seat for the next stage by joining the OpenHW Board as the world explores RISC-V.
