### ISSUE TITLE
Add RISC-V Taiwan Alliance (RVTA) logo on the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#710]
RISC-V Taiwan Alliance (RVTA) is one of the partners of OpenHW Group. Please add their attached logo under partners section.

URL: https://www.twiota.org/RISC-V/

![RISC-V_logo](https://github.com/user-attachments/assets/79702d42-1fec-4f45-8160-dcfa98790fc6)

**Comment by oliviergoulet5** [comment]
Hi @ZahraFazli! Here is a preview:

- https://preview-711--openhwgroup-org.eclipsecontent.org/
- https://preview-711--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Hi Olivier, I can't see the logo on this page: https://preview-711--openhwgroup-org.eclipsecontent.org/

**Comment by oliviergoulet5** [comment]
It should be on the right side if you're on a laptop or desktop.

![image](https://github.com/user-attachments/assets/2607b2bd-4212-46ad-a120-01fed80415d7)

**Comment by ZahraFazli** [comment]
They have to go under the partner section. As mentioned above, they are joining as partners.

**Comment by oliviergoulet5** [comment]
Fixed @ZahraFazli. They should now appear under Partners.

**Comment by Floadv298** [comment]
looks good to me
