### ISSUE TITLE
new Board Member to About Page

### ISSUE THREAD

**Issue by Floadv298** [openhwgroup/openhwgroup.org#712]
Hi @oliviergoulet5 
Please add new Member to About-Us page under "OpenHW Group Board of Directors" 

Keith Hopkins

Keith Hopkins is a serial entrepreneur. He started in Design with Intel and transitioned to Sales/Business Development for EDA, Consulting and Semiconductor IP licensing. Over the past 2 decades, he has worked with multiple early/mid stage companies as VP Sales/Business Development including ARM, Artisan, Denali, PLDA and EVE where he created comprehensive business strategies, developed the Sales/Business Plans, built the Sales teams and accelerated revenues leading to 4 company M&A exits with valuations in excess of $1.5B. He is currently an Executive Advisor, member of multiple Boards and the EVP of Sales and Business Development for Corelab Technology. He has been a part of CPU evolution from Intel to ARM and is excited to get a front row seat for the next stage by joining the OpenHW Board as the world explores RISC-V.

comment: I couldn't find a Linkedin, please keep emtpty

**Comment by oliviergoulet5** [comment]
Hi @Floadv298 

Here is a preview of the change: https://preview-713--openhwgroup-org.eclipsecontent.org/about-us/

**Comment by Floadv298** [comment]
Hi @oliviergoulet5 
ok, fit!
