### ISSUE TITLE
security advisory on axios

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/openhwgroup.org#714]
There is a new [security advisory](https://github.com/openhwgroup/openhwgroup.org/security/dependabot/59) automatically generated against [yarn.lock](https://github.com/openhwgroup/openhwgroup.org/blob/0d531505fb1b145b8a9db856c6877fe704b703aa/yarn.lock#L1).

**Comment by chrisguindon** [comment]
Closing this issue. I believe this was fixed a while ago
