### ISSUE TITLE
Add Job advertisment webpage for Verif EE

### ISSUE THREAD

**Issue by Floadv298** [openhwgroup/openhwgroup.org#717]
Please help to add a new Website for lookign for an Verification EE

We have done this before see here:
[Statement of Work for OpenHW Europe WG HW Verification Engineer](https://www.openhwgroup.org/resources/blog/hardware-verification-engineer/)

I Suggest page name to be "blog/hardware-verification-engineer-202409/"

The New content can be found here (OpenHW Google Drive / OpenHW share / OpenHW Europe / EU Tristan ):
https://docs.google.com/document/d/1zlUBUthxcEa011NuDrAkmRhh4U41W1FPyXXFwkpo1QU/edit#heading=h.2ohdu3h3pkun

**Comment by oliviergoulet5** [comment]
Hi @Floadv298! 

Here is a preview of the post: https://preview-718--openhwgroup-org.eclipsecontent.org/resources/blog/hardware-verification-engineer-2024-09/

Once it is approved by you, I'll merge it into the codebase. Then I'll provide a URL for the page on production. With that URL, you can create a post in the Eclipse Newsroom. This step is needed to have the post appear on the homepage.

I'll give you the details on how you can submit once the page is live.

**Comment by oliviergoulet5** [comment]
Hi @Floadv298, have you had a chance to review the patch?

**Comment by Floadv298** [comment]
looks good, please go live

**Comment by oliviergoulet5** [comment]
I submitted the post to the Eclipse Newsroom. Once moderators have approved it, it will be published as an announcement to newsroom.eclipse.org, as well as eclipse.org and openhwgroup.org.

Here is the URL: https://www.openhwgroup.org/resources/blog/hardware-verification-engineer-2024-09/

**Comment by Floadv298** [comment]
Hi @oliviergoulet5 ,
Thanks a lot for the effort, websie looks great!

For the Newsroom and Eclispe: Could you ask to hold the post?
I just had a internal call and we will have another website to post on Eclispe website and on OpenHW Website from a Job agency.

The OpenHW Website I still want to use, but no need to have a public link.
Thanks
FLo

**Comment by oliviergoulet5** [comment]
@Floadv298 Unfortunately, the job posting was published today in the newsroom at 6:42 AM EST.

I will request for it to be unpublished. FYI, it will no longer appear on the OpenHW homepage either.

**Comment by Floadv298** [comment]
Thanks Oliver and sorry for the trouble. 
Thanks for heling to get the website online!

**Comment by oliviergoulet5** [comment]
No worries @Floadv298!

I'll close the issue now

**Comment by Floadv298** [comment]
Thanks
