### ISSUE TITLE
New sponsor logo UltraSoC

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#72]
please add UltraSoC as a sponsor and link to https://www.ultrasoc.com/

[UL-000371-AW-1-Logo File (EPS).eps.zip](https://github.com/openhwgroup/openhwgroup.org/files/3888580/UL-000371-AW-1-Logo.File.EPS.eps.zip)

**Comment by autumnfound** [comment]
This is live!
