### ISSUE TITLE
Please add I Machines Inc as members on the OpenHW Group website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#720]
I Machines has joined OpenHW Group as Silver Member. 
Please add their logo to the website

URL: https://imachinesinc.com/
![I Machines Logo_Final](https://github.com/user-attachments/assets/e8d7586e-3f7f-486a-9d26-5dd2f6a008f2)

**Comment by oliviergoulet5** [comment]
Hi @ZahraFazli, here is a preview:

- https://preview-721--openhwgroup-org.eclipsecontent.org/
- https://preview-721--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by ZahraFazli** [comment]
Looks good. Thanks
