### ISSUE TITLE
Add CHERI Alliance logo to the website

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#722]
CHERI Alliance is a Partner of OpenHW Group. Please add their logo to the website.

URL: https://cheri-alliance.org/
![Badge founder white - RGB](https://github.com/user-attachments/assets/61b1cadd-a942-4cd3-9bf4-f8b5f5d44b8d)
![Badge founder - RGB](https://github.com/user-attachments/assets/f537a3aa-68dc-4159-b140-592f13cc241e)

**Comment by oliviergoulet5** [comment]
Here is a preview @ZahraFazli 
- https://preview-723--openhwgroup-org.eclipsecontent.org/
- https://preview-723--openhwgroup-org.eclipsecontent.org/membership/members/

**Comment by oliviergoulet5** [comment]
Have you had the chance to review @ZahraFazli ?

**Comment by oliviergoulet5** [comment]
Pinging this issue @ZahraFazli
