### ISSUE TITLE
Sponsors to Members

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#76]
Pls change the title 'Sponsors' to 'Members' above the logos.  Also, change the nav link in the top menu to 'Members & Partners' from 'Partners & Sponsors'.
Rick

**Comment by autumnfound** [comment]
This is live!

**Comment by rickoco** [comment]
Guys - sorry to a pain, but this is not completed as requested.

Change the title "Sponsors" to "Members" above the logos and the nav link in the top menu should read "Members & Partners".

**Comment by autumnfound** [comment]
This has been fixed to read "Members and Partners"
