### ISSUE TITLE
Create privacy@openhwgroup.org email alias

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/openhwgroup.org#8]
We would like to create an email alias for privacy@openhwgroup.org.

This email address should redirect mail to privacy@eclipse.org.

**Comment by rickoco** [comment]
alias will also fwd to rickoco@openhwgroup.org

**Comment by agafgfafa** [comment]
This should be reassigned. Eclipse Webmaster does not manage openhwgroup.org email.

**Comment by rickoco** [comment]
privacy@openhwgroup.org alias created
