### ISSUE TITLE
Partner logo reorder

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#85]
Pls create 2 rows for the partner logos as follows:

1st row: Eclipse, FOSSi, IBM, Publitek, RISC-V
2nd row: Norton Rose, PwC, RBC

**Comment by rickoco** [comment]
Guys - pls update the home page partner section as per below.  Note, IBM Cloud logo should be in the Partner section, not the Member section.

Pls create 2 rows for the partner logos as follows:

1st row: Eclipse, FOSSi, IBM Cloud, Publitek, RISC-V
2nd row: Norton Rose, PwC, RBC

**Comment by autumnfound** [comment]
Apologies! This will be fixed with the upcoming changes

**Comment by autumnfound** [comment]
This is live!
