### ISSUE TITLE
Update About us text

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#9]
About the OpenHW Group
OpenHW Group is a not-for-profit, global organization driven by its members and individual contributors where hardware and software designers collaborate in the development of open-source cores, related IP, tools and software. OpenHW provides an infrastructure for hosting high quality open-source HW developments in line with industry best practices.

**Comment by ericpoirier** [comment]
Hi Rick,

I updated the About us content on the production website.
