### ISSUE TITLE
IBM Cloud logo too small

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#91]
In the Partner section, pls increase the size of the IBM Cloud logo to be more consistent with the rest of the logo sizes.

**Comment by autumnfound** [comment]
This is live! I've updated the IBM Cloud logo to be ~17% larger, to more closely match other logos:
![image](https://user-images.githubusercontent.com/23018241/70451266-0f641580-1a73-11ea-989e-e49651e6e30d.png)
