### ISSUE TITLE
UltraSoC News release

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#93]
Please post the UltraSoC news item as of 6 Dec 2019

[UltraSoC_OpenSourceTraceEncoderPR.docx](https://github.com/openhwgroup/openhwgroup.org/files/3935504/UltraSoC_OpenSourceTraceEncoderPR.docx)

**Comment by autumnfound** [comment]
This is live! https://www.openhwgroup.org/news/2019/12/06/ultrasoc-donates-risc-v-trace-implementation-to-enable-true-open-source-development/
