### ISSUE TITLE
OpenHW RISC-V Summit News Release

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#94]
Please post the OpenHW RISC-V Summit news release as of 9 Dec 2019.

[OHW003(D3)RISC-V Summit.docx](https://github.com/openhwgroup/openhwgroup.org/files/3935512/OHW003.D3.RISC-V.Summit.docx)

**Comment by rickoco** [comment]
@chrisguindon @autumnfound Guys - updated version of the release from Andrea is attached.  Pls post this one.

[OHW003(A)OpenHW Group at the RISC-V Summit 2019.docx](https://github.com/openhwgroup/openhwgroup.org/files/3940523/OHW003.A.OpenHW.Group.at.the.RISC-V.Summit.2019.docx)

**Comment by autumnfound** [comment]
Yup! Saw that when I went to do that this morning. Thanks for checking in!

**Comment by autumnfound** [comment]
This is live! https://www.openhwgroup.org/news/2019/12/09/openhw-group-to-showcase-member-projects-based-on-cv32e-and-cv64a-open-source-cores-at-the-risc-v-summit-2020/
