### ISSUE TITLE
OpenHW - Website font change

### ISSUE THREAD

**Issue by ChristieWittEclipse** [openhwgroup/openhwgroup.org#96]
**Is your feature request related to a problem? Please describe.**
The OpenHW heading font "Orbitron,Arial,sans-serif" is not readable as a H1 header

**Describe the solution you'd like**
Please update the font to use "Open Sans,Arial,sans-serif" which is consistent with the body font and make the font smaller at 43px.

Screenshots included below:
![improvement-recommendation](https://user-images.githubusercontent.com/58480647/70453992-b6e34700-1a77-11ea-9e01-f7b6a4e278a1.png)
![current](https://user-images.githubusercontent.com/58480647/70453995-b8147400-1a77-11ea-8583-f15ecc67b34a.png)

**Comment by chrisguindon** [comment]
> The OpenHW heading font "Orbitron,Arial,sans-serif" is not readable as a H1 header

+1 I did notice the same thing this morning!

**Comment by chrisguindon** [comment]
Thank you @autumnfound and @ChristieWittEclipse
