### ISSUE TITLE
CORE-V Chassis news release

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/openhwgroup.org#97]
please post the attached CORE-V Chassis news release first to go live Tuesday morning Dec 10 UK time.

[OHW002(A2)2020 CORE-V Chassis.docx](https://github.com/openhwgroup/openhwgroup.org/files/3941984/OHW002.A2.2020.CORE-V.Chassis.docx)

**Comment by autumnfound** [comment]
this is live!
